### ISSUE TITLE
put data with metadata as atomic operation

### ISSUE THREAD

**Issue by trel** [irods/irods#2064]
From @PeteClapham at Sanger:

https://groups.google.com/d/msg/irod-chat/O-yncwrqdoY/EaCgWkIkms8J

> On the data input side, pipelines add data and then metadata to the system. Sadly iRODS does not currently support this as a single atomic operation that would roll back should it fail and the client tools do not report back exit codes that reflect the operation status.
> 
> So for large ingests various queries are run per data set addition to ensure all is going to plan. This is an area we have previously discussed with RENCI and are hopeful a resolution may be found.

**Comment by tempoz** [comment]
The way this feature is implemented is that if any part of a "put" fails (metadata attribution, ACL assignment, or the actual data put) the system will be left as though no piece of the "put" had occurred (for example, if the modAccessControl on a 10 GB file fails, the 10 GB that was transferred will be deleted).

**Comment by keithj** [comment]
Am I too early to be using atomic iput with metadata (in 0387ff4) or do I need to enable it in some way? I ask because doing this:

````
dd if=/dev/urandom of=random_file bs=4096 count=1024
iput -K random_file --metadata "foo;99;;bar;100;;"
````

and then interrupting the client before it has finished results in an empty file with no metadata being left behind.

**Comment by jasoncoposky** [comment]
that behavior sounds correct.  no metadata was put as the client process was killed, and a file was left behind due to potential restart.  what was expected?

**Comment by keithj** [comment]
I didn't expect to see any file remaining because the operation is then not idempotent (unless I add `-f` to overwrite any file left by an earlier failed operation). The restart option wasn't used in this case. Would there be a potential restart for some other reason?

**Comment by keithj** [comment]
Also, I set up a test like this:

````
$ irmtrash
$ ils
/tempZone/home/keith:

$ iput -f foo --metadata "foo;99;;bar;100;;"
$ ils -l
/tempZone/home/keith:
  keith             0 demoResc            7 2015-04-25.02:29 & foo
$ imeta ls -d foo
AVUs defined for dataObj foo:
attribute: foo
value: 99
units: 
----
attribute: bar
value: 100
units: 
````

And then attempted the same `iput` again. I expect either idempotence or an error due to duplicated AVUs.

````
iput -f foo --metadata "foo;99;;bar;100;;"
ERROR: putUtil: put error for /tempZone/home/keith/foo, status = -809000 status = -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME
````

I get the latter, which is fine, but now my file has gone...

````
$ ils
/tempZone/home/keith:
````

Are there some docs I can read on the intended behaviour?

**Comment by jasoncoposky** [comment]
we are currently building test cases around this feature, now is a good time to express any expectations.

thanks


On Apr 24, 2015, at 9:36 PM, Keith James <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, I set up a test like this:

$ irmtrash
$ ils
/tempZone/home/keith:

$ iput -f foo --metadata "foo;99;;bar;100;;"
$ ils -l
/tempZone/home/keith:
  keith             0 demoResc            7 2015-04-25.02:29 & foo
$ imeta ls -d foo
AVUs defined for dataObj foo:
attribute: foo
value: 99
units:
----
attribute: bar
value: 100
units:


And then attempted the same iput again. I expect either idempotence or an error due to duplicated AVUs.

iput -f foo --metadata "foo;99;;bar;100;;"
ERROR: putUtil: put error for /tempZone/home/keith/foo, status = -809000 status = -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME


I get the latter, which is fine, but now my file has gone...

$ ils
/tempZone/home/keith:


Are there some docs I can read on the intended behaviour?

-

**Comment by keithj** [comment]
I think @tempoz sums up one aspect very well above by saying *if any part of a "put" fails (metadata attribution, ACL assignment, or the actual data put) the system will be left as though no piece of the "put" had occurred *. I think the two cases above are examples where this doesn't hold.

Another consequence of atomicity is that the operation should be isolated. In the example above

````
dd if=/dev/urandom of=random_file bs=4096 count=1024
iput -K random_file --metadata "foo;99;;bar;100;;"
````

where the file does not exist initially and is large enough for the operation to take a minute or so, I should not be able to launch another client and do this successfully before the first client has finished:

````
imeta add random_file -d foo 99
imeta ls -d random_file 
AVUs defined for dataObj random_file:
attribute: foo
value: 99
units: 

````

However, I can do this and the result for the first client is:

````
ERROR: putUtil: put error for /tempZone/home/keith/random_file, status = -33000 status = -33000 SYS_INVALID_PORTAL_OPR
````

So the second client has managed to interpose is metadata add operation between the step where first client creates the file and the adds its own metadata. IMO that means the operation is not behaving atomically.

**Comment by jasoncoposky** [comment]
We will resolve the two cases above, but the last case with imeta is not possible to implement currently as iRODS does not have a robust locking mechanism, specifically around the application of metadata.  This would be a good point to raise at the Technical Working Group for the 4.2 road map.

**Comment by tempoz** [comment]
I can resolve the problem of a single-buffer put with failed metadata deleting an existing file in case of an overwrite as well as the metadata race condition you described by moving the metadata and acl application to the register operation as opposed to the close operation (and I intend to do just that). However, there is still a larger issue in that parallel transfer puts are not atomic and, in the case of a failed overwrite, will cause the existing file to be overwritten with a partial (bad) put. That extends beyond the scope of this issue, however, and I have opened another issue to handle that here: #2658

**Comment by tempoz** [comment]
After internal discussion, due to the structure of the database plugin and the fact that iRODS is not, in fact, a transactional filesystem, the current behavior will have to be sufficient for now until time can be taken to do a total rewrite of the database plugin. Otherwise this behavior would either introduce possible privilege escalation problems or still not be properly transactional.
With the current iRODS, a failed put operation with an overwrite flag has, unfortunately, already overwritten the file at the point where the metadata is added, and so the behavior cannot be to leave the previous file in place, as it has already been removed. What can be done instead is to leave the newly put file behind in the case that application of either the metadata or the ACLs fail. Input concerning this behavior is appreciated.

**Comment by tcutts** [comment]
From my perspective, the current behaviour is a show stopper for adopting iRODS 4.x.   Surely, the usual mechanism to protect against these issues is to create a new data object alongside, with its own metadata, and only when that is successfully completed, does the code rename it to replace the original.  That would protect against both of Keith's original issues, would it not?  The operation would then not destroy existing data or metadata until it was safe to do so, and would also be idempotent.

**Comment by jasoncoposky** [comment]
This issue is related to the application of metadata and ACLs to a data object.  I feel we are in a position of scope creep for this issue due to iRODS not also providing an increasing level of 'atomicity'.  For this issue we have provided a mechanism for the application of ACLs and metadata from a single API call for a put operation with all of the existing guarantees made the put code.  We can open an additional issue for the prevention of collisions between users ( due to the lack of locking ) and the issue of idempotency caused by the stub files for failed transfers ( for possible restarts ).

**Comment by trel** [comment]
Closing for 4.2.   Additional conversation should be in a new issue.
