### ISSUE TITLE
metadata and full-text indexing service

### ISSUE THREAD

**Issue by trel** [irods/irods#2065]
This is a placeholder for the ongoing discussion for how best to offload indexing to an external service (Lucene, ElasticSearch, etc.).

**Comment by michael-conway** [comment]
To amplify and start tying into DFC architecture discussions

there seems to be a case for a special class of iRODS resource.  This would combine the storage capabilities of iRODS with the ability to run processes on that data in either the indexing or computation.  Perhaps the iPlant 'Docker' model can provide a basis for both. It seems that the consortium model for discovery may be useful in order to discover and address tasks to these special resources?

ps do you guys mind if we add a DFC label to pull various irods tier items from DFC together?

**Comment by trel** [comment]
I think it will be best to put an `irods-core` label on some of the things in other repositories... we want to keep this namespace as clean and non-specific as possible.

**Comment by michael-conway** [comment]
NB iPlant is moving towards a standard model of providing their 'apps' abstraction the ability to run that app in docker on a resource, accessing the physical file system for computation.  Discussed this today w/Nirav.

It seems like a standard infrastructure to run 'computation' as a special resource type is getting real world traction, and perhaps a standard iRODS + docker installable configuration with supporting API could be both part of general computation as well as the 'file content indexer' use case.

**Comment by trel** [comment]
This will most likely be implemented as a series of packaged plugins that provide a service to iRODS clients.  Closing here, since there will be minimal work in the core of iRODS.  The new work will most likely leverage the audit plugin (AMQP) and the QueryArrow database plugin.
