### ISSUE TITLE
create a server runtime library

### ISSUE THREAD

**Issue by trel** [irods/irods#2308]
Migrate all object code from the agent executable into an independent runtime shared object.

This will allow smoother and safer upgrades as plugins also depend on symbols which are currently statically linked into the agent.

Have this shared object be the same one installed by the runtime package.

**Comment by vladimir-mencl-eresearch** [comment]
Hi,

as per the discussion at http://groups.google.com/group/irod-chat/t/a292a2324cc36a I'd also add 
that all client binaries would also have to link against libirods_client.so to avoid the duplication.

And all runtime libraries (jansson, boost, ...) should be linked dynamically so that plugins can properly declare a dependency on the code without loading the code multiple times...

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
Oh, and to add: doing so would require reorganizing the build system, as the libirods_client* libraries are only created at a later stage when building the dev+runtime packages.

And, in the build tree, the libirods_client.so symlink (pointing to the versioned libirods_client.so.1.0.0 library) does not get created at all - it only exists in the RPM/deb packages built.

So building plugins and client+server executables linked against these libraries would not be possible without a serious reorganization of the build process...

Cheers,
Vlad
