### ISSUE TITLE
update iget help to explain dirty replica behavior

### ISSUE THREAD

**Issue by trel** [irods/irods#2485]
As per the conversation here:  https://groups.google.com/forum/#!topic/iROD-Chat/6BH-EF_O37E

Add explanation of `iget` behavior in the presence of dirty replicas.  Also consider adding dirty replica definition and expected behavior into the manual somewhere.

**Comment by Wayne-Schroeder** [comment]
When you write up the description, be sure to define what is meant by 'clean' and 'dirty'.  In the past at least, technically 'dirty' meant, I believe, that the data item had be written to, so the use of the terms was turned around in the discussion.  But it's more natural to think of the clean copy as the one you want, so it gets messy to describe.  - Wayne -

**Comment by trel** [comment]
This is a good point - I have always been confused as to the database value that is used to mark the dirty and clean state.  We'll make sure they're consistent.

**Comment by Wayne-Schroeder** [comment]
I think it's standard computer science terminology to call it 'dirty' when a page or data-object has been written to; typically used in OSes but applies to distributed file systems too.  Raja and Mike Wan used the 'dirty' term for the column in SRB and Mike and/or Raja suggested it for iRODS too, and that seemed fine to me since it is standard usage (I just had to get my head around 'dirty' being good).  So I think it would best to simply document it well so everyone is clear on it.  Just my US $0.02 worth tho.
