### ISSUE TITLE
Correct use of rcDataObjFsync

### ISSUE THREAD

**Issue by keithj** [irods/irods#2499]
In a client application on 3.3.1 (https://github.com/samtools/htslib) data are written by calling these API functions in order:

````
rcDataObjOpen
rcDataObjWrite x n
rcDataObjFsync
rcDataObjClose
````

We observed that calling ````rcDataObjFsync```` in this context caused an error and the file
deposited was reported as size 0 by ```ils```

````
ERROR: readMsgHeader:header read- read 0 bytes, expect 4, status = -4115
ERROR: readAndProcApiReply: readMsgHeader error. status = -4115 status = -4115 SYS_HEADER_READ_LEN_ERR, Operation now in progress
samtools: error closing "irods:toy.bam": -1
````

However, despite being reported as size 0, we can open it and read all the data (using API calls),
while ````iget```` downloads an empty file.

Simpy removing the call to ````rcDataObjFsync```` results in the behaviour we expect i.e. no errors
and a correct file.

Is it wrong to be using ````rcDataObjFsync```` in this context? I notice that e.g. ````iput```` doesn't
call it (that I can find).

Thanks.

**Comment by jmarshall** [comment]
I see `rcDataObjFsync()` et al were removed in e78a6c105db3ec1865211297625578ccc8cae2e7 due to #1661, though there's not a lot of explanation of why they were removed.

I guess this suggests that even in clients aimed at 3.3.x, the correct use of `rcDataObjFsync` is not to use it..?

**Comment by trel** [comment]
Sorry for the delay...

Generally, we are heading in the direction of object based semantics, rather than POSIX, and off-loading the specific implementation details to the resource plugins.

We found no code paths that exercised this API, which encouraged us to remove it.

So, yes, it is fair to say that the correct use of `rcDataObjFsync` is not to use it.

Closing the question - definitely reopen / comment if this is not sufficient.

Thanks to both of you.
