### ISSUE TITLE
Investigate TCP_KEEPALIVE on the server

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2533]
- [x] main
- [x] 4-3-stable
---
@michael-conway 

To address parallel transfer timeouts noticed at iPlant.

Possibly allow setting of the following in `server_config.json`:
- `tcp_keepalive_time`
- `tcp_keepalive_intvl`
- `tcp_keepalive_probes`

**Comment by trel** [comment]
related to https://github.com/irods/irods/issues/5218

**Comment by PaulVanSchayck** [comment]
Having spent a couple of days debugging idle iRODS connections being killed across firewalls, I would strongly argue in getting this implemented.

In our case the 1247 server between two resource servers was timed out when one side of a msiDataObjRepl command was performing the checksum on a file. The resulting error messages looked very confusing (errors during checksum) and it took a while to figure out it was really the connection timing out. 

Setting the tcp_keepalive flag on all iRODS server sockets (catalog provider and consumer) , and having its value configurable from `server_config.json` makes a lot of sense to me. This is quite a bit better than the server wide sysctl setting applying to all sockets. TBH, I see little reason not to do this and also set a relatively aggressive default 10 minute value on `tcp_keepalive_time`. iRODS is dependent on keeping these connections alive, and an automatic reconnect mechanism is much harder to implement (due to PEPs).

For future readers, I found it useful to look at `netstat -n --tcp --timers` to debug the situation. I didn't find a reliable `tcpdump` filter to only catch keepalive ACK packets.

**Comment by trel** [comment]
Agree on all points, including the default 10min.   Thanks Paul.
