### ISSUE TITLE
Authentication always fails for OS X clients

### ISSUE THREAD

**Issue by jmarshall** [irods/irods#2578]
The following is `iinit` built on Mac OS X from current **master**, with some function addresses printed out for debugging.  Similar happens with 4.0.3.

    $ iinit
    In iinit.cpp: MD5Init (0x106b09470)
    In iinit.cpp: MD5Update (0x106b094c0)
    In iinit.cpp: MD5Final (0x106b0a9f0)
    Enter your current iRODS password: [type password (correctly!)]
    libnative.cpp calling MD5Init (0x106b09470)
    libnative.cpp calling MD5Update (0x106b094c0)
    libnative.cpp calling MD5Final (0x7fff8516385f)
    [-]	libnative.cpp:344:native_auth_client_response :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [Call to rcAuthResponseFailed.]
    failed with error -826000 CAT_INVALID_AUTHENTICATION 

Notice that the libnative.so plugin calls the expected MD5Init and MD5Update functions, but sees a different MD5Final function from the md5c.cpp one that iinit.cpp sees.  This other MD5Final function gets given a MD5_CTX that it doesn't understand and mostly either returns an incorrect digest (hence endless CAT_INVALID_AUTHENTICATION) or crashes.

The problem is that the OS X system library libcommonCrypto.dylib defines symbols `CC_MD5_Init`, `CC_MD5_Update`, `CC_MD5_Final`, and `MD5Final`.  The latter is undocumented and clearly a bug, but sadly it's been this way since 10.6.  This library is pulled in by libSystem, so essentially any typically-linked object will be polluted by this spurious `MD5Final` function.

`iinit` and other executables are explicitly linked with libRodsAPIs or so, so pull in md5c.cpp's MD5Final() and it takes precedence over the libcommonCrypto one.  However plugins' need for MD5Final() is satisfied via the libSystem they themselves have been linked with, and this takes precedence over the desired md5c.cpp one that the main executable would otherwise provide.

**Comment by jmarshall** [comment]
To be clear, the problem is that iRODS/lib/md5/src/md5c.cpp is broken on OS X when called from plugins, but the result is that authentication is broken and you can't do anything.

Possible fixes, at least one of which wouldn't work:

1. On OS X, link the plugins really carefully with `-nodefaultlibs` and no `-l`libraries that might pull in system stuff.  Very fragile, and unworkable for plugins that need libraries that the main executable doesn't provide.

2. Link libRodsAPIs.a or just md5c.o into the plugins.  Not too ideal.

3. (Optionally) discard iRODS/lib/md5 in favour of the system MD5, which on OS X might be `<CommonCrypto/CommonDigest.h>`'s `CC_MD5_Init()`/etc.  (See also #1998.)

4. Rename md5.hpp/md5c.cpp's functions to avoid this clash.  This could be a quick hack of adding `#define MD5Final MD5Final_iRODS` to md5.hpp or renaming all three to `irods_MD5foo()` or similar globally.

**Comment by ilarik** [comment]
I struggled with the same issue earlier and did some digging. I too did a fix to the code to use CommonCrypto MD5 and then decided to change the linkage to include `irods/iRODS/lib/md5/obj/md5c.o` into `libnative.so` which seemed the most simple way to correct the issue. 

In OS X the iRODS native auth module `libnative.so` has to have the necessary MD5 symbols locally so that the runtime dynamic linker wouldn’t resort to symbol `_MD5Final` from the system library `/usr/lib/system/libCommonCrypto.dylib`. In my opinion this is because the linkage is done with runtime dynamic lookup enabled in OS X as the file `irods/plugins/auth/Makefile.base` has

```
ifeq ($(OS_platform), osx_platform)
LDADD += "-Wl,-undefined,dynamic_lookup"
else
LDADD += "-Wl,-E"
endif
```

When the iRODS icommands binaries load the `/var/lib/irods/plugins/auth/libnative.so` in OS X and resolve for the auth interface routines which in turn call MD5 functions (`MD5Init`, `MD5Update` and `MD5Final`) which are left unresolved at link time for the native auth shared library and are thus resolved at runtime. This appears to be no problem in Linux since the MD5 symbols in question can and will be resolved to the irods binary loading the module (such as `iinit`) which already have by default the MD5 routines linked statically into them with a locally provided library `irods/iRODS/lib/md5/obj/md5c.o`.

In Linux we have the following result for the working default build config:

```
% objdump -T /var/lib/irods/plugins/auth/libnative.so | grep MD5 | c++filt
0000000000000000      D  *UND*	0000000000000000              MD5Init
0000000000000000      D  *UND*	0000000000000000              MD5Final
0000000000000000      D  *UND*	0000000000000000              MD5Update
% objdump -T `which iinit` | grep MD5Init | c++filt
0000000000494bc0 g    DF .text	000000000000002a  Base        MD5Init
% objdump -T `which iinit` | grep MD5Update | c++filt
0000000000495770 g    DF .text	000000000000018c  Base        MD5Update
% objdump -T `which iinit` | grep MD5Final | c++filt 
0000000000495900 g    DF .text	000000000000019a  Base        MD5Final
```

The previous listing shows that the symbols `MD5Init`, `MD5Update` and `MD5Final` are located in the `.text` section of the `iinit` binary. Linux ld.so seems to be perfectly happy resolving the undefined linkages correctly to the loading ELF binary image.

In OS X on the other hand the linker goes haywire and starts searching for the undefined symbols in the secondary symbol namespace (external libraries) instead of the locally defined ones (I don’t know why this is so). So when it's trying to do the MD5 hash in the challenge-response authentication sequence the MD5Final call wreaks havoc with the MD5 buffer since it has been resolved to the wrong one by the runtime linker (namely the one in `/usr/lib/system/libCommonCrypto.dylib`).

My solution for this was to modify the linkage of `libnative.so` such that it gets the `irods/iRODS/lib/md5/obj/md5c.o` linked to it. I have the following in the file `irods/plugins/auth/native/Makefile`:

```
EXTRALIBS = ../../../iRODS/lib/core/obj/irods_plugin_base.o \
            ../../../iRODS/lib/md5/obj/md5c.o
```

With this kind of linkage the native auth module gets the three MD5 symbols as externally visible local symbols in the `__text` section i.e.

```
$ nm -gm /var/lib/irods/plugins/auth/libnative.so | grep MD5
000000000000aeab (__TEXT,__text) external _MD5Final
000000000000ad2a (__TEXT,__text) external _MD5Init
000000000000ad78 (__TEXT,__text) external _MD5Update
```

The “reason” for why only the MD5Final gets linked wrong is visible in the following:

```
nm -gm /usr/lib/system/libcommonCrypto.dylib|grep MD5
0000000000004fc8 (__TEXT,__text) external _CC_MD5
0000000000004ec1 (__TEXT,__text) external _CC_MD5_Final
0000000000004cfb (__TEXT,__text) external _CC_MD5_Init
0000000000004db4 (__TEXT,__text) external _CC_MD5_Update
0000000000005385 (__TEXT,__text) external _MD5Final
```

That is, the two other MD5 function names `MD5Init`, `MD5Update` and `MD5Final` are only used in precompiler macros defined in the headers that point to the “appropriate” library calls to be used. For some reason there is still another `MD5Final` call in the common crypto library. In `/usr/include/CommonCrypto/CommonDigest.h` we have the following:

```
#define MD5_Init                    CC_MD5_Init
#define MD5_Update                  CC_MD5_Update
#define MD5_Final                   CC_MD5_Final
```

In this case since the code is not being compiled against those headers the symbols get conflicted especially when using the dynamic lookup scheme. Otherwise the linking would result in unresolved symbols and the problem would be visible at link time. 

The previous poster had already identified the problem correctly but I just thought I should share my thoughts and notes on the issue.

**Comment by kellerb** [comment]
Thank you for this very detailed and clear explanation.

I believe the current plan is to use @jmarshall's third proposed solution, which is to link against the system MD5 implementation, instead of building our own.

**Comment by ilarik** [comment]
I just made a pull request for using the system MD5 implementation on OS X, see #2589.

**Comment by jmarshall** [comment]
Any progress on this?

As this issue completely breaks native authentication on OS X, and assuming (per [this comment](https://github.com/irods/irods/issues/1413#issuecomment-37457883) on #1413) that OS X remains a supported platform, it would be reassuring if this issue could be added to the _4.1.0_ milestone.

**Comment by kellerb** [comment]
We should now be using the OpenSSL implementation of the MD5 as of the latest commit against #1998, which have different names, which should prevent the collision with the Mac system implementation.

**Comment by jmarshall** [comment]
Thanks, `iinit` works now.  (It would have been helpful if 56cdf463e3435dd6fcb7ddd862f05794683ef2c9's commit message had referenced this bug report too.)

Note that `<openssl/*.h>` is marked as deprecated on OS X in favour of [Common Crypto](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/CC_crypto.3cc.html).  It's unclear just what this implies, but presumably it would be advisable to use `CC_MD5_Init()`/etc on OS X instead of the openssl functions.  (To be sure, this is a headache of Apple's own making that portable code may not wish to pander to…)

**Comment by kellerb** [comment]
Created common crypto issue #2649
