### ISSUE TITLE
msiGetStderrInExecCmdOut segfaults if ExecCmd errors out

### ISSUE THREAD

**Issue by trel** [irods/irods#2604]
From @tedgin at https://groups.google.com/forum/#!topic/irod-chat/TOUZZLXSnWs:

`msiGetStderrInExecCmdOut` does not work if the binary in ExecCmd errors out

since ExecCmd leaves `*out` as null, `msiGetStderrInExecCmdOut` segfaults

**Comment by tedgin** [comment]
Could `msiExecCmd` be modified so that it populates `*out` even if the spawned process exits with a non-zero status? I would like to use `msiExecCmd`'s return code to determine whether or not the spawned process succeeded, and, on failure, I would like to be able log the stderr of the process for clues on why it failed.

**Comment by xu-hao** [comment]
Thanks for the suggestion. I think what you suggested should be the default
behavior.

**Comment by trel** [comment]
@tedgin please nod and we'll get this closed.   thanks.

**Comment by tedgin** [comment]
*nods*  ;-)

**Comment by tedgin** [comment]
In other words, through code inspection, the changes look good.

**Comment by jasoncoposky** [comment]
closing now that a test has been added.
