### ISSUE TITLE
jansson .so missing versioned symlink

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [irods/irods#2642]
Hi,

I tried linking my code against libjansson.so.  The runtime dependency got recorded as libjansson.so.4.

However, the irods-runtime package only contains

     /usr/lib/irods/externals/libjansson.so.4.7.0

and

    /usr/lib/irods/externals/libjansson.so -> libjansson.so.4.7.0

It should also contain:

    /usr/lib/irods/externals/libjansson.so.4 -> libjansson.so.4.7.0

Thanks a lot in advance for looking into it!

Cheers,
Vlad

**Comment by kellerb** [comment]
Thanks for finding that, not creating soname links was a holdover from when we were installing all the external libraries directly into `/usr/lib` and letting `ldconfig` create them.

Feel free to close this issue if the symlinks are working as you expect.

Btw, we have changed the layout of the libraries since 4.0.3 (as you have probably noticed). The plan behind that change is [mentioned here](https://github.com/irods/irods/issues/2494#issuecomment-75417512). Please let us know if you have ideas on how to improve this. We want the libraries to be as easy to use as possible. I am taking note of all your library suggestions.

**Comment by vladimir-mencl-eresearch** [comment]
Hi Ben,

Thanks for quick response and for the links.  I have not yet tested a new build, but this commit should fix the issue with the so names.  

There should be both the unversioned .so symlink (for linking new executables) and the major-version symlink (.so.M executables would request from ld.so) pointing to the exact version - I see the packaging list for runtime now has that.

The big task ahead would be to make all shared code linked dynamically - that would include changing the build process for all binaries (server and client), and changing the order of the build process and the package dependencies (the libraries are now built only at the end as part of the irods-runtime package, not required by the core binary packages like irods-icat).

And, I think that should also include linking against boost dynamically (as now, the plugins just expect boost symbols can be fetched from the main executable).

BTW, I did find a workaround to my issue with the dlopen-loaded library linked against iRODS: use LD_PRELOAD to pre-fetch my library into the main program symbol table, and then loading plugins works.

So the issue with how plugins are linked (expect to be loaded into a environment with all the symbols they need without declaring them as a dynamic link dependency) is now longer a show-stopper for me - but it would still be very appreciated to see a proper solution instead of having to rely on this hack.

Cheers,
Vlad
