### ISSUE TITLE
"iput -h" and "iget -h" have return code 1

### ISSUE THREAD

**Issue by trel** [irods/irods#2703]

**Comment by jmarshall** [comment]
However now `iget --bork foo - > localfoo` also has exit status 0.  The combination of usage error message going to stdout and return code 0 means that scripts using this can't distinguish between success and failure due to mistyped options.  Even with `iget --bork foo localfoo` you'd need to parse stdout or carefully check localfoo before and afterwards to distinguish these.

It's desirable for `iget -h` to have zero exit status, but it's **necessary** for `iget --bork` to have non-zero exit status.  See also [Stack Overflow: What are the conventions for stdout/stderr messages?](http://stackoverflow.com/questions/7977852/)

**Comment by jasoncoposky** [comment]
Thanks for catching this, fixing now.

**Comment by jmarshall** [comment]
Excellent, thanks!
