### ISSUE TITLE
Determine which hostname irods_control.py should use with irods-grid

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2771]

**Comment by tempoz** [comment]
irods_control uses the hostname returned by `socket.getaddrinfo(socket.gethostname(), 0, flags=socket.AI_CANONNAME)[0][3]`, which should be the same as an external call to `hostname -f`. This ought to route to the host machine. In the instances it does not, irods_control will still fall back to killing the processes. We cannot simply use `localhost` because `irods-grid` is not guaranteed to resolve the hostname locally, and thus rejects `localhost` as an argument categorically.
