### ISSUE TITLE
coredump with iphymv and root of filesystem

### ISSUE THREAD

**Issue by trel** [irods/irods#2815]
With two good resources:

```
irods $ iphymv -S test1 -R test2 -r /
Segmentation fault (core dumped)
irods $ echo $?
139
```

The rodsLog shows:

```
Jul 27 09:22:24 pid:5838 ERROR: [-]     iRODS/server/core/src/rsApiHandler.cpp:470:readAndProcClientMsg :  status [SYS_HEADER_READ_LEN_ERR]  errno [Resource temporarily unavailable] -- message []
        [-]     iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [Resource temporarily unavailable] -- message [failed to call 'read header']
                [-]     libtcp.cpp:240:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [Resource temporarily unavailable] -- message [read 0 expected 4]

Jul 27 09:22:24 pid:5838 NOTICE: Agent exiting with status = -4011
```

**Comment by tempoz** [comment]
This occurs because the root collection claims itself as its parent, so when you ask for all subcollections of the root collection, the root collection is listed. This results in infinite recursion, eventually overflowing the stack and causing a segmentation fault. The fix is twofold: one, do not return the root collection when querying for subcollections; and two, do not accept the root collection as an argument to phymv, since physical moves only make sense within a zone.
