### ISSUE TITLE
Impostor resource hides resource plugin load errors

### ISSUE THREAD

**Issue by AndreyNevolin** [irods/irods#2868]
If a particular resource driver cannot be loaded at runtime, iRODS server doesn't report the error, but instantiates impostor resource instead.

As far as I understand, the reason for this behavior is the following:

1. iRODS Server and iRODS Agent initialization procedure doesn't distinguish between different resource servers
2. That means that an attempt is made to instantiate all known resources on every resource server available
3. But some resource servers may not serve storage resources of a particular type => they may not have appropriate plugins
4. That's where impostor resource is useful

I.e. instantiation of impostor resource implies that the host resource server is not expected to manage storage resources of a particular type.

But this conclusion cannot be made based on an unsuccessful attempt of resource instantiation. Expectation of resource server functions can be based on a grid configuration only.

Existence of impostor resource significantly complicates investigation of resource plugin load errors. If a resource plugin cannot be loaded, iRODS implies that it shouldn't. But sometimes that's not the case (see bug #2867). In such cases the issue cannot be investigated further without building iRODS from source.

Please fix.

**Comment by jasoncoposky** [comment]
All resources are instantiated in memory by a server in order to provide the decision logic of a resource hierarchy.  An impostor resource is instantiated in the instance where a storage resource of a particular type is not available, such as an archive resource hidden behind a compound resource hierarchy.

We could possibly load an impostor plugin if the plugin does not exist at the expected location, and 
otherwise dump the errors to the log.

**Comment by AndreyNevolin** [comment]
I didn't get the reasoning behind impostor resources. Could you please explain how they help with resource hierarchies?

**Comment by kellerb** [comment]
During initialization, an iRODS agent constructs the entire resource hierarchy in memory (the current hierarchy can be seen with `ilsresc --tree`). This involves loading the appropriate plugin for each type of resource present in the hierarchy. Before the [impostor resource was added](https://github.com/irods/irods/issues/2186), this meant that every iRODS server needed a copy of every resource plugin used in the Zone. This requirement was both cumbersome for administrators (adding a new resource type to a Zone's resource hierarchy meant installing a new plugin on every server in the Zone) and complicated for some resource plugin developers (some resource plugins had external dependencies that made installing them on every server difficult at best).

The impostor resource relaxes this requirement, allowing iRODS agents to instantiate the entire resource hierarchy without needing to load all the plugins.

**Comment by AndreyNevolin** [comment]
Thanks Keller! Good explanation.
But I don't understand why you Jason relate the issue to 'hierarchy' case. The problem exists for ANY resource. Before impostor resource type was introduced, iRODS agents instantiated ALL resources registered in the system.
The second thing I don't understand is why the agents do that. (Actually they still do. But now this activity is hidden by means impostor resources). As far as I understand, under current iRODS paradigm particular resources are strictly associated with particular iRODS resource servers. So, I would expect that each resource server loads only that part of the hierarchy that it explicitly manages.

Could you please explain why that's not the case?

Sorry, for lots of questions. I believe that better understanding of the situation will prevent me from inappropriate actions and questions in future :)

Thanks!

**Comment by kellerb** [comment]
The questions are great :) If there is something you don't understand, chances are it isn't being explained very well and many other people are also wondering.

**Comment by kellerb** [comment]
To answer your first question (why are we involving the hierarchy in the explanation):
An iRODS agent attempts to load a resource plugin if and only if that type of resource is present in the resource hierarchy (i.e. present in an `ilsresc --tree`). So when you say that

>iRODS agents instantiated ALL resources registered in the system

the "resources registered in the system" are just those that are present in the hierarchy. This means, for example, that if you originally had exactly one Amazon S3 resource in your hierarchy (i.e. a resource of type `s3`), and then removed it (e.g. via `iadmin rmresc ...` etc.), newly created iRODS agents would no longer attempt to load the S3 plugin (i.e. they would no longer attempt to `dlopen()` `libs3.so` from `/var/lib/irods/plugins/resources`).

To answer your second question (why do iRODS agents load the entire resource hierarchy):
Consider the case of an iRODS Zone with:
* one iCAT server (IES) and two Resource servers
* one root-level resource, a `replication` resource
* that has two child resources, both `unixfilesystem` resources, one on each Resource server

A client connects to the IES and requests a data object (through an API call to [rsDataObjGet](https://github.com/irods/irods/blob/4.1.5/iRODS/server/api/src/rsDataObjGet.cpp#L28)).

How does iRODS (specifically, the `irodsAgent` process `fork()`'d by the `irodsServer` process to handle this client connection) determine which iRODS server and which leaf node of the resource hierarchy (i.e. which storage resource) should handle the request?

iRODS asks the hierarchy, through [resolve_resource_hierarchy](https://github.com/irods/irods/blob/4.1.5/iRODS/server/core/src/irods_resource_redirect.cpp#L423). This function (indirectly, through calls to other functions, all found in the same source file) iterates through the root nodes of the hierarchy (there is only one in our example, the `replication` resource), and asks each one for a vote (a `float` between `0` and `1`) and a resource hierarchy string (a list of resources connecting the root node and that root node's chosen leaf node). `resolve_resource_hierarchy` then returns the resource hierarchy string that had the highest vote, and iRODS continues on processing the request, using that specific path through the resource hierarchy whenever necessary. Note that this could include redirecting to the iRODS server specified by the `location` attribute of the storage resource in the resource hierarchy string.

How do the root nodes determine their vote and resource hierarchy string?
The behavior of any resource is defined by its type and implemented by its corresponding plugin. [In this
case](https://github.com/irods/irods/blob/4.1.5/plugins/resources/replication/librepl.cpp#L1784), the plugin's implementation of the `RESOURCE_OP_RESOLVE_RESC_HIER` operation. For a `replication` resource, this is along the lines of "ask each child resource for their answer and return the (vote, hierarchy string) pair with the highest vote". Notice that, generally speaking, coordinating resources (which, in the language of [trees](https://en.wikipedia.org/wiki/Tree_%28data_structure%29), are inherently the "internal nodes" of the resource hierarchy, since they don't actually have any data) implement `RESOURCE_OP_RESOLVE_RESC_HIER` recursively, by querying all their children, then performing some computation on the results. This means that when iRODS asks which resource it should use to handle a request (with the aforementioned `resolve_resource_hierarchy`), the query is generally going to propagate throughout the entire resource hierarchy, which requires each resource to respond to the query, which requires each type of plugin to be loaded, since resource behavior is implemented by the plugin.

That is why, originally, each server in the Zone needed to have a copy of each plugin.

You may notice that, since resource behavior (e.g. the response to `RESOURCE_OP_RESOLVE_RESC_HIER`) is implemented by its corresponding plugin, and the impostor resource replaces that plugin, the behavior of an iRODS agent could change depending on whether it has access to the actual resource plugin, or is using the impostor resource. This is true in general. However, normally the resources being replaced by impostor resources are the `archive` children of a `compound` resource (e.g. an `s3` resource). The `compound` resource does not query its `archive` child, (only its `cache` child), so in this case the behavior of the agent is unchanged by the presence of an impostor resource.

Note that in the above discussion, we focused on a simple resource hierarchy of a single `replication` resource with `unixfilesystem` children. It may be the case that, in this instance, it would be possible to examine the hierarchy and determine, without invoking all of the plugins, which leaf node should be used and to which iRODS server the IES should redirect the request. However, in the general case of arbitrary resource hierarchies of arbitrary resource types using arbitrary implementations of the resource plugin operations (specifically `RESOURCE_OP_RESOLVE_RESC_HIER`), the only way to know how the hierarchy will respond to `resolve_resource_hierarchy` is to ask it.

**Comment by trel** [comment]
We need to:
1) create a new error for missing plugins
2) [return that error if the plugin does not exist](https://github.com/irods/irods/blob/4.1.5/iRODS/lib/core/src/irods_resource_plugin.cpp#L296), rather than trying to call `dlopen()` in [`load_plugin()`](https://github.com/irods/irods/blob/4.1.5/iRODS/lib/core/include/irods_load_plugin.hpp#L164)

**Comment by AndreyNevolin** [comment]
@kellerb thank you very much for the detailed explanation. I'm sorry for returning to this thread after the long silence. I was on vacation an needed some time to get bet to the issue :)

Seems, now I understand the whole picture. Previously I suggested that since each resource - coordinating or actual one - is associated with a particular resource server, than all resource plugin requests should be executed on associated resource servers. I thought this is true for "redirect" action also.

But now I see that this schema is not valid. Instead all redirect operations are executed on a single resource server. Maybe that was done for performance reasons.

As I can see, there are two consequences associated with this implementation:
1) If one needs to have 'real' voices on every request, he/she needs to keep all resource drivers on each resource server (otherwise some voices may be substituted by impostor resource voice)
2) It may happen that a resource driver may need physical access to an associated storage system to produce its voice. And physical access may be possible from one resource server only (i.e. resource server associated with the logical resource). In this case voting process may fail if voting is executed on a different resource server.

May I ask also some quick questions? They will help me to make sure that I got your wonderful explanation right.

1) Seems, all registered logical resources are treated as a single resource hierarchy. E.g. if we have only two resources - of S3 and WOS types - there is one resource hierarchy with two isolated roots. Is that true? Previously I suggested that 'hierarchy' is a construct growing from a single root (i.e. if we have two roots, that means we have two disjoint hierarchies). Seems, I was wrong
2) You say that "iRODS continues on processing the request, using that specific path through the resource hierarchy whenever necessary". But looks like only the last point of the path is used. iRODS redirects directly to a resource server associated with the point. Is that true?

Sorry for returning to this. I really appreciate the time you spent on explaining all this stuff.

Thanks!

**Comment by kellerb** [comment]
Keep the questions coming :)

Your two consequences seem correct to me.

To answer your questions:

1. The resource hierarchy can contain more than one tree, i.e. have multiple isolated roots like in your example. The confusion is our fault, we refer to the resource hierarchy as a tree instead of a forest.
2. Yes, [`resource_redirect()`](https://github.com/irods/irods/blob/4.1.6/iRODS/server/core/src/irods_resource_redirect.cpp#L596) redirects the request to the [iRODS server corresponding to the leaf node of the specific path through the hierarchy](iRODS/server/core/src/). I just meant that the redirected API request will come with the already resolved hierarchy path, so any additional decisions that iRODS makes will use that existing path, not ask for another vote.

**Comment by AndreyNevolin** [comment]
Thanks! Wonderful explanation!
