### ISSUE TITLE
Missing irods_external_4.1.5_Debian.tar.gz

### ISSUE THREAD

**Issue by bzizou** [irods/irods#2873]
To build irods on a Debian based system, the build script tries to download irods_external_4.1.5_Debian.tar.gz but this file is missing while irods_external_4.1.4_Debian.tar.gz exists.

**Comment by trel** [comment]
Debian is not in our continuous integration system.  That is the reason it is not generated by default.

You can generate it yourself by running `make generate` in the external/ directory.

I have built and posted irods_external_4.1.5_Debian.tar.gz and irods_external_4.1.6_Debian.tar.gz just now.

**Comment by bzizou** [comment]
Thank you!
I suggest this patch of the Makefile, so that when we have generated a new tgz, we can copy it on other host and prevent de build script to erase it:

```
@@ -69,8 +69,10 @@ ifeq ($(OS_platform), osx_platform)
 default : generate
 else
 default :
-       @echo "Getting $(IRODSEXTERNALARCHIVE) -> $(IRODSEXTERNALLOCAL)..."
-       $(V_at)curl -o $(IRODSEXTERNALLOCAL) -z $(IRODSEXTERNALLOCAL) $(IRODS_FTP_BUILD)/$(IRODSEXTERNALARCHIVE) > /dev/null 2>&1
+       @if [ \! -e $(IRODSEXTERNALLOCAL) ] ; then \
+               echo "Getting $(IRODSEXTERNALARCHIVE) -> $(IRODSEXTERNALLOCAL)..." ; \
+               curl -o $(IRODSEXTERNALLOCAL) -z $(IRODSEXTERNALLOCAL) $(IRODS_FTP_BUILD)/$(IRODSEXTERNALARCHIVE) > /dev/null 2>&1 ; \
+       fi
        $(V_at)$(MAKE) $(FAKETARGETFORMAKE)
 endif

```

**Comment by trel** [comment]
Understood.

Originally, we didn't want the check to be as simple as 'if the file does not exist', since we were changing the externals much more often and always wanted the latest from the ftp site (we have changed the logic a bit in the master branch already).

I would suggest, if you need to move the file to a different host, manipulating the modified time with the `touch -t` command:
```
       -t STAMP
              use [[CC]YY]MMDDhhmm[.ss] instead of current time
```

As Debian is not a supported platform in our CI, and the 4-1-stable branch is only getting bugfixes, I'm not going to update the Makefile at this time.

We're racing to CMake as quickly as possible.

**Comment by bzizou** [comment]
OK, no problem!
"racing to CMake": that's a very good thing! Go go go! :-)
