### ISSUE TITLE
Facilitate installation automation

### ISSUE THREAD

**Issue by mpasserini** [irods/irods#3010]
I've been trying to automate the installation of iRODS with Puppet, but it's not that easy, mainly because of the following script:
https://github.com/irods/irods/blob/d3d9ef0a5eea9e3cbc0f78f58ea659f842368762/packaging/setup_irods.sh
It's not easy to handle an interactive script from an automation tool. It also does things which are not that obvious, like chowning the irods installation folder etc.
Do you think this could be improved in the future?
For example we could provide it an answer file that would be sufficient to run everything without any user interaction?

**Comment by jasoncoposky** [comment]
Per issue https://github.com/irods/irods/issues/2917 we are moving the entire setup process to pure python.  A json configuration file will be one of the potential ways to setup iRODS rather than an interactive process.

**Comment by kellerb** [comment]
https://github.com/irods/irods/issues/2790 covers adding a json input option to the install script.

Can you be more specific about the difficulties you are experiencing? We are currently reworking the setup process and I want to make sure we address as many issues as we can.

Wrt. the `chown`ing of the installation folder, that is done so that users can choose during setup which OS account will run the iRODS server.

Please feel free to voice any ideas for improving setup.

**Comment by mpasserini** [comment]
Well, at a first sight I would think that there is no need to install the packages first as root and then chown them to the system user irods. Just make irods as default system user for the installation. I don't see why and end user would want to call it in any other way.

I would also do so that when the irods daemon starts the first time it loads all the settings from the configuration files and creates the entries in the DB if the needed tables don't exist.

This would make the automatic deployments easier I think.

**Comment by cookie33** [comment]
Hi,

I think this is because under iRODS 3.3.x and lower you where able to install it as any user you wanted.
So iRODS could have been installed/run under any user. f.i. "mpasserini".
At our site it is the user "rods" at an other it is "orfeus".

To be compatible with older versions you need to have this functionality.

Greetings,

Robert

**Comment by kript** [comment]
Don't forget about kerberos as well - we have different accounts for different zones, so we do NOT want the irods user hard coded.

Cheers!

**Comment by Pete-C** [comment]
+1 on the kerberos aspect. The token requires a unique service user for the Kerberos backends. Not being able to select the run time user name will impact any group with multiple kerberised zones. 

    On Monday, 11 January 2016, 10:04, John Constable <notifications@github.com> wrote:
 

 Don't forget about kerberos as well - we have different accounts for different zones, so we do NOT want the irods user hard coded.

Cheers!

**Comment by trel** [comment]
closing this as duplicate - #2790 should handle these cases already.
