### ISSUE TITLE
Investigate msiGetSessionVarValue() in core.re

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3035]
`msiGetSessionVarValue()` is used in several commented `core.re` example rules. Uncommenting e.g. the `acPreprocForDataObjOpen()` version and `iget`ing causes stack traces.

**Comment by rskarbez** [comment]
This seems to be due to a segfault occurring at `plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/conversion.cpp:600`

```
if ( strcmp( type, KeyValPair_MS_T ) == 0 ) {
    keyValPair_t *kvp = ( keyValPair_t * ) RES_UNINTER_STRUCT( res0 );                               
    snprintf( res, 1024, "KeyValue[%d]:", kvp->len );
```

It seems that it is possible for kvp to be NULL, and it's not being checked.

I reproduced this by uncommenting `acPostProcForRmColl {msiGetSessionVarValue("all","all"); }` on line 408 of core.re and then deleting a collection.

**Comment by tedgin** [comment]
This also appears to happen in `acCreateUser` and `acTicketPolicy`.
