### ISSUE TITLE
Number of children resources limited by database schema

### ISSUE THREAD

**Issue by nono-gdv** [irods/irods#3052]
Hello,

I would like to use a deferred resource as a front-end for "a lot" of storage resources (think one resource per storage node, and I would like to be able to scale to a few hundred nodes). So I wrote a small script to batch-create resources:

```bash
for i in $(seq 1 1000)
do
  mkdir /mnt/vdb/rscs/unix${i}b
  iadmin mkresc unix${i}b unixfilesystem $(hostname):/mnt/vdb/rscs/unix${i}b
  iadmin mkresc passthru${i}b passthru
  iadmin addchildtoresc passthru${i}b unix${i}b
  iadmin addchildtoresc defer1 passthru${i}b
done
```
After about 70 resources, the last _iadmin_ command starts to fail:
```
ERROR: rcGeneralAdmin failed with error -806000 CAT_SQL_ERR
```
The SQL logs give me a more detailed explanation:
```
[2016-02-17 15:51:37.314 CET] ::1(60166) (irods/ICAT) [0][4/17681] ERROR:  value too long for type character varying(1000)
[2016-02-17 15:51:37.314 CET] ::1(60166) (irods/ICAT) [0][4/17681] STATEMENT:  update R_RESC_MAIN set resc_children='passthru1c{};passthru1b{};passthru2b{};passthru3b{};passthru4b{};passthru5b{};passthru6b{};passthru7b{};passthru8b{};passthru9b{};passthru10b{};passthru11b{};passthru12b{};passthru13b{};passthru14b{};passthru15b{};passthru16b{};passthru17b{};passthru18b{};passthru19b{};passthru20b{};passthru21b{};passthru22b{};passthru23b{};passthru24b{};passthru25b{};passthru26b{};passthru27b{};passthru28b{};passthru29b{};passthru30b{};passthru31b{};passthru32b{};passthru33b{};passthru34b{};passthru35b{};passthru36b{};passthru37b{};passthru38b{};passthru39b{};passthru40b{};passthru41b{};passthru42b{};passthru43b{};passthru44b{};passthru45b{};passthru46b{};passthru47b{};passthru48b{};passthru49b{};passthru50b{};passthru51b{};passthru52b{};passthru53b{};passthru54b{};passthru55b{};passthru56b{};passthru57b{};passthru58b{};passthru59b{};passthru60b{};passthru61b{};passthru62b{};passthru63b{};passthru64b{};passthru65b{};passthru66b{};passthru67b{};passthru68b{};passthru69b{};passthru70b{};passthru71b{};passthru161b{}', modify_ts='01455720697' where resc_id='10588'
```
This is with an iRODS server built last friday from branch 4-1-stable.

**Comment by kript** [comment]
Interested to know how this applies to upgrades as well; in our migration from our 3.3.1 install, we have one zone with 141 resources, 169 if you could the individual demoResc's from each iRES. If this means we can't have more than 70 resources in 4.1.X, then this would stop us migrating this zone!

**Comment by jasoncoposky** [comment]
This limitation will be fixed in 4.2 along with the move away from strings to resource id's.  Either way an answer to this issue is to use more hierarchy.  I would suggest adding either `random` or `deferred` interior nodes to better distribute the children.  I will move this to 4.2, related to #3039.

**Comment by kript** [comment]
Can you make a recommendation for a safe number of resources to have as leaf nodes? For e.g. at present we're looking at ~60 in each replResc node, which is uncomfortably close to the perceived limit to allow for any future expansion..

**Comment by nono-gdv** [comment]
AFAIU the limit is not in the number of children but in the length of the string "child1{};child2{};...;childn{}" which is limited to 1000 characters.

**Comment by kellerb** [comment]
@kript, nono-gdv is correct, the child resource name lengths affect the maximum number of children a resource can have. E.g. 10 character resource names limits you to 76 children, 20 character names limits you to 43 children. (Not quite linear because of the `{};` inserted between child resource names). Wrt. future expansion, even if you originally had all the leaf resources in a single replication resource, you can always update the hierarchy to add a new parent replication resource and add your current maxed-out replication resource to it.

**Comment by kellerb** [comment]
@nono-gdv, the `deferred` resource does not attempt to spread the files around. It's possible that for what you are planning, you would be better off using `roundrobin` instead.

While testing schema changes and hierarchies related to this issue, I made a script ([available here](https://gist.github.com/kellerb/4713acb89679c9c8dc14)) that makes recursive hierarchies with the `passthru -> unixfilesystem` leaves you mentioned. This may be useful to you for creating recursive `deferred` or `roundrobin` hierarchies to house all of your `unixfilesystem` leaves until the fix for the resource child max is pushed to 4.2.

Call the script with:

``` bash
python create_recursive_hierarchy.py \
  --vaults_root_directory /var/lib/irods/recursiveVaults \
  --parent_resource_type roundrobin \
  --number_of_unixfilesystem_resources 10 \
  --max_number_of_children_per_resource 4
```

to create

```
irods$ ilsresc
demoResc
roundrobin_0003:roundrobin
├── roundrobin_0000:roundrobin
│   ├── passthru_0000:passthru
│   │   └── unixfilesystem_0000
│   ├── passthru_0001:passthru
│   │   └── unixfilesystem_0001
│   ├── passthru_0002:passthru
│   │   └── unixfilesystem_0002
│   └── passthru_0003:passthru
│       └── unixfilesystem_0003
├── roundrobin_0001:roundrobin
│   ├── passthru_0004:passthru
│   │   └── unixfilesystem_0004
│   ├── passthru_0005:passthru
│   │   └── unixfilesystem_0005
│   ├── passthru_0006:passthru
│   │   └── unixfilesystem_0006
│   └── passthru_0007:passthru
│       └── unixfilesystem_0007
└── roundrobin_0002:roundrobin
    ├── passthru_0008:passthru
    │   └── unixfilesystem_0008
    └── passthru_0009:passthru
        └── unixfilesystem_0009
```

Also, note that a bug in the `deferred` resource was found that will prevent a recursive hierarchy of `deferred` resources from working. The fix for that has not yet been pushed to 4-1-stable, but will be included in 4.1.8.

**Comment by nono-gdv** [comment]
Thanks for your time. I really want deferred resources though, or at least I think I need them; my idea was to fill a storage node, then set its write weight to 0 (hence the passthru resource) and go on to fill the next node.

Any idea when the fix will be pushed to 4-1-stable?

**Comment by kript** [comment]
@nono-gdv You might find that the high water mark is a better fit for your need there  (#2981) ; its what we're planning to use. https://docs.irods.org/master/manual/architecture/#unixfilesystem

**Comment by trel** [comment]
@nono-gdv The fix for this issue, #3052 will be in 4.2.

The fix for the nested deferred node #3056 has been included in 4-1-stable (https://github.com/irods/irods/commit/a887b62ffc8474563ef836b8c9e91500e599e00b) and will ship with 4.1.8 later today.

Also, @kript is correct, you can protect from standard disk-full events with the new high water mark #2981.

**Comment by andyjp94** [comment]
I have done a few quick calculations using the information you have given us and our current infrastructure  which are:
10 characters per resource gives 76 child leaves
20 characters per resource gives 43 child leaves

Whilst I realise you said this isn't entirely linear I thought i'd still test as if it were to see how our current system would handle it.

The provided values gives an equation of child leaves = -3.3*(characters) + 109. I have provided a table below showing our current system and how it would translate into resource composition with the constraints enforced by this issue:

|          | resources | characters per child resource | child per node | 
| ---     | ---              | ---                                            | ---                    |
| local | 86              |32                                            | 3.4                   |
|remote| 80            |18                                            |49.6                   |

These figures do not include possible expansions to our iRODS service that we will need before we migrate to 4.2. So as you can see this is very much an issue for us. Adding more and more levels to the resource tree seems an untenable solution for a problem on this scale. Could you please suggest any alternative solutions or work arounds as we want to upgrade to 4.1.x rather than wait for 4.2?

**Comment by kellerb** [comment]
@andyjp94, sorry, linear was wrong, I should have said "not quite inversely proportional".

If `c` is the average number of characters per child resource name, then the maximum number of children for a resource is given by `floor(1001/(c+3))`.

Here is an updated table with your `characters per child resource` choices and a fix for my selection of 10 (should be 77 instead of 76)

| characters per child resource | max children per resource |
| ---                                            | ---
| 10                                            | 77
| 18                                            | 49
| 20                                            | 43
| 32                                            | 28

An updated version of your table is then:

|          | resources | characters per child resource | child per comp res | Number of comp res required |
| ---         | :---:          | :---:                                       | :---:                       | :---: 
| local     | 86            | 32                                         | 28                         | 4 |
| remote | 80            | 18                                         | 49                         | 2 |
