### ISSUE TITLE
Improve high_water_mark documentation

### ISSUE THREAD

**Issue by nono-gdv** [irods/irods#3066]
Trying to use the new high_water_mark context variable with iRODS 4.1.8:

```
irods@irods-0003:~$ mkdir /srv/irods/data/foobar
irods@irods-0003:~$ iadmin mkresc foobar unixfilesystem $(hostname):/srv/irods/data/foobar
Creating resource:
Name:           "foobar"
Type:           "unixfilesystem"
Host:           "irods-0003"
Path:           "/srv/irods/data/foobar"
Context:        ""
irods@irods-0003:~$ iadmin modresc foobar context high_water_mark=10000000
irods@irods-0003:~$ ls -l irods-icommands-4.1.7-ubuntu14-x86_64.deb 
-rw-r----- 1 irods irods 7447732 Feb 11 11:02 irods-icommands-4.1.7-ubuntu14-x86_64.deb
irods@irods-0003:~$ iput -R foobar irods-icommands-4.1.7-ubuntu14-x86_64.deb
ERROR: putUtil: put error for /augy/home/rods/irods-icommands-4.1.7-ubuntu14-x86_64.deb, status = -1803000 status = -1803000 HIERARCHY_ERROR
```

Here is the relevant excerpt from the iRODS logs:
```
Feb 23 17:04:02 pid:31225 NOTICE: Agent process 502 started for puser=rods and cuser=rods from 172.16.36.213
Feb 23 17:04:02 pid:502 ERROR: [-]      iRODS/server/api/src/rsDataObjPut.cpp:89:rsDataObjPut :  status [HIERARCHY_ERROR]  errno [] -- message [rsDataObjPut :: failed in irods::irods::resolve_resource_hierarchy for [/augy/home/rods/irods-icommands-4.1.7-ubuntu14-x86_64.deb]]
        [-]     iRODS/server/core/src/irods_resource_redirect.cpp:289:resolve_hier_for_create :  status [HIERARCHY_ERROR]  errno [] -- message []
                [-]     iRODS/server/core/src/irods_resource_redirect.cpp:72:request_vote_for_file_object :  status [HIERARCHY_ERROR]  errno [] -- message [failed in call to redirect host [irods-0003]  hier []]
                        [+]     libunixfilesystem.cpp:1529:unix_file_redirect_plugin :  status [Unknown iRODS error]  errno [] -- message []

Feb 23 17:04:02 pid:502 NOTICE: readAndProcClientMsg: received disconnect msg from client
Feb 23 17:04:02 pid:502 NOTICE: Agent exiting with status = 0
Feb 23 17:04:02 pid:31225 NOTICE: Agent process 502 exited with status 0
```

**Comment by trel** [comment]
Can you confirm this works when you are using a fully qualified domain name, rather than `irods-0003`?

**Comment by nono-gdv** [comment]
I get the same error using the FQDN.

**Comment by kellerb** [comment]
Can you show the output of `ping $(hostname)` please?

**Comment by nono-gdv** [comment]
```
irods@irods-0003:~$ ping -c2 $(hostname)
PING irods-0003.frymghq (172.16.36.213) 56(84) bytes of data.
64 bytes from irods-0003.frymghq (172.16.36.213): icmp_seq=1 ttl=64 time=0.056 ms
64 bytes from irods-0003.frymghq (172.16.36.213): icmp_seq=2 ttl=64 time=0.018 ms

--- irods-0003.frymghq ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.018/0.037/0.056/0.019 ms
```

**Comment by kellerb** [comment]
How about `ilsresc -l`.

**Comment by nono-gdv** [comment]
```
irods@irods-0003:~$ ilsresc -l foobar
resource name: foobar
id: 10764
zone: augy
type: unixfilesystem
class: cache
location: irods-0003
vault: /srv/irods/data/foobar
free space: 
free space time: : Never
status: 
info: 
comment: 
create time: 01456243384: 2016-02-23.17:03:04
modify time: 01456243421: 2016-02-23.17:03:41
children: 
context: high_water_mark=10000000
parent: 
object count: 0
```

**Comment by kellerb** [comment]
Can you do an unqualified `ilsresc -l` so we can see all the other resources?

**Comment by trel** [comment]
Can you put a file into that resource without the high_water_mark set?

**Comment by kellerb** [comment]
We've replicated the issue, thank you.

**Comment by nono-gdv** [comment]
@kellerb Here you are, the list is a bit long as I use this machine for testing resource composition.

[irods-0003-ilsresc.txt](https://github.com/irods/irods/files/142994/irods-0003-ilsresc.txt)

@trel, yes, it works without issue.

**Comment by kellerb** [comment]
### Short answer

iRODS is correctly failing to create a new data object on the `unixfilesystem` resource whose `high_water_mark` has been exceeded. iRODS is reporting this failing as a `HIERARCHY_ERROR`.

### Long answer

I believe this is an instance of iRODS behaving properly but with poor documentation / terse error messages.

The context string `high_water_mark=10000000` for a `unixfilesystem` resource means that when (the bytes used of the storage device backing the resource) plus (the size of the new file) exceeds the `high_water_mark`, the resource will:

1. Vote `0` during hierarchy resolution for the creation of a new data object
2. Fail during the creation of a new data object

In your case, the `high_water_mark` is set to 10,000,000 bytes (i.e. 10 MB, not 10 MiB). When handling the `iput`, iRODS asks the target resource tree (which in this case is just the `foobar` resource) to resolve the specific resource hierarchy to be used throughout the operation. `foobar` returns a vote of 0 (because the `high_water_mark` was exceeded) along with the resolved hierarchy (which in this case is just `foobar`). iRODS will not use a hierarchy that has a 0 vote, and reports the 0 vote as a `HIERARCHY_ERROR`.

We have made an issue to improve the error messaging #3067.

Please let us know if any of this requires more explanation or if you are seeing other behavior.

**Comment by nono-gdv** [comment]
OK, I understand. This won't be an issue in production with one resource per disk; it is just a hindrance for testing where I tend to create several resources on a single disk.

Thanks for explaining!

**Comment by kellerb** [comment]
Closing as #3067 covers the documentation fix.
