### ISSUE TITLE
irm, irmtrash don't delete physical folders

### ISSUE THREAD

**Issue by mpasserini** [irods/irods#3124]
- [x] master
- [x] 4-2-stable
----

Hi,

Is it normal that `irm` and `irmtrash` delete files but don't delete physical folders, neither from the vault nor from the trash? This has an impact on the number of inodes of the underlying filesystem...

Example:

```
-bash-4.1$ ils
/myzone/home/rods:
-bash-4.1$ imkdir testdir
-bash-4.1$ ils
/myzone/home/rods:
  C- /myzone/home/rods/testdir
-bash-4.1$ iput test
tests/    test.txt  
-bash-4.1$ iput test
tests/    test.txt  
-bash-4.1$ iput test.txt /myzone/home/rods/testdir/
-bash-4.1$ ils
/myzone/home/rods:
  C- /myzone/home/rods/testdir
-bash-4.1$ ils /myzone/home/rods/testdir/
/myzone/home/rods/testdir:
  test.txt
-bash-4.1$ ls /irodsvault/Vault/home/rods/
testdir
-bash-4.1$ ls /irodsvault/Vault/trash/home/rods/
-bash-4.1$ irm -r /myzone/home/rods/testdir/
-bash-4.1$ ls /irodsvault/Vault/home/rods/
testdir
-bash-4.1$ ls /irodsvault/Vault/trash/home/rods/
testdir
-bash-4.1$ ils
/myzone/home/rods:
-bash-4.1$ ls /irodsvault/Vault/trash/home/rods/testdir/
test.txt
-bash-4.1$ irmtrash -M -v
-bash-4.1$ ls /irodsvault/Vault/trash/home/rods/testdir/
-bash-4.1$ ls /irodsvault/Vault/trash/home/rods/
testdir
-bash-4.1$ ls /irodsvault/Vault/home/rods/
testdir
-bash-4.1$ imkdir testdir
-bash-4.1$ ils
/myzone/home/rods:
  C- /myzone/home/rods/testdir
-bash-4.1$ ls /irodsvault/Vault/home/rods/
testdir
-bash-4.1$ 
```

**Comment by mcast** [comment]
On Wed, Mar 30, 2016 at 01:13:30AM -0700, mpasserini wrote:

> Is it normal that irm and irmtrash delete files but don't delete
> physical folders, neither from the vault nor from the trash?

I have also observed this (with 'unix file system' vaults).

My first thought was that we might need to (write a tool to)
periodically scan the vaults and do some `rmdir`s.

My second thought was that iRODS should do it, because the vault is an
internal structure.  I only know that it happens because I opened the
"black box".

Then I thought iRODS doesn't need to bother, because the vault is an
internal structure and the empties aren't going to cause real
problems.


> This has an impact on the number of inodes of the underlying
> filesystem...

The empties will also use some space, though I doubt any normal
workpattern is going use a significant chunk of any modern storage.

My concern was that trees of empties would slow down directory
traversal of a vault.  Which I should never need to do, but I will be
opening that black box and so I will need to make some checks on the
contents.  Then maybe I will need take responsibility for cleaning up
empties - back to first thought!

So I'm still not convinced it's worth asking for iRODS to clean up...

-- 
Matthew


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by kellerb** [comment]
It is normal in the sense that, from iRODS' point of view, collections exist only in the database. From that reference frame, it wouldn't make sense to reach out to a storage resource for a collection deletion.

Continuing with that reference frame, the Vault directories are an implementation detail of the `unixfilesystem` plugin (though a wide-reaching implementation detail, given how important that plugin is). It may make sense to add some Vault clean-up code, though I'm not immediately sure what iRODS action(s) should trigger it. `irmtrash` could be a candidate.

**Comment by trel** [comment]
Marking this as a documentation exercise for the administrator.
