### ISSUE TITLE
iscan: bug or misunderstanding?

### ISSUE THREAD

**Issue by AndreyNevolin** [irods/irods#3176]
Hi,

please consider the picture below.

![screenshot-2016- -20-727-pm](https://cloud.githubusercontent.com/assets/7734325/15433195/56f1d1b8-1ec2-11e6-93ef-d4565b167742.png)

My expectation - according to iscan's description - is that zero should be returned (since 'run.pl' is registered in iCAT). Is this expectation wrong? (I might incorrectly understand the help message).

I'm using iRODS 4.1.8

**Comment by trel** [comment]
I think it's a misunderstanding.

If you were to run `ils -L`, I expect you'll see that the physical path that is registered for `run.pl` is the full path in the iRODS Vault, not the original location of the file that you `iput` into iRODS.

An `iput` is actually a copy (perhaps across a network) into the vault, and then a registration.

So, the path `/var/lib/irods/irods_test/run.pl` is correctly reported as not being registered.  The copy of it in the Vault is the file that is registered.

**Comment by AndreyNevolin** [comment]
Oh, seems I got it.

![1](https://cloud.githubusercontent.com/assets/7734325/15433995/f15c0fcc-1ec5-11e6-80a5-52e8dfacfedb.png)

So, 'local' word above means not a 'local copy of a file/directory put into iRODS' but 'copy on iRODS vault'. Right?

Does it only work with 'linuxfilesystem' resource type or with any resource type?

What is an intended use model? Search for orphan objects?

**Comment by trel** [comment]
The word 'local' in that sense means a physical path on disk rather than a logical path in iRODS.

It will work on `unixfilesystem`, definitely.  Object stores may not behave as well out of the box, I'm not sure we have any testing around that.  If you have new information (or new tests!) regarding an object store, then please share and we'll get things squared up.

Yes, identifying orphan or missing files is the intended use case.  Alongside `ifsck`, an iRODS administrator can get a feel for the integrity and negative space around registered files.

**Comment by AndreyNevolin** [comment]
Thanks Terrell for the explanation.
Currently I don't have any new tests. But if I have them one day, I'll share them for sure.
