### ISSUE TITLE
default_file_mode directive can not be limited to a single resource server

### ISSUE THREAD

**Issue by mheiges** [irods/irods#3231]
Changing `default_dir_mode` in server_config.json on a non-icat resource server is honored and the change is limited to resources managed by that server.

However, changing `default_file_mode` on the non-icat resource server is not used. I have to change default_file_mode on the icat server, but then all resource servers use altered file modes.

Is this the intended behavior?

(related to  #2674 : do "these directives act locally on resource servers and apply only to the vaults of the resources managed by the server itself"? )

**Comment by trel** [comment]
The `default_dir_mode` is only consulted when creating directories, which is much later in the connection life cycle, and only resolved on the server that is actually doing the work.  So it works as you had expected, per server.

The `default_file_mode` is consulted during the initial connection, and resolved before any redirect occurs - so it does not have the effect you had expected.

As I understand it, if you are connected to iRODS server A, and then doing file operations on a resource on a different resource server B, the initial server A is the one where the `default_file_mode` setting will be picked up and honored.

> I have to change default_file_mode on the icat server, but then all resource servers use altered file modes

If this is true, we may have a bug.   Can you re-confirm that this is the case?  Do all your servers share the same iRODS version?  What version is that?

If there is no bug (above), I would say it is 'understood' behavior, rather than intended, at this point.  We plan to eventually change how the POSIX-style information is resolved and passed around, but at this time, yes, this is the behavior we have.

**Comment by mheiges** [comment]
I'm using 4.1.8 everywhere.

> the initial server A is the one where the default_file_mode setting will be picked up and honored.

OK. I think I understand now. The setting used depends on the server to which I iinit. It had not occurred to me that I could iinit to any server. If I iinit to server B then that server's config is used.

I'll close this as not a bug. Thanks for the clarification.
