### ISSUE TITLE
4.1.9 - putting a client into debug logging also puts the ICAT server into debug logging

### ISSUE THREAD

**Issue by keithj** [irods/irods#3290]
To reproduce, edit a regular users's `irods_environment.json` to enable a high level of logging:

`"irods_log_level" = 10`

Run a client as that user e.g. `ils`

A lot of log messages are written to the user's STDERR, as expected. However about twice as many
lines are written to the server's rodsLog, as this apparently puts the server side in debug mode too.

The server writes about 1300 lines of debug log into the rodsLog for each `ils` client connection. With a single user running `ils` in a loop, I'm seeing 2G of logs generated per hour, sufficient to fill its disk quite quickly.

**Comment by trel** [comment]
I have just added a higher log level to a connecting client's `irods_environment.json` file on 4.1.9 and there was no additional logging on the server side - just the default four lines of output for an `ils`.

Did you add the higher `irods_log_level` to the `irods_environment.json` in the service account that operates the server itself?

**Comment by keithj** [comment]
Yes, the user isn't `irods`, but it is the user who set up the run-in-place install where this is happening. That's good news if it accounts for the behaviour. 

What effect does setting the log level in `server_config.json` have? I have it set there too (and validated successfully against the schema). Does it have no effect? i.e. it's a user error?

**Comment by trel** [comment]
I don't think there are any logging-related knobs in `server_config.json`:
  https://docs.irods.org/4.1.9/manual/configuration/#etcirodsserver_configjson

Having extra key/value pairs in a `.json` file would only make a schema instantiation invalid if `"additionalProperties": false` is set in the schema - and we did not use that in 4.1.x, since this was the first sequence to use the JSON schemas.
  https://github.com/irods/irods_schema_configuration/blob/v2/schemas/server_config.json

**Comment by keithj** [comment]
Thanks for your help. It's evidently PEBKAC on my part. I hadn't considered that if I start a run-in-place server without switching user while doing so, it picks up my own `irods_environment.json`, which I'm using for client tests. I'll close this - sorry for the noise.
