### ISSUE TITLE
Log file directory unwritable

### ISSUE THREAD

**Issue by fconagy** [irods/irods#3341]
When I did the upgrade from 4.1.8 to 4.1.9 there was an error message during the startup of the iRODS servers that they are unable to write their log files. Chowning the log directory from `root` to `irods:irods` seemed to solve the problem. The directory is packaged as root:root so then the iRODS server startup cannot write it.

Janos

**Comment by tempoz** [comment]
The log directory, like all directories and all files, must be packaged as root because the irods user is not the same user id on all machines, nor even necessarily the same username. The postinstall script is meant to chown the directories to the correct owner on upgrade. We are not experiencing this issue in our testing, and further inspection reveals that all appears to be well in the postinstall script. If you have more information on how to reproduce this issue, we would appreciate you providing it.

**Comment by trel** [comment]
@fconagy please let us know if you saw this effect again.  if not, we'll close as it appears to be working as expected for us.

**Comment by fconagy** [comment]
Hi,

thank you very much for looking into this.
As it is experienced only with a fresh new
install we don't have a chance frequently to
test this. We've seen it every time since 4.0.3.

Janos

**Comment by trel** [comment]
Thanks for the follow up.  Please open a new issue if you see this again.
