### ISSUE TITLE
Document upgrade path on ubuntu for 4.2

### ISSUE THREAD

**Issue by tempoz** [irods/irods#3384]
The correct order of commands for a 4.2 server upgrade is:
1. stop the old server `./irodsctl stop`
2. install the new server: `sudo dpkg --auto-deconfigure -i <package_file.deb>`
3. remove the old server `sudo dpkg -P <irods-icat or irods-resource>`
4. start the new server `./irodsctl start`
This prevents weirdness with the old server continuing to run when files important to it are moved and most importantly prevents the old server's uninstall scripts from destroying the VERSION.json file and the associated version information.

**Comment by tempoz** [comment]
We will also need to look into any parallel path for packages from the repos using apt.

**Comment by trel** [comment]
Won't be using dpkg with repository.

**Comment by trel** [comment]
With APT:
- If the `VERSION.json` file is manually moved/copied to `VERSION.json.previous` before the upgrade, the history of the deployment will be preserved in the resulting upgraded `VERSION.json` file.
- Otherwise, the 4.2 `irods-server` package will populate a dummy `VERSION.json.previous` file so the upgrade can go smoothly, but the real history will be lost.
