### ISSUE TITLE
Create/delete file with & char allows create, causes -816000 error on delete

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#3398]
See https://github.com/DICE-UNC/jargon/issues/170

That unit test creates a collection with & char successfully, delete in Jargon and icommands causes -816000 error

```
mconway@mikesubuntu:~/.irods$ irm -r "testDeleteACollectionWithAmpInTheNameBug170 && hail hail rock & roll  &"
ERROR: rmUtil: rm error for /zone1/home/test1/jargon-scratch/IRODSFileTest/testDeleteACollectionWithAmpInTheNameBug170 && hail hail rock & roll  &, status = -816000 status = -816000 CAT_INVALID_ARGUMENT


```

**Comment by michael-conway** [comment]
This is still an issue testing with iRODS 4.2.4...will continue to park the Jargon issue

**Comment by korydraughn** [comment]
I tried to reproduce this issue using icommands and jargon against 4.2.4 and master, but haven't been successful.  In my tests, iRODS is not experiencing any problems deleting collections or data objects with '&' characters in their name.

Can you provide the packing instructions produced by Jargon for this test so that I can compare.

**Comment by alanking** [comment]
Reproduced:
```
$ imkdir "/tempZone/home/rods/testDeleteACollectionWithAmpInTheNameBug170 && hail hail rock & roll  &"
$ irm -r "testDeleteACollectionWithAmpInTheNameBug170 && hail hail rock & roll  &"
remote addresses: 172.17.0.3 ERROR: rmUtil: rm error for /tempZone/home/rods/testDeleteACollectionWithAmpInTheNameBug170 && hail hail rock & roll  &, status = -816000 status = -816000 CAT_INVALID_ARGUMENT
$ echo $?
3
```

**Comment by korydraughn** [comment]
- [x] master
- [x] 4-2-stable
