### ISSUE TITLE
init_from_catalog should not error out on null genQueryOut

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods#3404]
- [x] If the results of the genQuery are null and no error was returned, set continueInx to 0 to exit the loop.

**Comment by alanking** [comment]
I think this is done?

https://github.com/irods/irods/blob/d232c7f3e0154cacc3a115aa50e366a98617b126/server/core/src/irods_resource_manager.cpp#L310-L316

On line 315, `continueInx` is set to 0 when the genQuery results are null.

However, this been the case since before this issue was created, so I may be misunderstanding its purpose...

**Comment by korydraughn** [comment]
We could replace the use of the GenQuery C API with the query iterator here.

**Comment by trel** [comment]
oh yes, let's remove the ability to hold it wrong.
