### ISSUE TITLE
Rule engine callback: unsupported effect handler type

### ISSUE THREAD

**Issue by jacquayj** [irods/irods#3424]
I'm experimenting with compiling my own version of the default C++ rule engine, and have encountered an interesting issue:

```
ERROR: rule engine callback: unsupported effect handler type. encountered:
PN5irods27rule_engine_context_managerINSt3__15tupleIJEEEP12RuleExecInfoLNS_27rule_execution_manager_packE0EEE
expected:
PN5irods27rule_engine_context_managerINSt3__15tupleIJEEEP12RuleExecInfoLNS_27rule_execution_manager_packE0EEE
PN5irods27rule_engine_context_managerINSt3__15tupleIJEEEP12RuleExecInfoLNS_27rule_execution_manager_packE1EEE
````

Which seems to be [coming from the callback::operator() function in irods_re_plugin.hpp#L684](https://github.com/irods/irods/blob/4.2.0/server/re/include/irods_re_plugin.hpp#L684). The type names seem to match from the error, however the if statement is going directly to the else block causing the error.

According to [cppreference.com](http://en.cppreference.com/w/cpp/language/typeid), using `std::type_info.hash_code()` in the comparison is preferred since "there is no guarantee that the same std::type_info instance will be referred to by all evaluations of the typeid expression on the same type". But take this with a grain of salt, since I'm not a C++ expert.

I should note that my original experiment compiled using `cmake && make package` works fine and doesn't encounter this error, but I'm trying to use an alternative compile process which results in what you see above. That said, everything should be mostly the same AFAIK:

```
CXX: /opt/irods-externals/clang3.8-0/bin/clang++
CXXFLAGS: -DBOOST_SYSTEM_NO_DEPRECATED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_LARGE_FILES -Dirods_rule_engine_plugin_go_EXPORTS -Dlinux_platform -fPIC -O3 -DNDEBUG -stdlib=libc++ -Wl,-z,defs -shared -nostdinc++ -std=c++14 -std=gnu++14 -I/opt/irods-externals/clang3.8-0/include/c++/v1 -I/usr/include/irods -I/opt/irods-externals/boost1.60.0-0/include -I/opt/irods-externals/jansson2.7-0/include
LDFLAGS: -L/opt/irods-externals/boost1.60.0-0/lib -L/opt/irods-externals/clang3.8-0/lib -L/opt/irods-externals/clang-runtime3.8-0/lib -lboost_system -lc++ -lc++abi -lirods_server -lirods_common -ldl -lm -lpthread
```

Maybe I'm missing a compiler/linker flag? Any help is greatly appreciated.

-- John

**Comment by trel** [comment]
Very interesting.

Can you tweak the source with your proposed fix (`std::type_info.hash_code()`) and let us know if that behaves better with your toolchain?

**Comment by kellerb** [comment]
The [cppreference.com](http://en.cppreference.com/w/cpp/language/typeid) link is saying that the addresses of (obtained via `operator&`) two `std::type_info`s are not guaranteed to be the same even though the `std::type_info`s are for the same type, not that `operator==` could return false for two `std::type_info`s for the same type.

Additionally, `std::type_info::hash_code` cannot be used in this instance because (like hashes in general) it is guaranteed to return equal hashes for equal types, but it is not guaranteed to return unequal hashes for unequal types.

I believe that the `std::type_info`s comparing unequal but the `std::type_info::name`s comparing equal suggests that there is a problem in the compilation or linking. I'm not sure yet what could be going wrong.

**Comment by jacquayj** [comment]
Thanks for looking into this @trel and @kellerb! I attempted to use `std::type_info.hash_code()` with my custom toolchain, but that didn't fix the issue. I find this strange, since @kellerb said `hash_code()` is guaranteed to return equal hashes for equal types, but I guess that result makes sense considering the original code acts the same way. There must be some issue with the compiling/linking in my toolchain... I wish I could be less vague about what I'm using, but I need to get permission first. 

In the meantime, until I get that sorted out, I came up with a simple fix that uses `strcmp()`:

```c++
if(strcmp(callback_hdlr_.type().name(), typeid(rule_engine_context_manager<default_re_ctx, default_ms_ctx, AUDIT_RULE> *).name()) == 0) {
    auto cb = boost::any_cast<rule_engine_context_manager<default_re_ctx, default_ms_ctx, AUDIT_RULE> *>(callback_hdlr_);
    return cb->exec_rule(_rn, std::forward<As> (_ps)...);
} else if (strcmp(callback_hdlr_.type().name(), typeid(rule_engine_context_manager<default_re_ctx, default_ms_ctx, DONT_AUDIT_RULE> *).name()) == 0) {
    auto cb = boost::any_cast<rule_engine_context_manager<default_re_ctx, default_ms_ctx, DONT_AUDIT_RULE> *>(callback_hdlr_);
    return cb->exec_rule(_rn, std::forward<As> (_ps)...);
} else {
    rodsLog(
        LOG_ERROR,
        "rule engine callback: unsupported effect handler type. encountered:\n'%s'\nexpected:\n'%s'\n'%s'\n",
        callback_hdlr_.type().name(),
        typeid(rule_engine_context_manager<default_re_ctx, default_ms_ctx, AUDIT_RULE> *).name(),
        typeid(rule_engine_context_manager<default_re_ctx, default_ms_ctx, DONT_AUDIT_RULE> *).name()
    );
    return ERROR(RE_TYPE_ERROR, "unsupported effect handler type");
}
```

Thanks again for looking into this, I should have known it was an issue on my end :)

**Comment by kellerb** [comment]
Yes, the subtext of "`hash_code()` is guaranteed to return equal hashes for equal types" is "assuming all the threshing gears of C++ are properly aligned".

When there are problems with types crossing object boundaries (in this case we are having trouble with the type `irods::rule_engine_context_manager<std::__1::tuple<>, RuleExecInfo*, (irods::rule_execution_manager_pack)0>*` (aka. `irods::rule_engine_context_manager<default_re_ctx, RuleExecInfo*, AUDIT_RULE>*`) working between a modified `libirods_rule_engine_plugin-cpp_default_policy.so` and `libirods_server.so`) sometimes the cause is a failure of the dynamic linker to unify weak symbols or weak objects that are present in both of the objects.

E.g. if you run `nm -CD libirods_server.so` you will see an entry like `00000000021fe3c0 V typeinfo for irods::rule_engine_context_manager<std::__1::tuple<>, RuleExecInfo*, (irods::rule_execution_manager_pack)0>`. Similarly, if you run `nm -CD libirods_rule_engine_plugin-cpp_default_policy.so` you will see the same entry (but probably with a different address). The `V` in the entry means that the symbol corresponds to a weak object. When the `irodsServer` uses `dlopen()` to load the rule engine plugin, the dynamic linker tries to match all weak objects in the rule engine plugin with already existing objects in the `irodsServer` address space, which includes all the objects exported by libraries the `irodsServer` links against, which includes `libirods_server.so`. This means that the rule engine plugin code ends up using the type info from `libirods_server.so`, so when objects of that type are passed back and forth, `typeid()` comparisons work.

This procedure can break (and therefore cause the program to be in violation of the One Definition Rule) if:
 * the symbol in the rule engine plugin is not a weak symbol (`V`) (so unification is not attempted).
 * the symbols from `libirods_server.so` are not available for unification when the rule engine plugin is `dlopen()`ed. This can happen e.g. if certain flags are used with `dlopen()`.

We had a similar problem recently when we were writing an iRODS plugin for another program. The other program was `dlopen()`ing the iRODS plugin with `RTLD_LOCAL`, which prevented the iRODS plugin (and all the libraries it linked against, e.g. `libirods_plugin_dependencies.so`) from injecting its objects into the global table, so when the iRODS plugin then loaded its network plugin (`libtcp_client.so`), the symbols from `libirods_plugin_dependencies.so` were not available for unification with the symbols from `libtcp_client.so` causing a dynamic cast to fail (since dynamic cast depends on checking type equality).

**Comment by jacquayj** [comment]
@kellerb wow, thanks for this in-depth explanation! I've run the `nm` commands you suggested, and this is what was produced:

```bash
[vagrant@icat MyRuleEngine]$ nm -CD libirods_rule_engine_plugin-custom.so | grep -F "V typeinfo for irods::rule_engine_context_manager<std::__1::tuple<>, RuleExecInfo*, (irods::rule_execution_manager_pack)0>"
00000000003ba560 V typeinfo for irods::rule_engine_context_manager<std::__1::tuple<>, RuleExecInfo*, (irods::rule_execution_manager_pack)0>
00000000003ba580 V typeinfo for irods::rule_engine_context_manager<std::__1::tuple<>, RuleExecInfo*, (irods::rule_execution_manager_pack)0>*
[vagrant@icat MyRuleEngine]$ nm -CD /usr/lib/libirods_server.so.4.2.0 | grep -F "V typeinfo for irods::rule_engine_context_manager<std::__1::tuple<>, RuleExecInfo*, (irods::rule_execution_manager_pack)0>"
00000000011b04c0 V typeinfo for irods::rule_engine_context_manager<std::__1::tuple<>, RuleExecInfo*, (irods::rule_execution_manager_pack)0>
00000000011b0d40 V typeinfo for irods::rule_engine_context_manager<std::__1::tuple<>, RuleExecInfo*, (irods::rule_execution_manager_pack)0>*

```

It seems the types are being marked as weak (V) but aren't being unified by my linker. I'm using the default 4.2.0 icat binary (from RPM package) to load the `.so`, so it should be invoking `dlopen()` correctly I'm assuming. This is a step in the right direction for debugging. Thanks again for all of this valuable information.

**Comment by kellerb** [comment]
Hopefully it is helpful. Please keep us posted on any discoveries you make. I have been trying to learn more about these things (the passing of objects between binaries) recently, as it is an important part of larger C++ projects that doesn't appear to be documented very well and depends on the implementation details of different Linux components. My previous post is based on the scraped-together wisdom of some forum and blog posts, so it should be at least partially correct :). If you find a good source of information, please let me know.

You mentioned that the rule engine plugin was working before you switched build procedures. It may be useful to compare the output of the following commands when run on the working and non-working plugin:  
* `nm -CD` (or possibly `readelf -Ws`)
* `readelf -d`
