### ISSUE TITLE
`irm -n` of last copy: surprising success

### ISSUE THREAD

**Issue by mcast** [irods/irods#3451]
- [x] master
- [x] 4-2-stable
----

Before issuing a large number of `irm -n` commands intended to reduce replica counts, I wanted to make sure that this wouldn't inadvertantly remove any last copies.  Turns out it can:

```
$ i-dev ils -L test-fail.txt 
  mca               0 data         3245 2017-01-20.13:11 & test-fail.txt
    c22136b0f0ecae115ce3d68a871e0e3b    generic    /data/home/mca/test-fail.txt
  mca               1 wtsiuser         3245 2017-01-20.13:12 & test-fail.txt
    c22136b0f0ecae115ce3d68a871e0e3b    generic    /wtsiuser/home/mca/test-fail.txt
$ i-dev irm -n1 test-fail.txt 
$ i-dev irm -n0 test-fail.txt 
$ i-dev ils -L test-fail.txt 
ERROR: lsUtil: srcPath /Sanger1-dev/home/mca/test-fail.txt does not exist or user lacks access permission
```

My suggestion is that `irm -n` should be changed to never remove the last copy, and that operation should require a plain `irm`.  I realise that this is a spec change and anyway may not suit everyone, but it does seem like a conservative choice worth considering.

(`i-dev` is a local wrapper which points me at our dev zone, currently 4.1.9)

If we're keeping current behaviour, would it be worth updating `irm -h` from

```
 -n  replNum  - the replica to remove; if not specified remove all replicas.
     This option is applicable only to the removal of data object and
     will be ignored for collection removal.
```

to add something like "This option can be used to remove the last copy of a file, equivalent to plain `irm file`" ?

**Comment by trel** [comment]
That is surprising.

I am inclined to mark the `-n` option itself as deprecated in 4.3 and remove the option in a later release.

Getting rid of a replica should be the business of `itrim`, not `irm`.

**Comment by mcast** [comment]
On Fri, Jan 20, 2017 at 09:49:10AM -0800, Terrell Russell wrote:
> That is surprising.

Glad it's not just me!  8-)

> I am inclined to mark the `-n` option itself as deprecated in 4.3
> and remove the option in a later release.
> 
> Getting rid of a replica should be the business of `itrim`, not
> `irm`.

If it could be accompanied by some more explicit or micro-managey
options for `itrim` in 4.2, that would suit me.  It looked a bit too
clever when I examined it (in v3.3.1).

I pushed the logic for how many replicas should be where into my
application code rather than write Rules Engine rules for it.  Now
remembering what 'iRODS' stands for this may seem a little perverse.
That might be a good topic for discussion another time if you like.

It was that code which generated the pile of `irm -n1`s.  It is fine,
I don't have a milestone requirement for this.

-- 
Matthew


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by trel** [comment]
Okay, so this is interesting.

Conceptually, `irm` is intended to be about the dataObject itself (or, if using recursively, a Collection).  `irepl` and `itrim` are intended to be targeted at operating on replicas of dataObjects.

Can you say a bit more about what might be needed for `itrim` to make you more comfortable using it to manage replicas explicitly?  The replica management code has been tightened up tremendously since 3.x.  We have tests around everything we've found and fixed since then.

**Comment by mcast** [comment]
On Sun, Jan 22, 2017 at 01:34:53PM -0800, Terrell Russell wrote:

> Conceptually, `irm` is intended to be about the dataObject itself
> (or, if using recursively, a Collection).  `irepl` and `itrim` are
> intended to be targeted at operating on replicas of dataObjects.

That makes sense.


> Can you say a bit more about what might be needed for `itrim` to
> make you more comfortable using it to manage replicas explicitly?

Possibly it's just documentation.  What I want is a command to reduce
the replica count from two to one, keeping the local one i.e. deleting
the offsite one.

The code ordering (de)replication knows which resources are local, but
treats them as leaf resources ignoring the structure above.

Using v3 resource groups, new files are written to the local group
containing resources which still have free space.


> The replica management code has been tightened up tremendously since
> 3.x.  We have tests around everything we've found and fixed since
> then.

Thank you.

Planning how these resources fit into the v4 structure will be an
early step in upgrading, but is not yet scheduled here...


Is this enough to let you continue with that `-n` deprecation plan?

-- 
Matthew


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by trel** [comment]
Given a composite resource tree:
```
$ ilsresc
demoResc
repl:replication
├── u1
└── u2
```
And a dataObject in `demoResc` and in `repl`:
```
$ ils -L foo
  rods              0 demoResc        32217 2017-01-24.08:56 & foo
        generic    /var/lib/irods/iRODS/Vault/home/rods/foo
  rods              1 repl;u2        32217 2017-01-24.08:56 & foo
        generic    /tmp/u2Vault/home/rods/foo
  rods              2 repl;u1        32217 2017-01-24.08:56 & foo
        generic    /tmp/u1Vault/home/rods/foo
```

You cannot trim a replica within the tree by naming the resource location:
```
$ itrim -S u2 foo
ERROR: trimUtil: trim error for /tempZone/home/rods/foo, status = -1816000 status = -1816000 DIRECT_CHILD_ACCESS
```

But you can trim a replica within the tree if you know the replica number:
```
$ itrim -n1 foo
$ ils -L foo
  rods              0 demoResc        32217 2017-01-24.08:56 & foo
        generic    /var/lib/irods/iRODS/Vault/home/rods/foo
  rods              2 repl;u1        32217 2017-01-24.08:56 & foo
        generic    /tmp/u1Vault/home/rods/foo
```

To get down to a single replica, you must also override the default minimum of 2 replicas which is in place to protect from accidental overtrimming:

```
$ itrim -n2 foo
$ ils -L foo
  rods              0 demoResc        32217 2017-01-24.08:56 & foo
        generic    /var/lib/irods/iRODS/Vault/home/rods/foo
  rods              2 repl;u1        32217 2017-01-24.08:56 & foo
        generic    /tmp/u1Vault/home/rods/foo

$ itrim -N1 -n2 foo
$ ils -L foo
  rods              0 demoResc        32217 2017-01-24.08:56 & foo
        generic    /var/lib/irods/iRODS/Vault/home/rods/foo
```


Yes, this is enough - we will mark the `irm -n` option as deprecated and point users to `itrim`.

**Comment by trel** [comment]
We still want to mark `irm -n` as deprecated in 4.3.

That's the work for this issue to be closed.

**Comment by PeteClapham** [comment]
Sorry I may miss-understand the text above. Being able to specify which object to remove, particularly if a single copy is corrupt, is rather useful. Would this be lost if irm -n is deprecated ?

**Comment by jaking92** [comment]
`itrim` deals with replicas where `irm` deals with data objects. The deprecation is meant to make this distinction clearer by restricting `irm` to deal only with data objects rather than particular replicas. So, `itrim -n` can/should be used to remove specific/corrupt replicas. If it is the *only remaining* replica, then `irm` can/should be used, because `itrim` will not remove the last copy of a data object.

Side note: `-N` flag specifies `numCopies`, or, the minimum number of replicas that should remain (defaults to 2). [More on `itrim` here](https://docs.irods.org/4.2.2/icommands/user/#itrim).

Hope that helps!

**Comment by jaking92** [comment]
Sorry, I should have explained that there are in fact two different flags for `itrim`:
```
-n  replNum  - the replica number of the replica to be deleted
-N  numCopies - minimum number of most current copies to keep. The default value is 2.
```
So `-n` will target the specified replica number. You can use `-N` in combination with this to ensure a minimum number of replicas remain after the trim. For example, if you want three replicas of `foo` at all times no matter what and you want to remove replica 1, you would run:
```
itrim -n 1 -N 3 foo
```
So this would remove replica 1 provided that three replicas remain afterwards. If you only have 3 replicas when you run that, nothing will happen.

Or, if you have 2 replicas and replica 1 is bad, you *must* use `-N` to specify that it is okay to have only 1 replica (since the default minimum number of replicas for `itrim` is 2):
```
itrim -n 1 -N 1 foo
```

**Comment by trel** [comment]
So we're still good?     You're making me nervous...

**Comment by trel** [comment]
Very well.   Thanks.
