### ISSUE TITLE
writeLine('stdout'...) not printing for Python RE when iRODS rule language RE is also present with irule -r

### ISSUE THREAD

**Issue by rskarbez** [irods/irods#3477]
When the Python and Native rule engines are both configured in the `rule_engines` list in `/etc/irods/server_config.json`, and python is first:

```
$ irule -F python_genquery_rule.r
$
```

When the Python and Native rule engines are both configured in the `rule_engines` list in `/etc/irods/server_config.json`, and python is not first:

```
$ irule -r irods_rule_engine_plugin-python-instance -F python_genquery_rule.r
$
```

**Comment by rskarbez** [comment]
Per conversation with Jason, tested this with a iRODS rule language rule with Python as the first rule engine and the iRODS rule language rule engine as the second, and did not observe the same problem. It appears to be somehow Python (or at least non-iRODS-rule-language) related.

**Comment by jasoncoposky** [comment]
This bug is only expressed when the native rule engine plugin is also configured along side the python rule engine plugin due to the fact that the ExecCmdOut_t structure is cached in a hash table for the implementation of writeLine for the native plugin whereas the python implementation which is used when the native is not configured will pass the ExecCmdOut_t structure through the msParamArray input.

For reference in the native plugin: 
https://github.com/irods/irods/blob/4-2-stable/plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/functions.cpp#L1981-L2002

And for the python implementation:
https://github.com/irods/irods/blob/4-2-stable/server/re/src/irods_re_structs.cpp#L269-L291

The python plugin will need to inject the provided execCmdOut into the native plugin's hash table.
