### ISSUE TITLE
reliably mitigate inappropriate client disconnect

### ISSUE THREAD

**Issue by trel** [irods/irods#3504]
The client exited without an appropriate disconnect - and then the Agent exited with `-4000`.

The AgentFactory needs to handle this error.  And the Agent should not exit hard when it sees a `-4000`.

```
Mar 29 17:07:49 pid:19790  ERROR: Agent [19790] exiting with status = -4000
Mar 29 17:07:50 pid:19717 remote addresses: X.X.X.X ERROR: Error sending socket to agent factory process, errno = [32]: Broken pipe
Mar 29 17:07:50 pid:19717 remote addresses: X.X.X.X ERROR: Bad acknowledgement from agent factory process, message = []
```

**Comment by rskarbez** [comment]
I think that the `-4000` isn't what's causing this bad behavior, it's a side effect of the actual problem, which is a dead agent factory process (the second irodsServer process).

I was able to reproduce by manually killing the agent factory process, and then trying to run an iRODS command. (Anything should work, I just tried an `ils`.)

`Apr 18 15:07:53 pid:27064 remote addresses: 127.0.0.1 ERROR: Agent [27064] exiting with status = -
4000`
`Apr 18 15:07:53 pid:27014  ERROR: Agent process [27064] exited with status [96]`
`Apr 18 15:21:39 pid:27013 remote addresses: 127.0.0.1 ERROR: Error sending socket to agent factory
 process, errno = [32]: Broken pipe`
`Apr 18 15:21:39 pid:27013 remote addresses: 127.0.0.1 ERROR: Bad acknowledgement from agent factory process, message = []`

I was NOT able to reproduce by, for example, Ctrl-C'ing out of a long running single-threaded iput. For example, doing

`truncate big_file.txt -s 10G`
`iput -N0 big_file.txt`

followed by a Ctrl-C behaved fine. (It killed the agent as expected, but the agent factory remained operational.)

If this is in fact the case, I don't think this is an actual issue. If this problem was discovered in a more nefarious way, could you provide more info as to how we found it?

**Comment by trel** [comment]
This was a Jargon connection that did "something bad" and didn't disconnect cleanly and so the Agent was unhappy with the end of the conversation (`SYS_HEADER_READ_LEN_ERR`).  The iCommands disconnect cleanly when Ctrl-C'd, I believe.

**Comment by andrew-irods** [comment]
Verified that a disrupted socket connection during iput does not cause problems in the agent factory process. 

Performed an "iput xxx" where xxx is a 10Gb file.  Jimmied up the socket so that on the fourth call to rcPartialDataPut() (this client function is in rcPortalOpr.cpp) the socket pointed to by myInput->conn->sock is blindly closed, disrupting the stream.  

The attached file shows both the client side error messages, as well as the error messages in the rodsLog file from the server.

The agent factory is unaffected by the induced error (agent returned -4000 as above), and the error messages are accurate on both the iput and server sides. 

The agent factory was verified to be up and functioning, by manually running "irodsctl status" before and after the iput, and then using ils, irm, and irmtrash again after each iput. 

[iputxxx.txt](https://github.com/irods/irods/files/2055064/iputxxx.txt)

**Comment by trel** [comment]
Excellent - so nothing to be done here.

Marking as 4.2.3 and closing.
