### ISSUE TITLE
itrim displays an incorrect count for files trimmed

### ISSUE THREAD

**Issue by jassigill2000** [irods/irods#3531]
the itrim command works under the hood but the output is misleading.
- [x] master
- [x] 4-2-stable
- [x] 4-1-stable

**Comment by kellerb** [comment]
https://github.com/irods/irods/blob/c1cafef303887985594878747b6d878187c9d4f6/lib/core/src/trimUtil.cpp#L101

Above line was added as part of this issue. At that point, `status` can be negative, indicating an error from `rcDataObjTrim()`, in which case the error code should be returned instead of calling `rcObjStat()`.
