### ISSUE TITLE
setup_irods.sh fails when the administrator's passwords as a '(' in it

### ISSUE THREAD

**Issue by tedgin** [irods/irods#3584]
I'm installing an iRODS 4.1.10 IES on a CentOS 6 server. I chose an admin password with a `(` in it. This choice caused setup_irods.sh to fail it's call to iinit and print the password to the terminal.

```
Step 4 of 4:  Configuring iRODS user and starting server...
    Updating iRODS user's ~/.irods/irods_environment.json...
    Starting iRODS server...
    Confirming catalog_schema_version... Success
    Validating [/var/lib/irods/.irods/irods_environment.json]... Success
    Validating [/etc/irods/server_config.json]... Success
    Validating [/etc/irods/hosts_config.json]... Success
    Validating [/etc/irods/host_access_control_config.json]... Success
    Validating [/etc/irods/database_config.json]... Success
    Opening iRODS connection...
sh: -c: line 0: syntax error near unexpected token `)'
sh: -c: line 0: `/usr/bin/iinit )pD7QmWoe5,%`?WW 2>&1'

Install problem:
    Connection to iRODS server failed.
        Found 2 processes:
	Stopping process id 21462
	Stopping process id 21464

Abort.
```

To get around this problem, I chose a new password that doesn't contain a `(`.

**Comment by tempoz** [comment]
I assume you mean that it contained a `)` ? Regardless, this would require adding the proper escaping of the string for shell to perl for when it passes the password to iinit (which would be significantly less than simple and quick to add). As this is already fixed in 4.2 by moving all setup into python (and away from making lots of direct calls to the shell, specifically to avoid problems like this), and one can work around it in 4.1 by changing the password to the desired one after setup, I'm going to close this wont-fix.
