### ISSUE TITLE
iscan not reporting missing 0-length files from disk

### ISSUE THREAD

**Issue by trel** [irods/irods#3681]
- [x] master
- [x] 4-2-stable
- [x] 4-1-stable
----------------------

`iscan` should complain if the 0-length file on disk is not present.

`a.txt` was not detected as missing.
`d.txt` was detected correctly.

```
irods@hostname:~$ ils -L ingested_stuff
/tempZone/home/rods/ingested_stuff:
  rods              0 demoResc            0 2017-10-13.13:48 & a.txt
        generic    /tmp/irods_ingest_demo/a.txt
  rods              0 demoResc            0 2017-10-13.13:48 & c.txt
        generic    /tmp/irods_ingest_demo/c.txt
  rods              0 demoResc           15 2017-10-13.13:48 & d.txt
        generic    /tmp/irods_ingest_demo/d.txt
  rods              0 demoResc            0 2017-10-13.13:49 & e.txt
        generic    /tmp/irods_ingest_demo/e.txt
irods@hostname:~$ ls -l /tmp/irods_ingest_demo/
total 4
-rw-rw-r-- 1 irods irods  0 Oct 13 13:46 a.txt
-rw-rw-r-- 1 irods irods  0 Oct 13 13:47 c.txt
-rw-rw-r-- 1 irods irods 15 Oct 13 13:47 d.txt
-rw-rw-r-- 1 irods irods  0 Oct 13 13:49 e.txt
irods@hostname:~$ iscan -r /tmp/irods_ingest_demo/
irods@hostname:~$ iscan -rd /tempZone/home/rods/ingested_stuff
irods@hostname:~$ rm /tmp/irods_ingest_demo/a.txt
irods@hostname:~$ iscan -r /tmp/irods_ingest_demo/
irods@hostname:~$ iscan -rd /tempZone/home/rods/ingested_stuff
irods@hostname:~$ rm /tmp/irods_ingest_demo/d.txt
irods@hostname:~$ iscan -r /tmp/irods_ingest_demo/
irods@hostname:~$ iscan -rd /tempZone/home/rods/ingested_stuff
Physical file /tmp/irods_ingest_demo/d.txt on server xxx.xxx.xxx.xxx is missing, corresponding to iRODS object /tempZone/home/rods/ingested_stuff/d.txt
irods@hostname:~$
```

**Comment by andrew-irods** [comment]
Recreated the issue, which gave rise to a few other possible issues.  For me these are questionable, since I don't know what the correct behavior is.  

The attached file Issue_3681-run1.txt has a complete run (this is a simple bash script). I'll refer to the line numbers in the file for reference.

First question I had was - how were the files associated with a resource to begin with?  I assumed "ireg -C... -R...", and that's what I used.

Lines 1-16:  Setup of resources (I used two) associated with the physical paths of the directories involved.  First question I had was - how were the files associated with a resource to begin with?  I assumed "ireg -C... -R...", and that's what I used (because you can't run iscan against a physical directory or file unless it's somehow registered against a resource). 


Lines 20-97:  Ran ls, ils, and iscan against the directories and individual files, showing correct behavior.

Line 101:  Removed one zero-length file (file1) from ptemp1, and a non-zero length file (file2) from ptemp2.

Lines 105-184: Ran ls, ils, and iscan against the directories and individual files, showing some issues (some questionable).

Here they are:

1. Lines 116-126:  ils -L of both logical directories show all files there, even though two of the physical files are missing (see 105-112).

2. Lines 130-141: ils -L of each of the individual logical files: all files got listed ok, even though two of the physical files were missing (ERROR?). 

3. Lines 146-147:  iscan -r of the physical dir ptemp1 returned 0.  (ERROR? one of the physical files - the zero-length file - is missing)

4. Lines 149-150:  iscan -r of the physical dir ptemp2 returned 0.  (ERROR? One of the physical files - the non-zero lengh file - is missing)

5. Lines 152-153:  iscan of logical ltemp1 did NOT detect the missing zero-lengh file (ERROR).

6. Lines 155-157:  iscan -rd of the logical ltemp2 correctly detected the missing non-zero length file (GOLD STAR!!!).  However, in this case, iscan still returned 0, which is an ERROR - and no gold stars.

7. Lines 159-171:  iscan's of the four individual physical files all correctly detected the missing two files and the return values from iscan when it found the errors were 184, correctly (GOLD STAR HERE!!).

8. Lines 173-184:  Individual iscan -d's for each individual logical file yielded two problems:  The missing logical ltemp1/file1 was successful (missing zero-length file) - ERROR.
And, the missing non-zero length file (ltemp2/file2) was detected, but the return code was still 0.  ERROR.

**Comment by andrew-irods** [comment]
[Issue_3681-run1.txt](https://github.com/irods/irods/files/1882028/Issue_3681-run1.txt)

See comment above.

**Comment by andrew-irods** [comment]
We need to fill out this functional matrix:

| iCommand           | return code | Error Message | Comment                   |
|:-------------------|:-----------:|:--------------|:--------------------------|
|                    |             |               |                           |
| ils -L ldir     |             |                  | missing pfile in pdir equivalent to ldir    |
|                    |             |               |                           |
| ils -L lfile     |             |                 | missing pfile equivalent to lfile   |
|                    |             |               |                           |
| iscan -r pdir      |             |               | missing local pfile in pdir     |
|                    |             |               |                           |
| iscan pfile   |             |                    | missing local pfile    |
|                    |             |               |                           |
| iscan -rd ldir |             |                   | missing local pfile in pdir equivalent to ldir   |
|                    |             |               |                           |
| iscan -d lfile    |             |                | missing local pfile equivalent to lfile        |
|                    |             |               |                           |

**Where:**

ldir is logical irods directory

pdir is physical local directory

lfile is logical irods file

pfile is physical local file

**Comment by andrew-irods** [comment]
Please ignore - just trying something out:

Icommand|Condition|rc should be|rc is|error message should show|error message is shown|Dispensation
|:---|:---|:---:|:---:|:---|
iscan -r pdir|Zero length file is missing from registered pdir|Non-0|0|YES|NO|ISSUE (rc + error msg)
iscan -r pdir|Non-zero length file is missing from registered pdir|Non-0|0|YES|NO|ISSUE (rc + error msg)
iscan pfile|Zero length file is missing|Non-0|184|YES|YES|OK
iscan pfile|Non-zero length file is missing|Non-0|184|YES|YES|OK
iscan -rd ldir|Zero length file is missing from ldir (registered pdir)|Non-0|0|YES|NO|ISSUE (rc + error msg)
iscan -rd ldir|Non-zero length file is missing  from ldir (registered pdir)|Non-0|0|YES|YES|ISSUE (rc)
iscan -d lfile|Zero length physical file is missing from ldir (registered pdir)|Non-0|0|YES|NO|ISSUE (rc + error msg)
iscan -d lfile|Non-zero length physical file is missing from ldir (registered pdir)|Non-0|0|YES|YES|ISSUE (rc)
||||||
||||||
||||||
||||||
|ldir is the collection - called logical irods directory in the results file|||||
|pdir is the physical local directory|||||
|lfile is the data object - called logical irods file in the results file|||||
|pfile is the physical local file|||||

**Comment by andrew-irods** [comment]
This matrix is to keep track of where the work is at.  Color coded!!!

[Issue-3681-matrix-fixed.xlsx](https://github.com/irods/irods/files/1887092/Issue-3681-matrix-fixed.xlsx)

**Comment by andrew-irods** [comment]
Adding test case which is currently an issue:

$ ireg -C "/full/path/pdir" ...

pdir has two files in it which are registered

$ cp /dev/null /full/path/newfile

# iscan -d /full/path/pdir 

This should emit an error message (because newfile is not registered in irods), and return a non-zero return code. 

Currently it does emit an error message, but a zero return code which is an error.

**Comment by andrew-irods** [comment]
One more unrelated fix:  error messages from scanObj go to either stdout or stderr.  Will be changed to make them all go to stdout.

**Comment by andrew-irods** [comment]
CI test passed: Build 761 - http://172.25.14.125:8080/view/2.%20Personal/job/irods-build-and-test-workflow/761/

**Comment by trel** [comment]
Nice.  I've merged and checked the `4-2-stable` checkbox above.

Please cherry-pick to master.
