### ISSUE TITLE
set socket options to avoid timeouts

### ISSUE THREAD

**Issue by HowardLander** [irods/irods#3824]
- [x] main
- [x] 4-3-stable
---

### iRODS Version, OS and Version
4.2.2 Ubuntu 7

### What did you try to do?
When trying to iput a 10GB file from a RENCI Ubuntu VM into a compound resource (using the new azure driver)on a Ubuntu VM inside of azure, the transfer failed because azure decided to close the connection on port 1247.  Oops... I fixed this on the client side by altering the kernel TCP parameters like so:

sudo echo 120 > /proc/sys/net/ipv4/tcp_keepalive_time
sudo echo 30 > /proc/sys/net/ipv4/tcp_keepalive_intvl

but arguably this should be handled by the iRODS client code using setsockopt to set the keep alive parameters (see http://tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/) on the individual socket . This could be configurable, if desired.

**Comment by trel** [comment]
"The TCP idle timeout on the Azure load balancer is 240 seconds by default."

**Comment by trel** [comment]
related to https://github.com/irods/irods/issues/5218

**Comment by stsnel** [comment]
It would also be helpful for us to have iRODS handle these settings on a socket level, mainly for the following use cases:
* Researchers who want to upload large files using the iCommands from shared infrastructure, such as a compute cluster, where sysadmins would prefer not to change kernel parameters for one application.
* Researchers who want to upload data using the iCommands on WSL are often not familiar with changing kernel parameters. It would be easier to have iRODS handle this automatically rather than talk users through these changes.

**Comment by trel** [comment]
Agreed - do you know the setting we'd need to manipulate?

**Comment by kript** [comment]
> Agreed - do you know the setting we'd need to manipulate?

There is code in the linked article above for a test program enabling and disabling, in case you hadn't seen it (I'd used it to investigate similar options for https://github.com/irods/irods/issues/3986).
