### ISSUE TITLE
Validate environment during ingest

### ISSUE THREAD

**Issue by tempoz** [irods/irods#3845]
The server configuration file contains an environment which is currently under-specified. In particular, all values in an environment must be strings, and this is not enforced anywhere. It is possible the schema itself can be changed to account for this, but if that is not possible it must be checked for and reported in the python that loads the json file.

**Comment by trel** [comment]
Not sure what this issue is about.

Closing soon unless @tempoz appears and shares some more smart words.

**Comment by korydraughn** [comment]
I thought this was about the server_config.json schema's definition of `environment_variables`, but after comparing the date of this issue and the date of the schema, this must be referring to something else.

If you start here and go back in time using git blame, you'll notice that `additionalProperties` was set to `{ "type": "string" }` long before this issue was created.
https://github.com/irods/irods/blob/24e1d3db8726a43b60121b3b00981a5e035a3336/configuration_schemas/v3/server_config.json#L30

Perhaps the tool we used to validate schemas back then did not support all features of the schema spec.

With that said, I think we should close this. If the schema is too loose, we can open up a new issue and handle it then.

@trel Any thoughts?

**Comment by trel** [comment]
Knowing that it was added prior to the creation of this issue is definitely confusing - yes, I think we close this and deal with anything new in a new issue.  No clear action items here.
