### ISSUE TITLE
When delayed rules are run in parallel by at most N forked processes, at most N delayed rules are run per batch

### ISSUE THREAD

**Issue by dworkin** [irods/irods#3941]
- [x] master
- [x] 4-2-stable
-----

### iRODS Version, OS and Version

iRODS master / 4.2.2

### What did you try to do?

When ``maximum_number_of_concurrent_rule_engine_server_processes`` is 4, at most 4 delayed rules will be processed per batch, and ``rule_engine_server_execution_time_in_seconds`` is ignored.  This seems odd, given that when parallelisation is disabled, and delayed rules are run sequentially, more than 4 delayed rules can be processed per batch. This can work out to single-threaded processing of delayed rules being faster.

### Expected behavior

**When** ``maximum_number_of_concurrent_rule_engine_server_processes`` is 4, ``rule_engine_server_sleep_time_in_seconds`` is 30, ``rule_engine_server_execution_time_in_seconds`` is 120, there are 10 delayed rules in the queue, and each delayed rule takes about a second to process,
**then** I expect all 10 to be processed in the same batch, at most 4 concurrently.

### Observed behavior (including steps to reproduce, if applicable)

Only 4 delayed rules will be processed.

**Comment by jaking92** [comment]
Hi @dworkin. Thanks for all the good work in the pull request!

I ran the following rule:
```
myTestRule {
    for(*i = 0; *i < 10; *i = *i + 1) {
        delay("<PLUSET>10s</PLUSET>") {
            writeLine("serverLog", "delay *i");
        }
    }
}
OUTPUT ruleExecOut
```
...with the following settings in `server_config.json` (same as those described above):
```
"maximum_number_of_concurrent_rule_engine_server_processes": 4, 
"rule_engine_server_execution_time_in_seconds": 120, 
"rule_engine_server_sleep_time_in_seconds": 30, 
```
...and got the following output in the log:
```
Jul 10 13:15:13 pid:37530 NOTICE: writeLine: inString = delay 0
Jul 10 13:15:13 pid:37534 NOTICE: writeLine: inString = delay 2
Jul 10 13:15:13 pid:37535 NOTICE: writeLine: inString = delay 3
Jul 10 13:15:13 pid:37532 NOTICE: writeLine: inString = delay 1
Jul 10 13:15:13 pid:37544 NOTICE: writeLine: inString = delay 5
Jul 10 13:15:13 pid:37542 NOTICE: writeLine: inString = delay 4
Jul 10 13:15:13 pid:37546 NOTICE: writeLine: inString = delay 6
Jul 10 13:15:13 pid:37548 NOTICE: writeLine: inString = delay 7
Jul 10 13:15:43 pid:37560 NOTICE: writeLine: inString = delay 9
Jul 10 13:15:43 pid:37559 NOTICE: writeLine: inString = delay 8
```
All 10 rules get processed over 2 RE server wake-ups, with 8 delayed rules processed on the first wake-up, and 2 on the second. So the observation I have is that 2N (in this case, 2N=8 since N=4) processes are run per batch. Does this align with what you were seeing?

The doubling is due to a subtle bug in the code for getting rules off the queue where we are processing rules not marked as "failed" twice per pass in reServerMain.

https://github.com/irods/irods/blob/87e9b6c31ee01b1df3118ccef3cc22b480927785/server/core/src/reServerLib.cpp#L224

We wanted to make sure we had the right before/after assertions when writing the tests. It doesn't really have to do with the correctness of your change, which is fine. Thanks!

**Comment by dworkin** [comment]
Hi @jaking92,
You are completely right, the number of delayed rules processed in one batch is 2N, not N as I stated.

**Comment by jaking92** [comment]
Okay, thanks for confirming!

It looks like writing a test for the 2N bug's fix is a pointless exercise because the change to process as many batched rules as possible masks the problem. Either all of the queued processes will complete in the `rule_engine_server_execution_time_in_seconds` window, or they will not. In the latter case, the failed processes will not be retried either because the execution time window has closed by that point. The rest of the jobs will complete in the next wake-up (or the next... or the next), and the retry will pick up the failed process (eventually).

As such, we are planning on merging @dworkin's change, then following it with an accompanying test and a fix for the 2N problem (with no accompanying test). CI tests are running now.

**Comment by trel** [comment]
fixed on master - need the 4-2-stable cherry-pick.
