### ISSUE TITLE
Zero length replica 1

### ISSUE THREAD

**Issue by bh9** [irods/irods#4170]
- [x] master
- [x] 4-2-stable
---------
### iRODS Version, OS and Version
4.1.10, Ubuntu 12

### What did you try to do?
iput large file over congested pipe to replicated resource

### Expected behavior
2 good replicas

### Observed behavior (including steps to reproduce, if applicable)
1 good replica on disk, catalog has correct checksum for this replica, but says it has 0 length
1 zero-length replica with no catalog checksum
```
irods@irods-sanger1:~$ ils -L /seq/ont/gridion/GXB01179/Multiplex_ligation_291018/GA20000/GA20000_fast5_2018-10-29T141014.0.tar
  srpipe            0 root;replicate;seq-red;red3;irods-seq-i20-de            0 2018-10-29.14:09 & GA20000_fast5_2018-10-29T141014.0.tar
    77b9a010cd4cbfa222053c1af78fb8a2    generic    /irods-seq-i20-de/ont/gridion/GXB01179/Multiplex_ligation_291018/GA20000/GA20000_fast5_2018-10-29T141014.0.tar
  srpipe            1 root;replicate;seq-green;green2;irods-seq-sr02-ddn-ra08-6-7-8            0 2018-10-29.14:21 & GA20000_fast5_2018-10-29T141014.0.tar
        generic    /irods-seq-sr02-ddn-ra08-6-7-8/ont/gridion/GXB01179/Multiplex_ligation_291018/GA20000/GA20000_fast5_2018-10-29T141014.0.tar
```

**Comment by trel** [comment]
Not sure how to reproduce this, yet.

If the first replica is not 'complete' (still has 0-length in catalog), it's not clear how the replication is triggered.

**Comment by bh9** [comment]
Triggered using tears, not iput.

**Comment by kript** [comment]
A slight correction for the above; `biobambam` _reads_ the same way `tears` does, but `tears` is used for the writing...

**Comment by kript** [comment]
So what I think is happening, as I'm not sure I made it clear above, is that the data upload succeeds, so the file on disk is complete, but as the control connection had dropped, iRODS catalog is not updated with the completion, and so our rule isn't triggered to do the Checksum, and the size isn't updated (since iRODS creates the catalog entry for the file with 0 length on starting the upload), as tears only know what size to provide when its finished writing, since its written to support streaming/pipelining. 
This isn't _quite_ the same case as the one the issue was opened with, but its similar, sorry...

**Comment by trel** [comment]
I like the #3986 theory, but...

Did the server holding the connection trigger the replication?  If not, who did?

How did it know that the file was complete if the control connection had dropped?

**Comment by alanking** [comment]
Cannot check boxes, but I think this can be closed.
