### ISSUE TITLE
new multipart transfer mechanism

### ISSUE THREAD

**Issue by trel** [irods/irods#4336]
- [x] master
- [x] 4-2-stable
------

## Feature

Leveraging lessons learned from [last year's multipart investigation](https://github.com/irods/irods_api_plugin_multipart)...

This will use the new dstream operator (https://github.com/irods/irods/issues/4268).

- solves race conditions caused by inconsistent catalog entries related to parallel transfer
  - incorrectly marked 'good' leftover/failed 0-length files (#4170)
  - data incorrectly readable from failed 0-length files (#4195)
  - extra/undesired replicas due to rebalance (#4314)
- replaces legacy parallel transfer (#4335)
  - leverages any in-place SSL capabilities
  - removes need for parallel transfer portal (high ports)
- enables reimplementation of rsDataObjRepl (#4334)

**Comment by bh9** [comment]
I'm fairly sure the problem in #4314 is caused by the rebalance seeing a good replica 0 existing, but no replica 1 existing, and removing the zero-length catalogue entry will actually increase the time for which this is the case, especially for large files.
I can also see this leaving significantly more unregistered files from failed uploads which are only accessible through the filesystem.

**Comment by kript** [comment]
Is it time to look at #2796 as part of this?

**Comment by korydraughn** [comment]
can this be closed?

**Comment by trel** [comment]
I think so - the linked issues above are all (save one) still open, but that's why they're separate issues...

@alanking any hesitation here?  If not, I'll mark it 4.2.9 and close it.

**Comment by alanking** [comment]
I believe bullet 1 will be covered by a combination of #4343 and #3848
