### ISSUE TITLE
irodsReServer becomes a zombie

### ISSUE THREAD

**Issue by lwesterhof** [irods/irods#4351]
- [x] master
- [x] 4-2-stable
---
### iRODS Version, OS and Version
iRODS 4.2.5
CentOS Linux release 7.3.1611 (Core)
Linux 3.10.0-514.16.1.el7.x86_64

### What did you try to do?
Filled the delayed rule queue with jobs.

### Expected behavior
Jobs are processed by the irodsReServer.

### Observed behavior (including steps to reproduce, if applicable)
Jobs are processed by the irodsReServer, but after some time the irodsReServer becomes a zombie:
```bash
$ ps -edalf | grep irods
1 S irods    55373     1  0  80   0 - 207479 poll_s 07:46 ?       00:00:04 /usr/sbin/irodsServer
1 S irods    55374 55373  0  80   0 - 27108 poll_s 07:46 ?        00:00:07 /usr/sbin/irodsServer
0 Z irods    55376 55373  8  80   0 -     0 do_exi 07:46 ?        00:08:26 [irodsReServer] <defunct>
```

This worked for us on iRODS 4.2.4.

**Comment by alanking** [comment]
Do you have any clues in your reLog or rodsLog as to what happened (stacktraces, caught signals, etc.)? When a signal is caught by the RE server, you should have a "NOTICE" message in the log of the form "RE server received signal [\<signal\>]" and the RE server is then terminated upon its receipt. We have not seen this in our testing so that will help us with the investigation and writing a test for this.

Our first impression is that this is a matter of an uncaught exception in the task posted to the io_service for executing rules:
https://github.com/irods/irods/blob/db085559893dabcb8e3acd30dbd7c4b65bc110dc/server/core/src/irodsReServer.cpp#L266-L278
The `run_rule_exec` call should be wrapped with a try-catch as well so the offending thread will not take down the entire long-running RE server process.

Thanks!

**Comment by lwesterhof** [comment]
Some clues in the reLog and rodsLog: https://gist.github.com/lwesterhof/abd926da49a1168a271c5d6169a53189

On Apr 15 08:11:30 the server is still processing delayed rules (iiRevisionCreate). On Apr 15 08:11:31 a unixODBC error occurs and everything goes haywire.

**Comment by alanking** [comment]
Thanks for the quick response and the detailed report. I was able to reproduce this in a test and a fix will be merged shortly.
