### ISSUE TITLE
Add detached mode to unixfilesystem plugin

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#4421]
- [x] main
- [x] 4-3-stable
-------

## Feature

Add detached mode to UFS.

This will be similar to what is done for the cacheless S3 plugin.  Any resource server can serve up the request.

**Comment by anderbubble** [comment]
Strongly suggest that there be a way to nominate which resources servers can respond to requests for each resource. For example, we want to mount NFS to our resource servers and serve the data out from any of them that have the path mounted; but possibly not all resources servers might have this path mounted. Even if it's just a way to influence the voting, the mechanism for controlling which resource servers respond for each detached resource should be well understood and documented. (I feel the same way about the cacheless S3 plugin, though we're not using that today, so it doesn't affect us directly.)

**Comment by kript** [comment]
This would be quite interesting for us - we're thinking about ways we can use Isilon or Lustre, and this might be quite a good way to approach that, so registering our interest here.

If its going to support/be intended for NFS, then it would be great if there was a way it could detect/handle NFS et al mounts going away, which might not happen often, but would be quite disruptive if they did.

I can see an HA deployment using multiple consumers with this model...

**Comment by trel** [comment]
Excellent.

Yes, storage that *isn't* there after a vote will require some retries and/or the ability to go back and 'revote' to select a different storage resource.

Related to https://github.com/irods/irods/issues/3480.

**Comment by JustinKyleJames** [comment]
We will have a host_list parameter in the resource context string.  If this exists, only the hosts in the list will be considered available to serve the request.

Also note that we considered adding a path for each host so the mount point doesn't have to be identical but that isn't feasible because the full path is stored in the catalog.  Therefore, the mount point must be identical for all servers.

**Comment by alanking** [comment]
Anything else to do?

**Comment by trel** [comment]
@JustinKyleJames can this be closed?

**Comment by JustinKyleJames** [comment]
Closing this as it has been merged.

**Comment by yr-wang-hit** [comment]
Detached mode in ufs means that ` any server may serve up requests for the resource as long as all servers share a common mounted vault` . imagine some unified storage like nfs or isilon with multiple servers mounted on it, some with irods resource server installed on them, others without(have no related to irods at all), Whether The host_list must only specify the servers with irods resource server installed or either one is OK?

**Comment by trel** [comment]
Hi @yr-wang-hit - the documentation is here:
  https://docs.irods.org/4.3.1/plugins/composable_resources/#detached-mode-configuration

It would not make any sense to point to hosts that are NOT running iRODS servers... so I think the answer to your question is...

Yes, entries in the `host_list` must be iRODS servers.  And those iRODS servers must have the mount point available.

**Comment by alanking** [comment]
Point of pedantry... I think that it is *allowed* to specify hosts which are not running iRODS servers, but it would have no effect whatsoever because the point of the list is to indicate to a running iRODS server/agent that it does not need to redirect to access data in that resource.

So I'll echo @trel's sentiment and say just don't do that. :)

**Comment by trel** [comment]
Oh, I see.    Yes, agreed.

**Comment by yr-wang-hit** [comment]
So the vote mechanism of resource servers in the host_list may take workload as consideration so that workload(write) will be balanced to underlying unified storage(say isilon) when many write requests hit that resource?

**Comment by trel** [comment]
If you have the following hierarchy...

```
$ ilsresc --ascii
randresc:random
|-- ufs1:unixfilesystem
|-- ufs2:unixfilesystem
|-- ufs3:unixfilesystem
|-- ufs4:unixfilesystem
`-- ufs5:unixfilesystem
```
And each of ufs1-ufs5 has a consistent mount point to an underlying unified storage system, then yes, they would randomly be assigned any incoming write requests and should share the load evenly.

Please experiment and see how it scales.

**Comment by yr-wang-hit** [comment]
Thanks @trel, I will try to experiment and collect some performance data.

In my opinion, What we want is if we create a detached mode ufs and specify its related host_list(say host1, host2, host3 three resource servers), we have a resource that if we attempt to write to it， the request will be automatically distributed to its three resource servers(maybe through some mechanism like voting by server statistics(cpu or memory/disk usage)) , and a single resource can manage a tens PB storage system(say isilon) in irods way.  As the storage system grows, we can horizontally scale the system by adding resource servers so that number of resource servers will not be the bottleneck of the resource when heavy workload hits the resource.
Intuitively, A unified storage system should not split to many ufs resources just to share the I/O workload. If we use random resource to distribute the I/O workload as the example says, it seems there is no difference between attached mode and detached mode, right? what if one resource for one unified storage system like:
```
$ ilsresc --ascii
| -- ufs1: unixfilesystem(isilon, detached mode, host1,host2,host3)
| -- ufs2: unixfilesystem(lustre, detached mode, host4,host5,host6)
| -- ufs3: unixfilesystem(nfs-bufferd tape library, detached mode, host7)
```
it seems much more manageable from the perspective of data infrastructure of a big data center.

**Comment by alanking** [comment]
That is one benefit of detached mode, yes - being able to have one storage resource serviced by many iRODS servers.

Unless I'm misunderstanding, the example with the random resource would be more useful in an *attached* situation for the use case being described here (that is, distributing workload across servers). Each resource would be *attached* to a server with a vault path pointed at a mount point to the same storage for each server.

For detached mode, the random resource and multiple resources would be useful if one wanted to distribute the processing requirements across many servers *and* the storage requirements across many storage systems. Each resource could be serviced by any or all of the same servers, but would be managing separate storage systems, if you will.

Not sure if that adds anything for your investigation, but, I felt the need to throw that out there :)

**Comment by trel** [comment]
Alan is correct.   Random and attached/detached solve different problems.   but could definitely be used in concert.

**Comment by yr-wang-hit** [comment]
yeap，make sense. Thanks to trel and alan for patiently reply
