### ISSUE TITLE
Remove user quota functionality

### ISSUE THREAD

**Issue by alanking** [irods/irods#4481]
- [x] main - core
- [x] main - icommands
----

## Proposal

ORIGINAL TITLE - Remove group quota functionality

Total and per-resource quotas should be enforceable for users only (not groups). The concept of a group quota is incompatible with user quotas (both cannot be enforced simultaneously).

**Reasoning:**
1. Adding a heavyweight user to a group could restrict all other group members from writing to the system.
2. If the user's quota is full, but if a group of which the user is a member still has remaining unused quota, it is unclear which one should be enforced.

**Usage effect:** `iadmin sgq` will be removed, all mentions of "group" will be removed from quota help texts (`iadmin cu`, `iadmin lq`, `iquota`, etc.).

**Upgrade effect:** Walk `R_QUOTA_MAIN` and `R_QUOTA_USAGE` and remove all rows where `user_id` is of type `rodsgroup`.

**Comment by kript** [comment]
Before TWG, to hopefully aid discussion;
We use group quotas extensively on one of our Zones. 
Its not clear what the recommended replacement is.

Reason 1 is the point of quotas, and I feel well understood (perhaps just by us, but then we do the same withing with Lustre filesystems), and manageable as long as there are tools available to show who is using the space.
Reason 2: more tricky, I do admit. Unix has the concept of a 'primary group' here. Same concept, perhaps? 

Perhaps instead have either group OR user quotas available, with the default being group?
Switching later not supported, perhaps?

**Comment by bh9** [comment]
Reason 2 doesn't seem tricky to me, if a user has exhausted their quota, they shouldn't be able to write. If both user quota and group quota are enabled, quota enforcement should be a binary and of:
- does the user have available quota to write to the system
- does the group have available quota to write to the system
so your example would result in a quota error

**Comment by trel** [comment]
Okay - other things to consider...

3. What permission matters when counting against quota?  read?  write?  own?

4. How do user and group quotas interact?  A data object of size 2GB is owned by userA, userB, and groupC (of which both A and B are members).  How much does this single data object count against everyone's quota?   userA's quota should count it 2G, userB's quota should count it 2G, and groupC's quota should count... 2G or 4G or 6G or 8G?

5. Should every replica count?  Same as above... if data object of 2G has three replicas... userA should count 2G or 6G?  groupC is what?

We need to draw some clean lines between logical/physical and user/group and total/resource.

Logical Quotas would eliminate consideration 5.  The rest is still hard and open for discussion.

**Comment by kript** [comment]
3. own, IMHO
4. as above,  instead have either group OR user quotas available, with the default being group?
5. yes. At least, that's how we currently do it. I could see logical quota also working.  On reflection, would support either but needs to be one of the other, with a default.

**Comment by trel** [comment]
So maybe we can thread the needle...

## Considerations:
C1) Logical Quotas (count only one good replica) and/or Physical Quotas (count all the replicas)
C2) User Quotas and/or Group Quotas (can they co-exist?)
C3) Total Quotas and/or Per-Resource Quotas (already both exist)
C4) Which replica(s) count - OWN, WRITE, READ (leaning towards WRITE or greater)

## Proposal:
A create/write operation by user `U` in groups `G1` and `G2` to a resource `R` should be allowed if:
A) `U` has remaining total quota available (or is not defined)
AND
B) `U` has remaining per-resource quota on `R` available (or is not defined)
AND
C) `G1` has remaining total quota available (or is not defined)
AND
D) `G2` has remaining total quota available (or is not defined)
AND
E) `G1` has remaining per-resource quota on `R` available (or is not defined)
AND
F) `G2` has remaining per-resource quota on `R` available (or is not defined)

If any of those conditions are not met, the create/write operation will be denied with a QUOTA error.

---
Does granting someone READ access today affect their quota?  Need to test the current implementation a bit more to understand C4 a bit better.

**Comment by tedgin** [comment]
AFAICT, `U` must be the primary owner of a data object before it counts against their quota. This is true even if you set `U`'s ` permission on the object to `null`. Likewise, this object counts against `G1`'s and `G2`'s quotas regardless of any permissions they have on it.  Calculating a user's usage based on primary ownership makes sense, but having a group's usage only based on the primary ownership of its users without consideration of the group being able to access these data doesn't.  

Could we also require that a group have `own` permission on a data object before it counts towards the groups usage? In other words, I propose the following addendum.

For a data object to count against a group's quota, the primary owner of the data object must be a member of the group, and the group must have `own` permission on the data object.

**Comment by trel** [comment]
I think the concept of 'primary owner' is problematic - permissions should be counted 'as is' without knowledge of when they were granted.

Quotas *should(?)* only care about whether someone can write more data... which is why I proposed `WRITE` as the level of permission that should matter when evaluating whether to block a create/write operation.

Proposal:

- **Current Used Total Quota for User `U`** is equal to the sum of the bytes of the data objects on which `U` has `WRITE` or `OWN` permission.
- **Current Used Per-Resource Quota for User `U` on Resource `R`** is equal to the sum of the bytes of the data objects on which `U` has `WRITE` or `OWN` permission on replicas stored on `R`.
- **Current Used Total Quota for Group `G`** is equal to the sum of the bytes of the data objects on which `G` has `WRITE` or `OWN` permission.
- **Current Used Per-Resource Quota for Group `G` on Resource `R`** is equal to the sum of the bytes of the data objects on which `U` has `WRITE` or `OWN` permission on replicas stored on `R`.

These totals do not take group membership into consideration when calculating current totals... only that the group has been granted `WRITE` or `OWN` permission *as* a group.

Re: Logical Quotas vs. All Replicas...  I think it works if Total Quotas are considered to be Logical Quotas, and the Per-Resource Quotas are Physical Quotas (as they're already dealing with replicas on a particular physical resource).

**Comment by tedgin** [comment]
Image this scenario.  We have a quota policy where are users get a logical quota of 100 GiB.  A user may get a higher one if they request it, and their request is approved.  We have two users: _Elite_ and _Normal_.  Elite went through this request process and has a quota of 1 TiB.  Elite has a collection named _Project_ containing 200 GiB of data. This user asks Normal to edit this data and gives Normal write permission on all of the data in Project.  This immediately forces  Normal to exceed their quota. Since Normal only has write permission, they cannot remove their write permissions.  This means that Elite has the ability to make Normal exceed their quota, possibly without approval, and that Normal cannot undo this action.  They must either ask Elite or get help from an admin user. Having a primary owner prevents this situation.  

Restricting usage computation to just those objects that a user has own permission on makes it easier for the user to fix; the user can just lower their permission.  However, it still allows one user to influence another user's usage count.  This is storage equivalent of a denial of service attack.

Using own (or write) permission to compute quotas also allows users to game the system.  A user with a 100 GiB quota could have 100 TiB of data they are the primary owner of.  They just give themself read permission on everything.  When they want to use some of the data, they raise their permission to write or own on just the set of data they will use and lower the permission when they is done.

These arguments hold for group quotas as well, but since a group cannot be a primary owner, I don't have any idea what to do about it.

**Comment by edwins** [comment]
To provide a short drive-by opinion, I agree that supporting both user and group quotas presents challenges, given iRODS permission model and functionality. However, in response to the title of this feature enhancement, I would actually support the removal of user quota functionality, rather than group quotas. For my organization, it is quite common that our users are organized around research projects/groups, and we assign storage quotas more to projects and groups than to individual users.

Here are some additional thoughts on what was already mentioned about primary ownership and groups quotas:

* If a site needs quotas by user, then a user could be considered as belonging to their own logical group (of size 1).

* Having a primary logical owner (group) ~strictly for the purposes of quotas~ might help streamline iRODS quotas and not having to worry about own vs write, multiple owners, or gaming the system by using iRODS hidden features.

* In my opinion, storage usage (and quotas) should be counted once, meaning the ability of deposit data shouldn't depend on both a user AND group quota. I've used other multi-tier quota systems, and it can be frustrating to both admins and users to try to track down the cause of over-quota issues, particularly since most quota errors do not reveal all the quota checks used to verify limits. Of course, this frustration may be mitigated if we had good tooling (per kript's response).

* I am not familiar with "logical quotas", but regarding the counting of replicas against quotas, could this be a configuration? If not, then I would say count them :).

Note, I understand some of my thoughts do not consider what it would take to implement certain changes to the existing quota functionality.

**Comment by trel** [comment]
@tedgin I think that the very valid (thanks for bringing it up) storage-DOS attack warrants considering using `OWN` as the permission to count.  Counting `OWN` additionally means those users could even delete some data to get back under the limit they are violating.

I don't see a good way around an original owner 'gaming the system' by lowering/raising their permissions.  Utrecht University has a policy whereby new data comes in, and then the system copies the original data object (primary owner = user) to a new data object (primary owner = admin), and then removes the original, and swaps in the new, and sets appropriate permissions.  This prevents the 'gaming' scenario.

@edwins I appreciate the 'single member group' idea.  It has merit, but is probably a lot of work for large installations?

Can you tell me more about the multi-tier quota system frustrations?  We would definitely think through printing out enough information to easily identify the limiting quota calculation.

I hesitate to count all replicas against the 'Total Quota' limits because the replication policy could be hard-coded and out of the users' hands.  Counting only logical quotas (3 replicas of a 1MB file would only count 1MB against a user's Total Quota) seems correct in this case.

**Comment by edwins** [comment]
@trel by "a lot of work for large installations", what do you mean? I wouldn't suggest that irods groups be created manually by site administrators -- that would be very onerous and error prone. If anything I suggest that iRODS would magically take care of that, either logically (i.e. in code vs a real group) or perhaps automatically creating a real group per user. As a model for the latter, Linux by default will create a group named after a user account. Of course, in Linux, you can also add additional users to that same group, which is another nice feature of that model.

As for an example multi-tier quota system, one that comes to mind is OpenStack, specifically OpenStack Nova, with quotas for multiple resources, not just storage. OpenStack Nova has default (global), user, and project quotas. Despite what the OpenStack documentation says (and depending on which documentation you read and version of OpenStack), quotas are calculated based on the minimum of a user's user and project quotas. Again, part of the frustration I have enjoyed along with my fellow cloud admins and users with OpenStack's quota implementation is that the tooling is inadequate: for a user who has both user and project quotas defined, which they may not be, an admin needs to use two separate tools (or apis) to read/update them properly. An over-quota limit error will only specify that the quota was reach but will not report which quota was in violation.

Regarding replica counting for quotas, for certain large projects, we negotiate total storage limits, which includes a max replication factor (note, some users are looking toward AWS Glacier/Deep Archive as an alternative means of replication). Due to research grant proposal processes, these storage limits are negotiated before hand, sometimes a few years in advance. Some users may want a subset of their data replicated at a higher level while another subset of their data by the same project may not need that availability/durability. The replication factor for these collections/resources would still be managed by us automatically using rules. In any case, it would be nice if a site admin could configure total storage calculations for quotas as logical vs actual (including replicas).

**Comment by tedgin** [comment]
I'll expand on what @edwins said about storage usage only being counted once. 

The reason for placing a quota on something is to prevent a user or a group of users from hogging a finite resource.  It's not to limit their access to only a certain amount of data. By applying a quota to the volume of data a user is the primary owner of, you are limiting the amount of a  resource they can consume.  By applying a quota to the volume of data a user has `own` permission on, you are limiting their access to a certain amount of data.  A 1 GiB data object could be owned by 10,000 users, or 10,000 1 GiB data objects could each be owned by a distinct user.  In both cases, 10,000 users have each used 1 GiB of their quota.  In the first case, only 1 GiB of storage is used, but in the second 10,000 GiB of storage has been used. Thus by applying based on `own` permission you aren't really controlling the amount of storage being consumed, only the amount of data each user has access to.

This is true for resource specific quotas, but it can also be made true for logical quotas. You just need to limit the number of replicas users can make.

**Comment by darthtux** [comment]
Recently I have been looking at the storage tiering capability and I really like how you can adjust the object violation query with metadata.  I am wondering if that idea would make sense here with quotas.  It seems like different groups have different ideas on how quotas should work.  Maybe it would make sense to have a default definition for how user and group quotas are calculated but have the option to change it through a config option in server_config.json?

**Comment by trel** [comment]
Hi @darthtux, welcome.

We haven't updated this conversation in a while.

Logical Quotas are now real, and will be provided via rule engine plugin - first release coming soon.

  https://github.com/irods/irods_rule_engine_plugin_logical_quotas/

**Comment by darthtux** [comment]
Awesome, thanks @trel !

**Comment by trel** [comment]
Due to...

> The concept of a group quota is incompatible with user quotas (both cannot be enforced simultaneously).

and

> I agree that supporting both user and group quotas presents challenges, given iRODS permission model and functionality. However, in response to the title of this feature enhancement, I would actually support the removal of user quota functionality, rather than group quotas.

so...

We have determined that we can change the title of this issue to 'remove user quota functionality'.

Group quota functionality would remain unchanged.

This is workable because every user in iRODS also is/has a group of the same name.  So setting a 'group' quota on a group named 'alice' would provide the same functionality of today's 'user quota' (assuming the 'alice' user is the only user in the group 'alice').

**Comment by trel** [comment]
Considering just limiting the use of `iadmin suq` to only allow a value of `0` for now (which 'unsets' a quota).

(and change the help text to explain this).

This will remove the ability to set a new quota for a user.

This will leave any existing quotas in place until we remove them more completely.

**Comment by mstfdkmn** [comment]
> Due to...
> 
> > The concept of a group quota is incompatible with user quotas (both cannot be enforced simultaneously).
> 
> and
> 
> > I agree that supporting both user and group quotas presents challenges, given iRODS permission model and functionality. However, in response to the title of this feature enhancement, I would actually support the removal of user quota functionality, rather than group quotas.
> 
> so...
> 
> We have determined that we can change the title of this issue to 'remove user quota functionality'.
> 
> Group quota functionality would remain unchanged.
> 
> This is workable because every user in iRODS also is/has a group of the same name. So setting a 'group' quota on a group named 'alice' would provide the same functionality of today's 'user quota' (assuming the 'alice' user is the only user in the group 'alice').

I have tried to read all regarding with the native quota. I am confused with what was said here. Could you elaborate this pls?

What I tried:

I wanted to set quota on a user as a rodsadmin assuming that user has the same name of its group.
```
[irods@dev-u0137480 ~]$ iadmin sgq user1 total 20
remote addresses: 10.0.2.100 ERROR: rcGeneralAdmin failed with error -829000 CAT_INVALID_GROUP
```
```
[irods@dev-u0137480 ~]$ iquest "select USER_GROUP_NAME"
USER_GROUP_NAME = group
------------------------------------------------------------
USER_GROUP_NAME = public
------------------------------------------------------------
USER_GROUP_NAME = rods
------------------------------------------------------------
USER_GROUP_NAME = user1
------------------------------------------------------------
```
```
[irods@dev-u0137480 ~]$ iadmin moduser user1 type rodsgroup
remote addresses: 10.0.2.100 ERROR: rcGeneralAdmin failed with error -169000 SYS_NOT_ALLOWED
Level 0: a user cannot be changed to a group
```

**Comment by korydraughn** [comment]
The comment you're referencing is mostly true. The issue is that it states for every user in the system, there is a group with the same name. That isn't true for 4.3.0 or 4.2.11. When a user is created in these systems, a group is NOT created along with them.

The second issue is assuming the query you wrote consists only of groups. Your query is returning a mix of users and groups because `select USER_GROUP_NAME` is the same as manually running `select user_name from R_USER_MAIN`. `select USER_NAME` produces the same result.

To see only groups, you need to add a condition that discards users. For example, `select USER_GROUP_NAME where USER_TYPE = 'rodsgroup'`. This is similar to how `select META_COLL_ATTR_NAME` returns all metadata attribute names in the system rather than for just collections.

Here is documentation on how to simulate user quotas with group quotas.
- https://github.com/irods/irods_docs/blob/f45ee07719b459fcb653eeb4d422bd4be003fc8c/docs/administrators/policy_cookbook.md#simulating-user-quotas

Keep in mind that the docs I just linked target 4.3.

**Comment by mstfdkmn** [comment]
Thanks @korydraughn, we see now how to manage user-based quota by using the native group quota. But pity that we could not catch this in our tests regarding with changes both for 4.2.11 and 4.3.0. Could you share which commit made this change?  

> To see only groups, you need to add a condition that discards users. For example, select USER_GROUP_NAME where USER_TYPE = 'rodsgroup'. This is similar to how select META_COLL_ATTR_NAME returns all metadata attribute names in the system rather than for just collections.

Yes, I just wanted to show `user1` appears on the `USER_GROUP_NAME` attribute but its user type is not `rodsgroup`.

**Comment by korydraughn** [comment]
Are you asking about the commit which made it so that new users do not result in new groups?
