### ISSUE TITLE
ibun fails to unzip a 3.2GB zip file

### ISSUE THREAD

**Issue by hyi** [irods/irods#4495]
- [x] master
- [x] 4-2-stable
---
This issue can be reproduced with this 3.2GB zip file: http://people.renci.org/~hongyi/irods/OcheyedanRiver.zip using this command ```ibun -xDzip```
It can be reproduced in iRODS version 4.2.6. @trel is able to reproduce the issue in iRODS 4.2.6. When running this ibun command to unzip this file, ibun immediately returns without doing anything. No relevant messages are recorded in the log.

**Comment by alanking** [comment]
The approach we have for fixing the extract operation uses libarchive to iterate over the structured file and register its contents in the catalog rather than pulling the entire file into memory and reading it in that way. See [libarchive documentation](https://github.com/libarchive/libarchive/wiki/Examples) for examples. This includes a hard-coded value of 1MB for the "block size" in the structfile resource plugin. Here I will provide some justification for our decision using benchmark test results. Notes about the test:
1. Used a RAM disk for the unixfilesystem resource vault
2. Figures are approximate
3. `unzip` took ~44 seconds to extract the contents of the file, for comparison

block size (KB) | 4 | 8 | 16 | 32 | 64 | 128 | 256 | 512 | 1024
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
ibun -x time (sec) | ~129 | ~79 | ~54 | ~43 | ~36 | ~34 | ~32 | ~31 | ~30

![image](https://user-images.githubusercontent.com/8021100/64458012-33096f80-d0c2-11e9-909c-becd4eb6e262.png)

The data show a significant initial performance gain as block size increases from 4KB with the effect tapering off as the value increases. This is because the number of iterations needed to read the file decreases as the block size increases.

**Comment by PaulVanSchayck** [comment]
Would this also help for issue #4118?

**Comment by trel** [comment]
This issue was due to crossing an arbitrary 4GB threshold defined by using an integer and not iterating over blocks of the zip file in question.  The files in #4118 are much bigger, so ... it's probably not exactly the same problem.  We'll investigate there as well.

**Comment by alanking** [comment]
I was able to demonstrate that the linked code changes also fix the problem described in #4118.

**Comment by PaulVanSchayck** [comment]
Thanks Alan. The issues sounded so similar that I thought there must be overlap.

**Comment by alanking** [comment]
Test needs to copy a different directory as CI runs out of `/var/lib/irods/scripts`
