### ISSUE TITLE
CMake in master should depend on  spdlog 1.5.0, not 0.17.0 

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#4810]
- [x] master
----

## Bug Report
Currently irods master will not build on a system without `/opt/irods-externals/spdlog0.17.0-0` present
### iRODS Version, OS and Version
centos 7, on Docker

**Comment by d-w-moore** [comment]
Probably only a change to the version number in `CMakeLists.txt` is required
```
CMakeLists.txt:38:IRODS_MACRO_CHECK_DEPENDENCY_SET_FULLPATH_ADD_TO_IRODS_PACKAGE_DEPENDENCIES_LIST(SPDLOG spdlog0.17.0-0)
```

**Comment by sprinkjm** [comment]
Thanks for this thread. I did a pull from https://github.com/irods/externals in order to do a build on raspberry pi earlier this week and the challenge I faced was that the versions.json pulled the wrong version, and then the irods main compile did not build. There were a few changes in CMakeLists.txt that I also made to make the compile work, as the include structure did not match the CMakeLists.txt spec.

I see that there was a commit made 4/21—but my compile lasted about 20 hours, so I am not enthusiastic to try it now that I was successful with the below. I apologize that some of these are fixes in files that are from externals. It would be great if the documentation could be updated to help get started in irods compile, to tell that it is the standard cmake build process (rather than depending on python scripting as does the externals).

Within versions.json of irods/externals
```
"spdlog": {
        "commitish": "v0.17.0",
        "version_string": "0.17.0",
        "license": "MIT",
        "consortium_build_number": "0",
        "externals_root": "opt/irods-externals",
        "build_steps": [
            "mkdir -p TEMPLATE_INSTALL_PREFIX/include",
            "cp -r include/spdlog TEMPLATE_INSTALL_PREFIX/include"
            ],
        "external_build_steps": [
            "ls -l TEMPLATE_INSTALL_PREFIX/../* ; cp -rf TEMPLATE_INSTALL_PREFIX/../* ../../ ; ls -l ../../"
        ],
        "fpm_directories": ["include"]
    },
```

And in CMakeLists.txt of irods, add the include/spdlog line and extend parens.
```
include_directories(${IRODS_EXTERNALS_FULLPATH_CLANG}/include/c++/v1
                    ${IRODS_EXTERNALS_FULLPATH_JSON}/include
                    ${IRODS_EXTERNALS_FULLPATH_SPDLOG}/include
                    ${IRODS_EXTERNALS_FULLPATH_SPDLOG}/include/spdlog)
```

**Comment by trel** [comment]
Hi @sprinkjm - the 4-2-stable branch of the irods/externals repository is what you should be building to produce packages usable for the upcoming 4.2.8 release (aka from the 4-2-stable branch of the irods/irods repository)

We've moved/bumped a lot of the externals for the 4.2.8 release... so if you are trying to build externals for iRODS 4.2.7, you should checkout the 4.2.7 tag of the irods/externals repository.

**Comment by sprinkjm** [comment]
Thanks, I'm less concerned with having the most up-to-date version as I am with having icommands running on my raspberry pi to allow automated uploading. I was following the instructions from irods-client-icommands, so if that documentation can point folks to the stable release it would no doubt be helpful.

**Comment by sprinkjm** [comment]
I was able to complete the build and execute successfully on an rpi, thanks for directing me to that branch. It was a bit disconcerting that the 4-2-stable branch builds a version numbered 4.3.0. After a marathon compile to see that the version number is the same as the one I built but knew was faulty led to a little heartburn. :)

**Comment by trel** [comment]
Glad it’s working.    You should not see 4.3.0 except on the master branch.

**Comment by sprinkjm** [comment]
I thought the same, perhaps there is an error in how I am accessing the branch. My workflow from Dockerfile below. I'm possibly just misunderstanding how git repos are handled, I'm old enough for several different RCS than git, and typically had a dev repo that was separate from the one pointed to in the documentation, which was merged after the release candidate was approved. It may be the workflow should be different and I've just not been git-ing actively produced projects :)
```
RUN git clone https://github.com/irods/irods /irods-4-2-stable
RUN cd /irods-4-2-stable && git branch remotes/origin/4-2-stable && \
    git submodule update --init

RUN mkdir -p /irods-4-2-stable/build && cd /irods-4-2-stable/build && cmake ..
RUN cd /irods-4-2-stable/build && make 
RUN cd /irods-4-2-stable/build && cpack
```

**Comment by trel** [comment]
When you `git clone` - by default you’re on the master branch.  You would need to `git  checkout 4-2-stable` from inside the new repo that you cloned.
