### ISSUE TITLE
iadmin lr returns stale information: resc_objcount

### ISSUE THREAD

**Issue by bh9** [irods/irods#5099]
- [x] master
- [x] 4-2-stable
------

### iRODS Version, OS and Version
4.2.7 Ubuntu 18.04

### What did you try to do?
We drained a resource to retire it, then tried to confirm it was empty. 
We tried 3 different approaches:
1. `iquest "SELECT DATA_ID WHERE DATA_RESC__ID = '218587968'"`
2. I compared the outputs of `iscan -r /irods-seq-sr01-ddn-re12d-14-to-19` and `find /irods-seq-sr01-ddn-re12d-14-to-19/ -type f` 
3. `iadmin lr irods-seq-sr01-ddn-re12d-14-to-19 | grep resc_objcount`

### Expected behavior
1. `iquest "SELECT DATA_ID WHERE DATA_RESC__ID = '218587968'"` returns CAT_NO_ROWS_FOUND
2. The files in `iscan -r /irods-seq-sr01-ddn-re12d-14-to-19` and `find /irods-seq-sr01-ddn-re12d-14-to-19/ -type f` should match
3. `iadmin lr irods-seq-sr01-ddn-re12d-14-to-19 | grep resc_objcount` should produce no output since resc_objcount is now a stale column

### Observed behavior (including steps to reproduce, if applicable)
1.  `iquest "SELECT DATA_ID WHERE DATA_RESC__ID = '218587968'"` returned CAT_NO_ROWS_FOUND ✔️ 
2. I compared the outputs of `iscan -r /irods-seq-sr01-ddn-re12d-14-to-19` and `find /irods-seq-sr01-ddn-re12d-14-to-19/ -type f`, to confirm that every file in the resource was unregistered ✔️ 
3. `iadmin lr irods-seq-sr01-ddn-re12d-14-to-19 | grep resc_objcount` said there were still 155 data objects on the resource (it was mostly drained before the upgrade, so this is likely the number at the time of the upgrade) 🟥 

There are no objects on the resource in the database, but yet `iadmin lr` still reports there are, because it's reading a stale column from the database

**Comment by trel** [comment]
So, the bug is that the database has stale information in it?

Or that `iadmin lr` still prints out that column?

Upon local testing, a non-zero value does not prevent the removal of the resource from the catalog:
```
$ iadmin lr testresc | grep resc_objcount
resc_objcount: 42
$ iadmin rmresc testresc
remote addresses: 127.0.1.1 ERROR: rcGeneralAdmin failed with error -835000 CAT_RESOURCE_NOT_EMPTY 
Level 0: resource 'testresc' contains one or more dataObjects
$ irm -f foo
$ iadmin rmresc testresc
$ echo $?
0
$
```

I believe your first two approaches to verify resource emptiness are sufficient.

The third approach adds no information as, like you say, the `resc_objcount` column is stale and iRODS code does not have any logic that pays attention to that value anymore (since 4.2.0?).




If the bug is that the database has stale information in it... then the remedy would be to run some `UPDATE` sql that sets it to zero for all resources?    We defaulted to not removing information from the catalog that isn't harmful.   If that column continuing to have stale information is harmful/confusing/dangerous, we can discuss a good 'fix'.

For your own Zone, it is definitely sufficient to zero it out for all your resources.

**Comment by bh9** [comment]
>Or that iadmin lr still prints out that column?  

This one. Given that the client is 4.2.7, I would expect it not to provide columns which are known to be stale in 4.2.7, so the fact that it output `resc_objcount` at all seems wrong (unless it went away and calculated the correct value somehow)

**Comment by trel** [comment]
right, okay - that's easy enough.

`ilsresc` already does not print out that information.
