### ISSUE TITLE
istream does not mark sibling replicas stale on update

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#5187]
- [x] master
- [x] 4-2-stable
---
## Bug Report
Given two or more replicas, using `istream` to modify the contents of one replica does not cause the sibling replicas to be marked as stale.

### Example
The following operations should cause replica 0 to be stale.
```bash
$ ils -l
/tempZone/home/rods:
  rods              0 demoResc          224 2020-10-12.12:39 & bar
  rods              1 resc0          224 2020-10-12.12:40 & bar
$ echo 'NEW DATA' | istream write -n1 bar
$ ils -l
/tempZone/home/rods:
  rods              0 demoResc          224 2020-10-12.12:39 & bar
  rods              1 resc0            9 2020-10-12.12:44 & bar
```

**Comment by alanking** [comment]
After a discussion, we have decided that this behavior should not be allowed at all. Using `iput` as an example, the user should see a message related to creating a replica on a new/different resource for an existing data object not being allowed.

This action should only be allowed via replication, phymv, or registration in the catalog, each of which should undergo a verification step to ensure that the data is consistent with any sibling replicas marked good.

**Comment by alanking** [comment]
After even more discussion, it has been decided that `istream` should in fact be allowed to create new replicas. However, all sibling replicas will become stale after closing because the stream may have moved the truth.

So, in summary, `istream` writing to any replica of a data object, whether new or overwrite, will result in all sibling replicas being stale.

**Comment by trel** [comment]
checkboxed
