### ISSUE TITLE
Need a way to drain processes on a resource server non-disruptively

### ISSUE THREAD

**Issue by bh9** [irods/irods#5188]
## Feature
Occasionally, irods will need restarting. For us this time, the issue is that we're exhausting the number of file descriptors irods is given by systemd (1024), so we need to restart the service on all of our resource servers. To do this non-distruptively, we need to prevent new processes from being started on a server without affecting any of the existing processes.  There are a few approaches we thought might work, but testing has established they don't:
### 1. Restart the irods service
This used to stop the server, but let any existing processes finish. That behaviour changed in 4.2(?) so this now interrupts all existing processes
### 2. Mark the resource down with `iadmin modresc <resc> status down`
This also interrupts all existing processes
### 3. Pause the server with `irods-grid pause --hosts=<host>`
This does have the effect of not interrupting existing processes, but doesn't stop new `iget`s from targetting replicas on the paused resource, which end up just hanging until they either timeout or the server is unpaused  
  
  
Are we missing an approach, or is this not currently possible. If the latter, could we have a way to do this please?

**Comment by trel** [comment]
hmmm, option 1 should have a timeout associated with it...

Ah, yes, a default of 20 seconds...

https://github.com/irods/irods/blob/328c86782ea0f21a9b0c4cc4a9448b658e6e8b97/scripts/irods/controller.py#L145-L153

which calls

https://github.com/irods/irods/blob/328c86782ea0f21a9b0c4cc4a9448b658e6e8b97/scripts/irods/controller.py#L125-L136

So, we need a better way to plumb the timeout through from above?

**Comment by trel** [comment]
As a follow up - here's the plumbed version of `shutdown`:

```
irods-grid shutdown --wait-forever --hosts=<fqdn1>
```

This will wait for all existing connections to complete and then stop the server.

Coupled with a following `irodsctl start` on that host, I think this should cleanly do what you're asking for.

**Comment by bh9** [comment]
A bit of testing this morning:
```
irods-grid shutdown --wait-forever --hosts=<fqdn1>
```
will perform an immediate shutdown if it receives no reply in 10s, not the failure mode I would expect
```
irods-dev@irods-seq-dev-ies1:~$ time irods-grid shutdown --wait-forever --hosts=irods-g2-dev.internal.sanger.ac.uk
{
    "hosts": [
        {
            "response_message_is_empty_from": "tcp://irods-g2-dev.internal.sanger.ac.uk:1248"
        }
    ]
}

real    0m10.317s
user    0m0.013s
sys     0m0.000s
```
Even if it does receive a response, attempts to iget objects with a replica on that host get Connection Refused, presumably because the resource isn't marked down so the replica on the now shutdown host is still targetted. This makes this approach also disruptive

**Comment by trel** [comment]
First, you would like any new incoming requests to the system to route somewhere else - the iRODS protocol handles this through the voting mechanism (marking things down or with weights so that this particular resource/replica votes lower than its sibling replicas).  It does not have a means to say 'no, go somewhere else' *after* the decision to route (voting) has been made.

Second, you would like the server that is going down to service existing connections, and accept no new connections on the way down.  This appears to be working as designed (except for the 10s timeout, we can look into that and make it better / configurable).

So...

A fourth option in your list could be a combination of having both a passthrough weight reads and/or writes at 0 *and* using `irods-grid shutdown --wait-forever`.  This may behave better than your option 2 (marking the resource down), but I'm not sure.  I'm surprised that marking the resource down would interrupt existing connections.  That could be a real bug (rather than intended behavior) and need to be addressed separately.

**Comment by bh9** [comment]
From talking to John, and then some testing: `iadmin modresc <resource> status down` does not interrupt running processes as of 4.2.X, but did in 4.1.12, so we do have a way, thanks

**Comment by trel** [comment]
Hooray!
