### ISSUE TITLE
rcDataObjRead should verify offset is not past end of file (size in the catalog)

### ISSUE THREAD

**Issue by kript** [irods/irods#5352]
- [x] master
- [x] 4-2-stable
-----------

### iRODS Version, OS and Version

4.2.7
Ubuntu 18.04

### What did you try to do?

Read a file using samtools/htslib which under the hood uses `rcDataObjLseek`.
The file is marked zero length, but actually contains data on disk, due to past issues.

### Expected behavior

a zero length file is provided as that is the size held in the catalog.

### Observed behavior (including steps to reproduce, if applicable)

The underlying file is read and passed through to the samtools program.
This actually worked out for us, but I thought I'd raise it in case its an unintended consequence...

**Comment by kript** [comment]
Not that I expect you to look at samtools/htslib, but in case; https://github.com/samtools/htslib

**Comment by trel** [comment]
We think the use case that suggests it needs to be possible (and not verify catalog size) is if a data_object is opened with `O_RDRW`...

A `0`-length data_object could be opened, and then `rcDataObjLseek` `50` bytes, and then written (which seems fine, regardless)... or read (which seems... possibly problematic as you mention), but that's what POSIX allows.  It's up to the user to hold things correctly.

If this is a security argument, then we'd like to hear more use cases / scenarios... but for now, I think this is working as intended.

**Comment by trel** [comment]
@kript @korydraughn  any further thoughts?    i don't know that there's anything actionable here at this time.

**Comment by korydraughn** [comment]
I agree with your previous statement. I don't think there is anything actionable here. Also, changing how seek works could negatively affect the parallel transfer engine.

**Comment by kript** [comment]
As with other tools, though, if the catalog says the file size is zero, 0 bytes are what should be passed back?
If the user attempts to seek past the 'end' of the file on a filesystem they would get an error, and I would presume the same here?

**Comment by trel** [comment]
But... that's not true?

```
The lseek() function allows the file offset to be set beyond the end of the file (but this does not change the size of the file). If data is later written at this point, subsequent reads of the data in the gap (a "hole") return null bytes (aq\0aq) until data is actually written into the gap.
```

**Comment by kjsanger** [comment]
I think @trel is correct and I would expect to be able to seek beyond the end of the file. But I wouldn't expect to be able to read data from there.

https://linux.die.net/man/2/read: 

> If the current file offset is at or past the end of file, no bytes are read, and read() returns zero.

**Comment by trel** [comment]
Ah, very good.

We will make sure we have a test for this use case of 'read after seek/offset past the end of file'.

**Comment by korydraughn** [comment]
We get this for free if the replica's size on disk matches what is in the catalog. If the replica's size on disk is greater than what is in the catalog, then the server has to gather the information (file position, size in catalog, size on disk) so that it knows how to proceed.

The simple solution is to check this in `rsDataObjRead`, but that means all read operations pay the cost of doing this.

An alternative is to capture some of this information in `rsDataObjOpen`. The problem with relying on open is keeping things in sync. What if the client is operating on the same replica using multiple threads?

A third way to handle this is to make `rsDataObjLseek` operate based on how the replica was opened. If the replica was opened using `O_RDONLY`, then lseek never exceeds the size in the catalog. For all other open modes, lseek is allowed to seek past the end of the replica.

**Comment by korydraughn** [comment]
I feel the third solution is the best way to handle this.

Are there other ways to accomplish this?

**Comment by trel** [comment]
The third sounds reasonable and the most POSIX-behaviorish.    So no changes to `rcDataObjRead` itself then?

**Comment by trel** [comment]
Seems good.

**Comment by trel** [comment]
checkboxed.
