### ISSUE TITLE
Object remains in intermediate state when close operation returns an error.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods#5495]
- [x] master
- [x] 4-2-stable
---------
## Bug Report

When the close operation from a resource plugin returns an error, the object is left in an intermediate state.  After this happens the object can't be overwritten without first doing a force removal.

I believe it should be in a fail or stale state in this scenario.

### iRODS Version

4.2.9 (4-2-stable)

**Comment by alanking** [comment]
This is likely due to a missed error case somewhere in close. I've covered everything I could find in `rsDataObjOpen` and `rsDataObjClose` to ensure that data objects are unlocked (and the target replica set to the appropriate state) for all code paths. I will also need to double-check `replica_close` for streaming cases. I will link against this issue in the upcoming write-lock implementation.

**Comment by alanking** [comment]
Cannot checkbox, but I think this can be closed.
