### ISSUE TITLE
imeta fails when reading commands with quoted arguments from a pipe

### ISSUE THREAD

**Issue by tedgin** [irods/irods#5518]
### iRODS Version, OS and Version
iRODS 4.2.8, CentOS 7 and Ubuntu 20.04

### What did you try to do?
I have a file with multiple imeta commands in it. Since the object names and attribute names, values, and units may all of white space in them, these are quoted in the file. When I pipe the contents of this file to imeta, imeta generates an error saying that too many positional arguments were provided. In iRODS 4.1.10, this works.

Here's an example file named `file1`.

```
adda -d "/cyverse/home/tedgin/SPARCd/assoc-array-inc.sh" "a1" "v1" "u1"

```

The command that fails is `cat file1 | imeta`. 

### Expected behavior

I expect that the data object `/cyverse/home/tedgin/SPARCd/assoc-array-inc.sh` would have the AVU triple <`a1`, `v1`, `u1`> attached to it.

### Observed behavior (including steps to reproduce, if applicable)

```
-bash-4.2$ cat file1 | imeta
imeta>
Error: too many positional options have been specified on the command line

```

**Comment by d-w-moore** [comment]
As we say, "found a parser"....
On a little bit of investigation, `getInput` is adding an extra parameter when the final one (the AVU units in this case) is quoted, for a total of 7 rather than six.  Probably won't be difficult to fix.  On the other hand, Bash has always been more reliable input string separator than any homebrew concoction, So the following script excerpt is an example of how to spool imeta input from a TSV (tab separated values) file allowing also empty and commented('#') lines:
```
cat inputfile | while IFS=$'\t' read -a arr ; do
   [ ${arr:0:1} = '#' -o  ${#arr[@]} = 0 ] || imeta "${arr[@]}"
done
```
