### ISSUE TITLE
Setting to output debug logs only in rodsLog

### ISSUE THREAD

**Issue by tk9320** [irods/irods#5523]
iRODS ver = 4.2.6

I set `irods_log_level = 7` in `irods_environment.json` to output debug logs in rodsLog*.
Then, ils command result is as below.

> [rods@host ~]$ ils
> DEBUG: irods_authentication_file is not defined
> DEBUG: irods_ssl_ca_certificate_path is not defined
> DEBUG: irods_ssl_ca_certificate_file is not defined
> DEBUG: irods_ssl_verify_server is not defined
> DEBUG: irods_ssl_certificate_chain_file is not defined
> DEBUG: irods_ssl_certificate_key_file is not defined
> _(omitted)_
> /ZONEname/home/rods:
>   test.txt
>   C- /ZONEname/home/rods/sample
> _(omitted)_
> DEBUG: irods_ssl_certificate_chain_file is not defined
> DEBUG: irods_ssl_certificate_key_file is not defined
> DEBUG: irods_ssl_dh_params_file is not defined
> DEBUG: irods_connection_pool_refresh_time_in_seconds is not defined
> DEBUG: irods_plugins_home is not defined

I would like to be output debug information only in rodsLog*.
Should I edit any setting?

**Comment by alanking** [comment]
This is actually setting the "log level" for the client, which is why you are seeing these outputs on your console. If you set the `irods_log_level` in the `irods_environment.json`, as you've done, on the *service account* for the iRODS server, you will enable the debug logging both in the console and in the server log.

For your desired behavior, you should set `spLogLevel` environment variable to the desired log level with a command like:
```bash
$ export spLogLevel=7
```
And the server must be restarted in order for the log level to take effect.

See https://docs.irods.org/4.2.8/system_overview/troubleshooting/ for more information.

**Comment by trel** [comment]
I think this is answered - closing.
