### ISSUE TITLE
PAM authentication faild in icommands during long connection

### ISSUE THREAD

**Issue by a-tsygan** [irods/irods#5753]
## Bug Report
iRODS v. 4.2.8

One of our clients was testing of multiple files upload via command line interface script. 
after doing iinit once using PAM authentication the process was started.
After some hours user got back failed PAM authentication error.
 failed with error -840000 CAT_PASSWORD_EXPIRED 

We suspect that in this case the following problem happens:
during initial connection temporary PAM account is set 
then during operations PAM account lifetime ends and in scope of the given iinit operations is no longer possible. 
(it was around 5Tb copy)
The workaround for the user was to do init per file which is sub optimal. 

We saw similar problem in Java using Jargon. 

Other users complain about disconnects during big file uploads via WebDav an in Cyberduck.
Cyberduck returnes: java.io.IOException: read length is set to zero
(this one we saw as well in our java code when long running session got broken) 

I suspect that all this due to the limited lifetime of the temp PAM account. in scope of connection temporary PAM account should be reinitialized automatically if it is not valid anymore and if username/password combination is correct in scope of the session. Or such temporary account should not be invalidated is initial connection is still working.  Or we need a parameter that sets lifetime of such account for custom time directly in server configuration

**Comment by trel** [comment]
perhaps related to #5096, #4198, #3742

**Comment by alanking** [comment]
I don't think we have a test for this situation, but this may be fixed in 4.3.1. See https://github.com/irods/irods/issues/7274

**Comment by alanking** [comment]
After some more investigation, we think this is the expected behavior. If the user needs more time on the time-limited password, `iinit` provides the `--ttl` option to specify a number of hours for the password to be valid.

4.3.1 also expanded configuration around password lifetimes in the server to correct a few known issues. See documentation here: https://docs.irods.org/4.3.1/system_overview/configuration/#authentication-configuration

We are going to close this as resolved. @a-tsygan - Please open a new issue with a reproducible case if you think this issue still exists. Thanks!
