### ISSUE TITLE
write ticket for collection does not allow upload of new data objects

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#5913]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
### iRODS Version, OS and Version

iRODS 4.2.10, Ubuntu 18

### What did you try to do?

As user alice, create a new object with `iput`, with a write ticket to the parent collection enabled.

### Expected behavior
Assuming that write tickets are intended to provide a dropbox-style upload functionality, then - giving user `alice` a write ticket to a collection - it is expected then that she would be able to use that ticket to create and write to (in effect, upload) a new data object in that collection.

### Observed behavior (including steps to reproduce, if applicable)
as rods (rodsadmin):
```
irods:~$ imkdir /tempZone/home/rods/test_write
irods:~$ iticket create write /tempZone/home/rods/test_write
ticket:6pBAw34U5g6HUFx
```

as alice (rodsuser):
```
~$ echo 'from: alice' > ALICE_abc.dat
~$ iput -t 6pBAw34U5g6HUFx ALICE_abc.dat /tempZone/home/rods/test_write/abc.dat
remote addresses: 127.0.0.1 ERROR: putUtil: put error for /tempZone/home/rods/test_write/abc.dat, status = -808000 status = -808000  CAT_NO_ROWS_FOUND
```

This is produced in the rodsLog:
```
Oct 13 13:48:31 pid:11541 NOTICE: session ticket setup, value: 6pBAw34U5g6HUFx
Oct 13 13:48:31 pid:11541 remote addresses: 127.0.0.1 ERROR: failed to determine collection name for object id [10096]
Oct 13 13:48:31 pid:11541 remote addresses: 127.0.0.1 ERROR: [-]        /irods/server/api/src/rsRegDataObj.cpp:85:int _rsRegDataObj(rsComm_t *, dataObjInfo_t *) :  status [CAT_NO_ROWS_FOUND]  errno [] -- message [_rsRegDataObj - Failed to register data object "/tempZone/home/rods/test_write/abc.dat" - CAT_NO_ROWS_FOUND ]

Oct 13 13:48:31 pid:11541 remote addresses: 127.0.0.1 ERROR: filePathReg: svrRegDataObj for /tempZone/home/rods/test_write/abc.dat failed, status = -808000
Oct 13 13:48:31 pid:11541 remote addresses: 127.0.0.1 ERROR: [create_new_replica:334] - failed in rsPhyPathReg [error_code=[-808000], path=[/tempZone/home/rods/test_write/abc.dat], hierarchy=[demoResc]

```
---
If now the `rods` admin creates the `/tempZone/home/rods/test_write/abc.dat` data object with contents `from: rods`, 
we can now - as `alice` - list, read, and overwrite it as  alice , as you would expect :
```
~:$ ils  -t 6pBAw34U5g6HUFx  /tempZone/home/rods/test_write
/tempZone/home/rods/test_write:
  abc.dat
~:$ iget  -t 6pBAw34U5g6HUFx  /tempZone/home/rods/test_write/abc.dat -
from: rods
~:$ iput  -f -t 6pBAw34U5g6HUFx ALICE_abc.dat  /tempZone/home/rods/test_write/abc.dat -
~:$  iget  -t 6pBAw34U5g6HUFx  /tempZone/home/rods/test_write/abc.dat -
from: alice
```

**Comment by d-w-moore** [comment]
I did try that and as I remember it didn't make a difference. But, will repeat to make sure.

**Comment by w-bonelli** [comment]
Is there a way to grant temporary write permissions to an anonymous iRODS user in the meantime? If not, (maybe this is out of scope for this repo, sorry..) is there a way to do the same more generally with respect to CyVerse users, e.g. with Terrain?

I have a service that submits jobs to clusters on behalf of CyVerse users. Currently it runs a background task to periodically refresh Terrain access tokens for users with open job submissions, ask cluster scheduler for job status, transfer data (via Terrain) after completion, and so on. This works ok, but it means units of work (e.g., pull some files from the Data Store, do something with them, push results back) can't be packaged into a single job script, fired and forgotten &mdash; jobs might sit in a scheduler queue arbitrarily long, so an access token may no longer be valid by the time it's needed. A use-dependent rather than time-dependent method for temporary, limited access to the Data Store would really help by obviating the need to manually orchestrate data transfers separately from jobs (unless I'm missing some simpler way to achieve the above).

Thanks again for all the help [here](https://github.com/irods/python-irodsclient/issues/327).

**Comment by d-w-moore** [comment]
Until write tickets are fixed, it might be possible to create a microservice that "routes" (moves) data objects from a landing-zone collection of sorts, to their proper place (among a whitelist of choices).

**Comment by w-bonelli** [comment]
Thanks @d-w-moore, I will look into it.

For now getting by with Terrain's share/unshare, to temporarily grant access and revoke it after jobs complete

**Comment by d-w-moore** [comment]
This worked in 4.2.6, but not 4.2.7 .  see this commit: 6ed2c6fd3e3ad6ce70e57371c8952e8ff4aab976

**Comment by d-w-moore** [comment]
To clarify ... in 4.2.6, using iput and specifying (via the `-t ticketstring` option) a write ticket on coll  `A`  : 
   1.  may be used to force-overwrite an existing data object directly in that collection
   2.  may be used to create a new data object (of whatever name) directly in that collection
   3.  may **not** be used to write into data objects within `A`'s subcollections (whether pre-existing or not)

What the above [commit]( https://github.com/irods/irods/commit/6ed2c6fd3e3ad6ce70e57371c8952e8ff4aab976 ) loses us in the above list is the second (2) capability.

**Comment by korydraughn** [comment]
> 1. may be used to force-overwrite an existing data object directly in that collection
> 2. may be used to create a new data object (of whatever name) directly in that collection
> 3. may not be used to write into data objects within A's subcollections (whether pre-existing or not)

I've verified that recent commits against this issue restore/satisfy all items.
