### ISSUE TITLE
itrim seems not work

### ISSUE THREAD

**Issue by yr-wang-hit** [irods/irods#6041]
irods version4.2.8 
we have a fairly simple resource tree like that(zone name is zone1):

```
rootResc(passth)
    -- rrResc(Random)
        --AResc(UnixFileSystem)
        --BResc(UnixFileSystem)
```

We want to decommission storage on AResc, As the tutorial , the command seems something like :
```
$ iadmin rmchildfromresc rrResc AResc 
$ itrim -M -r -S AResc /zone1
$ iadmin rmresc AResc
```

But the itrim is not work, It cannot delete any data object located on /zone1.
I turned on the -V option, found that it really traversed the data object tree, but
get the conclusion that there is no data object to trim. I wonder if there is some 
default options such like(-N, -n, or something else) to turn? But it seems confusing to
deal with that by hand.

Thanks a lot!

**Comment by d-w-moore** [comment]
@yr-wang-hit  If the -V output indicates the object was traversed but not trimmed, it's most likely that only two replicas of the data object existed and (as you suspected) you did not specify `-N 1`.  **-N** will be needed in such a case, because by default, itrim does not like leaving fewer than two replicas on the system (for redudancy's, ie, safety's sake).

**Comment by yr-wang-hit** [comment]
Thanks @d-w-moore 

But imagine the situation that the only copy is on the AResc. I want to delete all the data objects on 
AResc although it can cause data loss. If there is a solution(-N 0 seems not work)? the -N option has
been deprecated, why is the case?

Another advice is if the (logical)collection_object can have a flag indicating that all the data objects under the 
collection located in the same physical resource path, So traveresing/deleting a dictionary can be accelerated.

**Comment by d-w-moore** [comment]
@yr-wang-hit So if I understand correctly, for the data objects having only a replica on AResc and no others, you don't mind that data being lost? That's a use case that I wouldn't have expected, but it could be satisfied with a combination of itrim, iquest and irm commands.

**Comment by trel** [comment]
Confirmed, it is by design that `itrim` cannot 'trim to zero replicas'... as that is the definition of `irm`.

The `itrim -N` option is deprecated because it would trim 'down to' that number of replicas, which was non-deterministic and dependent on how many items were already in the catalog.  Trimming will soon only trim one replica at a time.  If more than that is needed, then multiple trim operations will need to be programmed/scheduled/executed.

**Comment by yr-wang-hit** [comment]
Thanks @trel
