### ISSUE TITLE
Resource redirect is wrong if resource hostname contains current hostname as substring 

### ISSUE THREAD

**Issue by peterverraedt** [irods/irods#6070]
- [ ] main
- [ ] 4-2-stable
---
### iRODS Version, OS and Version

* IRODS 4.2.10

### What did you try to do?

We have the following setup:

* `irods.example.com` is the hostname/fqdn of the irods entrypoint (load balanced solution in multiple containers, but that doesn't matter for the bug)
* `resource-X.irods.example.com` as hostnames for our resource servers (with a custom load balancer in front, but again, that doesn't matter for the bug).
* Some replicated unixfilesystem resource that reside on `resource-X`, containing a file `some.tar`.

### Expected behavior

All commands work, including `ibun`.

### Observed behavior

The normal operations as `iput`, `iget`, `ils`, ... work, but `ibun -x some.tar` fails with a UNIX_FILE_MKDIR_ERR, see <https://groups.google.com/g/irod-chat/c/6aispOGidvc>. 
This is because the `ibun` operation is handled on the irods entrypoint server and is not redirected to the irods resource server.

The actual bug is because <https://github.com/irods/irods/blob/master/server/core/src/irods_resource_redirect.cpp#L478-L492>, which is run on `irods.example.com`, determines that the file is local, because the resource server name `resource-X.irods.example.com` has `irods.example.com` as substring.

**Comment by trel** [comment]
Good find - thank you.

Yes, this looks very similar to, but probably different from https://github.com/irods/irods/issues/5410.

**Comment by korydraughn** [comment]
I haven't been able to reproduce this.

Can you provide a script that triggers this error?

**Comment by korydraughn** [comment]
needs checkboxes for main and 4-2-stable.

**Comment by alanking** [comment]
Should we mark 4-2-stable as done?

**Comment by korydraughn** [comment]
Not yet. I still need to reproduce the issue. Once we can reproduce it, I'll circle back and check the box.

**Comment by korydraughn** [comment]
We've reproduced the issue using 4.2.10 and verified that the commits against this issue resolve it.

We had to manually test this scenario because our test environment does not allow us to automate it. For that reason, I'll list the steps we used to reproduce it here.
### 1. Create a topology with 3 servers and 1 client.
  - The client should only have icommands installed.
  - 2 of the servers are consumers.
    - 1 server with a hostname of `irods-consumer` *(this is the server the client is configured to connect to)*.
    - 1 server with a hostname of `resource.irods-consumer`.
  - The last server will be the provider.
### 2. Create a unixfilesystem resource on `resource.irods-consumer` using the following steps:
  1. `mkdir /ufs_vault`
  2. As the iRODS service account, run `iadmin mkresc ufs unixfilesystem resource.irods-consumer:/ufs_vault`
  3. `chown irods:irods /ufs_vault`
### 3. As the client, do the following:
  1. `touch foo`
  2. `tar -cf archive.tar foo`
  3. `iput -R ufs archive.tar`
  4. `ibun -x archive.tar` *(this will trigger the failure)*
