### ISSUE TITLE
Creation of 64 byte user names is allowed, even though they cause issues

### ISSUE THREAD

**Issue by stsnel** [irods/irods#6091]
- [x] main
- [x] 4-2-stable
---
### iRODS Version, OS and Version

Reproduced on Ubuntu 18.04; iRODS 4.2.7, as well as 4.2.11.

### What did you try to do?

Create a user with a 64 byte name.

### Expected behavior

If I can create a user with a 64 byte name, then such names should be supported by iRODS/iCommands.

### Observed behavior (including steps to reproduce, if applicable)

```
vagrant@provider:~$ iadmin mkuser "thisisquitealongusername64charactersfillerfillerfillerfillerfil" rodsuser
vagrant@provider:~$ ils /testZone/home/thisisquitealongusername64charactersfillerfillerfillerfillerfil
remote addresses: 10.0.2.15 ERROR: unpackNonpointerItem: strlen of ownerName > dim size, content: thisisquitealongusername64charactersfillerfillerfillerfillerfil 
remote addresses: 10.0.2.15 ERROR: readAndProcApiReply:unpack_struct error. status = -308000 status = -308000 USER_PACKSTRUCT_INPUT_ERR
terminating with uncaught exception of type irods::experimental::filesystem::filesystem_error: cannot get status: Unknown error -308000
Aborted (core dumped)
```

It seems that rsGeneralAdmin also permits 64 byte user names.

**Comment by trel** [comment]
Hrm, so this is either a bug that we allow it to be that long since the protocol can't handle it... or... we have a bug in the implementation of using the boundary case.    Thanks for the report!

Does a username with length 63 work fine?

**Comment by stsnel** [comment]
As far as I can tell, the issue only occurs when a name is exactly 64 bytes long (names of 65 bytes are rejected by iadmin; 63 byte owner names don't cause the exception issue in ils)

**Comment by trel** [comment]
Got it.   We'll box it in.

**Comment by korydraughn** [comment]
I've reproduced this issue using main/4.3.

This error is produced when the client attempts to unpack the response.
https://github.com/irods/irods/blob/ed6328646cee87182098d569919004049bf4ce21/lib/core/src/packStruct.cpp#L2110-L2117

The server does not experience any error other than the one caused by a dirty disconnect. I'm not sure why the code considers this an error. For my test, I created a user with 63 byte long name. `myStrlen` reflects this and is 63 while `maxStrLen` is 64. It feels like L2110 is incorrect. Perhaps, `>=` should be replaced by `>` or the `+ 1` should be removed.

Tip of main does not allow 64 byte usernames. I believe 4.2.11 guards against 64 byte usernames as well.

**Comment by korydraughn** [comment]
I'm thinking the `+ 1` is incorrect based on the fact that `strlen` does not count the null terminator byte and `myStrlen + 1` does not make sense if the `+ 1` doesn't represent the null terminator byte.

**Comment by trel** [comment]
Yes, please let's get rid of all `+ 1`'s in the code without explicit comment for why they are required.

**Comment by korydraughn** [comment]
needs checkboxes for main and 4-2-stable.

4-2-stable checkbox should be checked.
