### ISSUE TITLE
Fix non-package installations for 4.3.1

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6284]
- [x] main
- [x] 4-3-stable
---
The following things need to be verified/updated for non-package installations:
- [x] `docs.irods.org` documents the correct steps for a successful installation
- [x] Schema validation works
- [x] Servers stand up and shut down without error
- [x] icommands work
- [x] The logs capture all activity

4.2.11 documentation for reference: https://docs.irods.org/4.2.11/getting_started/installation/#non-package-install-run-in-place

**Comment by trel** [comment]
And consumers.

**Comment by SwooshyCueb** [comment]
I think the targets list in the main CMakeLists.txt will need to be updated at the very least

**Comment by korydraughn** [comment]
Can you elaborate on that a little more?

**Comment by SwooshyCueb** [comment]
https://github.com/irods/irods/blob/4087cef3caf89ba94643202729298f19f8f3bd1a/CMakeLists.txt#L310-L351

This is the list of targets that must be built before the install commands are run in the `non-package-install-*` targets. It does not include every target that would be installed by the install commands, so unless someone does `make all` or whatever the ninja equivalent is before running `make non-package-install-postgres`, CMake will throw errors due to missing files.

**Comment by korydraughn** [comment]
We've detected issues with shared library resolution.

Bumping to 4.3.1.
