### ISSUE TITLE
Client API Allowlist option does not align with description at docs.irods.org

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6295]
- [x] main
- [x] 4-2-stable
---
https://docs.irods.org/4.2.11/system_overview/configuration/ states that the default value is **enforce**. This means, even when the property does not exist in server_config.json, it should be treated as if it were explicitly set to **enforce**.

The code does not follow this.

Notice line 194. The call to `get_server_property()` can result in an exception. If it throws, the allowlist is ignored.
https://github.com/irods/irods/blob/eb361f5e49e817ff498dbb417eb935030e5b2322/server/core/src/client_api_whitelist.cpp#L188-L206

This function is called by `get_server_property()`.
https://github.com/irods/irods/blob/eb361f5e49e817ff498dbb417eb935030e5b2322/lib/core/include/irods/irods_server_properties.hpp#L65-L74

We need to update the code to match the docs or update the docs to match the code.

Based on the code, the intention seems to be that if admins want to enforce a strict client-side API, they have to say that in the config explicitly. This allows admins to opt into this without the risk of breaking the system.

The upgrade process needs to pay close attention to this property as well.

**Comment by trel** [comment]
I think the code is the correct behavior, rather than the docs, for 4.2.x... we couldn't enforce it all of a sudden and we weren't going to inject it into everyone's `server_config.json` upon initial introduction.

I think we can change the code for 4.3.0 to match the docs, and enforce it, now that it will be defined in everyone's `server_config.json` upon upgrade.

**Comment by korydraughn** [comment]
I agree.

For 4.2, the documentation needs to be updated.

For 4.3, the code needs to be updated.
