### ISSUE TITLE
Consider exposing timeout options for controlling delay server migration communication

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6370]
- [x] main
- [x] 4-3-stable
- [x] irods_docs (main only)
---
Depending on the network, admins may need to adjust the timeout values so that delay server migration operates correctly.
https://github.com/irods/irods/blob/db858d950a9efe6345f78ccb55e1f1d2f905bbf2/server/main_server/src/rodsServer.cpp#L576-L577

**Comment by alanking** [comment]
Hmm... now that I've already opened all the PRs, I have some questions... :)

There are 4 levels of granularity for the socket timeout configuration that seem consistent to me:
1. Use `server_control_plane_timeout_milliseconds` for send and receive of all internal control plane message type
2. Use one value for the main control plane configuration and one value for each additional internal control plane message type (of which there is currently one(?), delay server migration)
3. Use separate values for send and receive for the main control plane configuration which will also serve as configuration for all internal control plane message types
4. Use separate values for send and receive for the main control plane configuration as well as separate values for each additional internal control plane message type

The implementation that I put up in #6762 is none of these options. It is one configuration value for send and receive for the main control plane, and separate values for send and receive for just delay server migration communications. This feels disjointed and confusing to me.

I think options 1 and 2 are my favorites, but I also don't claim to understand what system administrators may need to configure. For reference, here is where we are using the single configuration value for the control plane to set the send and receive timeouts:
https://github.com/irods/irods/blob/2f602874739f3d0d15551127cddbac181fb88e27/server/main_server/src/main_server_control_plane.cpp#L77
https://github.com/irods/irods/blob/2f602874739f3d0d15551127cddbac181fb88e27/server/main_server/src/main_server_control_plane.cpp#L91-L92

Thoughts?

**Comment by trel** [comment]
Do we have a real/good/known use case for send and receive values needing to be different from one another?  If not, that would limit us to 1 or 2.

Since whatever we're doing (now and in the future) in a single iRODS zone is going over the same network as any thing else we're doing in that zone (as far as I know)... there is maybe no reason to have option 2?   aka it's good enough for the main server, it should be good enough for any others on the same network?   Then we are at option 1.

I can imagine different applications on a machine having per-app timeout settings... but this level of within-same-app granularity might be overkill...

**Comment by korydraughn** [comment]
It's not clear which approach is best, so I think we start with 1 (the simplest solution).

If that isn't good enough, we implement 2 and so on.

**Comment by alanking** [comment]
Sounds good. Let's go with option 1 for now, then. Thanks!

**Comment by trel** [comment]
sold.  reuse the main server values and we're good to go for now.
