### ISSUE TITLE
Investigate test_resource_types.Test_Resource_CompoundWithUnivmss with Python REP on Almalinux 8

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#6440]
- [x] main
- [x] 4-3-stable

---

The tests never complete and operations carried out by univMSSInterface.sh do not succeed. That is, resource vaults aren't created automatically on calls to `iput`, etc. `iput` hangs and never returns.

Looking inside the container created by the testing environment shows issues in /var/log/irods/irods.log. The number of processes continue to grow as well.

Observed on Almalinux 8 using the Python REP.

The tests pass when run on Almalinux 8 with the Native REP.

**Comment by alanking** [comment]
Forthcoming PR will reveal the solution, but just noting here that the issue was in the univMSSInterface script template's usage of `which`. Through an interaction with PREP or one of its dependencies on EL, the `which` command is overridden by one which picks up on functions in addition to things in the path. We have decided to replace it with `type -P` as it provides equivalent behavior without picking up on the function.
