### ISSUE TITLE
severe imkdir performance impact with inheritance enabled

### ISSUE THREAD

**Issue by davebiffuk** [irods/irods#6495]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
----------

### iRODS Version, OS and Version

4.2.7 on Ubuntu 18.04 (client and server)

### What did you try to do?

use `imkdir`

### Expected behavior

imkdir performance should not be unduly affected by the presence of inheritance.

### Observed behavior (including steps to reproduce, if applicable)

imkdir in two test areas with inheritance disabled (/Sanger1/home/dh3, /seq/home/dh3#Sanger1) is fast, taking less than 1 second.

imkdir in a test area with inheritance enabled (/seq/test/dh3) is much slower, taking more than 12 seconds. Anecdotally, this has been getting slower over time.

Disabling inheritance on the "slow" area makes the imkdir response time drop to that of the "fast" areas. Re-enabling inheritance makes imkdir go slow again. See the attached dashboard screenshot.

![image](https://user-images.githubusercontent.com/3263801/180752777-e4cd04a8-bba2-488d-b28b-facdbe4baf4f.png)

**Comment by davebiffuk** [comment]
For completeness: the permissions on those areas.
```
dh3@farm5-head1:~$ ils -A /Sanger1/home/dh3
/Sanger1/home/dh3:
        ACL - dh3#Sanger1:own   
        Inheritance - Disabled
```
```
dh3@farm5-head1:~$ ils -A /seq/home/dh3#Sanger1
/seq/home/dh3#Sanger1:
        ACL - dh3#Sanger1:own   g:dnap_ro#seq:read object   psdpipe#Sanger1:read object   srpipe#seq:own   trace#Sanger1:read object   
        Inheritance - Disabled
```
```
dh3@farm5-head1:~$ ils -A /seq/test/dh3
/seq/test/dh3:
        ACL - dh3#Sanger1:own   dj3-test#Sanger1:own   g:dnap_ro#seq:read object   irods-g1#seq:own   psdpipe#Sanger1:read object   g:public#seq:read object   rodsBoot#seq:own   srpipe#Sanger1:own   srpipe#seq:own   trace#Sanger1:read object   
        Inheritance - Enabled
```

**Comment by trel** [comment]
I would bet this is exclusively due to serially setting all the permissions on the newly created collection.

Wondering if these can be done atomically.

**Comment by kript** [comment]
Possibly related? #4547

**Comment by trel** [comment]
I don't think #4547 is related... although I suspect that if it is, it's downstream from this issue.    This issue is about being slow/serial.  That issue is presumably about returning 'too early'.

**Comment by alanking** [comment]
It looks like the collection's inherited access levels are set as part of the same transaction as the collection's creation:
https://github.com/irods/irods/blob/15fa433f9cdf0e3ab91571491d5f2b0e37e1e967/plugins/database/src/db_plugin.cpp#L4903-L4916

This is already as efficient as we can get it (probably), as it is a single `insert` from a `select`.

Maybe it has something to do with a lack of an index?
```
ICAT=# \d r_objt_access
                      Table "public.r_objt_access"
     Column     |         Type          | Collation | Nullable | Default 
----------------+-----------------------+-----------+----------+---------
 object_id      | bigint                |           | not null | 
 user_id        | bigint                |           | not null | 
 access_type_id | bigint                |           | not null | 
 create_ts      | character varying(32) |           |          | 
 modify_ts      | character varying(32) |           |          | 
Indexes:
    "idx_objt_access1" UNIQUE, btree (object_id, user_id)
```
Could be worth adding an index and see if that helps. However, if that was the answer, we would expect `ils -A` to also take ~12 seconds, so we're still a bit stumped.

**Comment by kript** [comment]
I am no DBA and do not play one on TV, so this is the table status for us;

```
                      Table "public.r_objt_access"
     Column     |         Type          | Collation | Nullable | Default
----------------+-----------------------+-----------+----------+---------
 object_id      | bigint                |           | not null |
 user_id        | bigint                |           | not null |
 access_type_id | bigint                |           | not null |
 create_ts      | character varying(32) |           |          |
 modify_ts      | character varying(32) |           |          |
Indexes:
    "idx_objt_access1" UNIQUE, btree (object_id, user_id)
    "idx_objt_access_wtsi_1" btree (object_id, user_id, access_type_id)
    "idx_objt_access_wtsi_2" btree (user_id, object_id)
```

Is there a better index we should be adding?

**Comment by trel** [comment]
Oh, so... you already have two additional custom indices...

----

Please have a grown-up DBA check why the query could be slow (line 4914 above):
```
insert into R_OBJT_ACCESS (object_id, user_id, access_type_id, create_ts, modify_ts) (select %s, user_id, access_type_id, ?, ? from R_OBJT_ACCESS where object_id = ?)
```

**Comment by DavidHarper** [comment]
In Simon's absence, I'll be playing the grown-up DBA today.  I'd like to run that query through the PostgreSQL EXPLAIN command, but I'm going to need actual parameter values, because EXPLAIN won't work on a query that has placeholders.

We have a recent snapshot of our SEQ zone database where I can run the EXPLAIN, so there's no danger of me accidentally altering any data.

**Comment by DavidHarper** [comment]
But at a first glance, the index named idx_objt_access1 would already be optimising the behaviour of the sub-select because the first column of the index is R_OBJT_ACCESS.object_id.

**Comment by trel** [comment]
Agreed - your indices appear good/great.   So now we're looking for 'so, why 12 seconds?'.


```
     cllBindVars[0] = myTime; 
     cllBindVars[1] = myTime; 
     cllBindVars[2] = collIdNum; 
```

The first two are just timestamps/epoch - so you can use 'now', will be fine.

The third is the collection_id of the parent collection (the one who's permissions are being 'cloned')...  you can get that information via iquest for any logical path...

```
$ iquest "select COLL_ID where COLL_NAME = '/seq/test/dh3'"
```

**Comment by DavidHarper** [comment]
Well, I'm a DBA, not an iRODS user, so someone else will need to run that quest command and provide me with a number, please.

**Comment by DavidHarper** [comment]
Okay, so I need to know what value currStr2 would take, so I can fill in the %s placeholder.  Suggestions, please?

**Comment by DavidHarper** [comment]
I used **select max(object_id)+1 from r_objt_access** to infer a valid value for currStr2, and current_timestamp for the two timestamp placeholders.  EXPLAIN returned this:

Insert on r_objt_access  (cost=0.70..317.61 rows=4527 width=188)
  ->  Index Only Scan using idx_objt_access_wtsi_1 on r_objt_access r_objt_access_1  (cost=0.70..317.61 rows=4527 width=188)
        Index Cond: (object_id = '1157141232'::bigint)

So it is using index  idx_objt_access_wtsi_1, which is over columns (object_id, user_id, access_type_id).  This is narrowing down the rows for closer examination to around 4527 out of ~ a billion rows.  I'd say that PostgreSQL is making a very good choice of index here.

**Comment by DavidHarper** [comment]
The performance problem is mostly likely related to the fact that this table has 2.5 billion rows, and the data and indexes occupy 190 GB and 300 GB on disk, respectively.  This is a very large table.  Re-balancing the indexes after each insert is a big operation.

**Comment by trel** [comment]
Very good - so far things are working as designed, there's just a lot of it.

Is this (2.5B rows) a case of over-indexing causing the slowdown?   Aka, if you were to remove the `idx_objt_access_wtsi_1` index... the `select`s would still be able to use `idx_objt_access1` or `idx_objt_access_wtsi_2` relatively efficiently?   Then, each insert wouldn't take as long, because less rebalancing?

**Comment by DavidHarper** [comment]
idx_objt_access_wtsi_2 wouldn't help, because object_id is the second column.  That index is optimised for searching first on user_id, then on object_id.

idx_objt_access1 is not as good a choice as idx_objt_access_wtsi_1, because the latter index contains within itself all of the columns required by the SELECT, so PostgreSQL doesn't even need to go to the table data pages.  It can get everything it needs from the index alone.  That's what "Index Only Scan" means.

If we dropped idx_objt_access_wtsi_1, PostgreSQL would most likely switch to using idx_object_access1, but it would be somewhat slower, because PostgreSQL would have to read in the table data pages to get the values of access_type_id.  That said, there remains the possibility that it might revert to a full table scan, if it determined that the spread of values in the indexed columns isn't well-balanced.

**Comment by trel** [comment]
Right - all that makes sense.

So, at this time, there doesn't seem to be a good solution to optimizing the slowness of the `insert`s without giving up the power of the index for `select`s.

Well, without removing the transactionality of the multiple `insert`s.

**Comment by DavidHarper** [comment]
Having said that, I just dropped idx_objt_access_wtsi_1 on a clone of the SEQ zone database cluster that I've been using for benchmarking, and the SELECT part of the query ran very fast indeed.  CAVEAT: this PostgreSQL cluster has been configured with enough shared buffer cache to hold the entire database in memory, and the pg_buferache extension shows me that r_objt_access is wholly in the buffer cache, so no disk I/O was needed to fetch the table's data pages.

**Comment by DavidHarper** [comment]
But Simon created that index for a reason, and I would be very hesitant to remove it from the production database.  It might cause more problems than it solved.

**Comment by DavidHarper** [comment]
The performance of the SELECT is also acceptably fast (around 30 milliseconds) on another clone of the SEQ zone database which is configured with the same shared_buffers size (128 GB) as the production database, on the same model of host machine, and with the same type of back-end enterprise storage.

**Comment by DavidHarper** [comment]
Interestingly, the SELECT is a lot faster when I run it in psql rather than DbVisualizer: 0.8 ms versus 30 ms!  So the SELECT itself can run in sub-millisecond times.

When I simulate the INSERT/SELECT operation by running this query repeatedly inside a transaction in a psql session:

insert into R_OBJT_ACCESS (object_id, user_id, access_type_id, create_ts, modify_ts) (select nextval('r_objectid'), user_id, access_type_id, current_timestamp, current_timestamp from R_OBJT_ACCESS where object_id = 2399192);

I see execution times around 1 millisecond quite consistently, so the INSERT operation does not add a significant overhead in this environment.  If I simulate auto-commit mode by sandwiching the INSERT between a BEGIN and a COMMIT, the overall execution time is still only 1.5 ms.

It seems very unlikely that the INSERT/SELECT operation is the bottleneck here.

**Comment by DavidHarper** [comment]
Before I was a DBA, I was a software developer, working on a large data management application which had a database back-end.  Speaking now as a software developer, I'd point out that the INSERT/SELECT command in the code snippet shared by Alan King is generated dynamically at each execution, with a different value interpolated into the string at the '%s' on every invocation.  This means that PostgreSQL is forced to re-parse and re-analyse the query every time it's executed.  That may very well add a significant overhead, although I cannot tell you how much because I have not simulated the effect on our test databases.

**Comment by alanking** [comment]
Thanks for looking into this!

I'm definitely not a DBA. I am having trouble understanding why the string interpolation on the query would have that big of a performance impact. How would we get around this?

**Comment by DavidHarper** [comment]
The string interpolation has the potential to affect the performance of the query because, from the viewpoint of the database server, it's a completely new query each time, so it must be re-parsed and re-analysed to determine the optimum execution plan every time.

The most efficient way to execute the query would be to replace the %s with a '?' placeholder i.e. re-write it as

```
insert into R_OBJT_ACCESS (object_id, user_id, access_type_id, create_ts, modify_ts)
  (select ?, user_id, access_type_id, ?, ? from R_OBJT_ACCESS where object_id = ?)
```

then create a prepared statement object from it **and keep a reference to this object throughout the execution of the program**.  Then when the program needs to execute the query, it simply defines the values of all four placeholders in the context of the prepared statement object, and executes the prepared statement, using the appropriate database API calls for these tasks.  Most popular programming languages provide excellent support for prepared statements.  I assume that the ODBC API for C/C++ also has prepared statement support, but I have never used it, so I can't advise you on this.

**Comment by kjsanger** [comment]
Also affects `irmdir` to the same degree.

**Comment by kript** [comment]
Hey folks, have you had a chance to look into this? 

We're looking into changing the top level inheritance but @DavidHarper suggestion sounds a good way to reduce the overall load as well.

**Comment by alanking** [comment]
We have not. So far, we have only eyeballed the code and have not reproduced the issue as of yet.

In the example given by OP, are there many subcollections (and subcollections in those collections, etc.) with inheritance enabled as well?

Are the slow `imkdir` calls just under the collection(s) in question?

**Comment by kjsanger** [comment]
It affects any new collection on the zone to about the same degree. e.g. `/seq/test/kdj/` is empty

```
$ time imkdir /seq/test/kdj/0

real    0m13.250s
user    0m0.020s
sys     0m0.004s
```

**Comment by korydraughn** [comment]
> Before I was a DBA, I was a software developer, working on a large data management application which had a database back-end. Speaking now as a software developer, I'd point out that the INSERT/SELECT command in the code snippet shared by Alan King is generated dynamically at each execution, with a different value interpolated into the string at the '%s' on every invocation. This means that PostgreSQL is forced to re-parse and re-analyse the query every time it's executed. That may very well add a significant overhead, although I cannot tell you how much because I have not simulated the effect on our test databases.

Based on the code, the `%s` should always result in the same string value. Since you're running Postgres, `%s` would be replaced with `currval('R_ObjectID')`, resulting in a prepared statement the database should recognize. See `cllCurrentValueString` in the code snippets below.

https://github.com/irods/irods/blob/c48b524a12bc726cb616044d3460554cf70def1e/plugins/database/src/db_plugin.cpp#L4972-L4987

https://github.com/irods/irods/blob/c48b524a12bc726cb616044d3460554cf70def1e/plugins/database/src/low_level_odbc.cpp#L957-L967

This leads us to believe there must be something else causing the performance issue.

**Comment by DavidHarper** [comment]
As John has indicated, the most recent problematic query is an UPDATE, specifically:

update R_COLL_MAIN set coll_inheritance=$1, modify_ts=$2 where coll_id= currval('R_ObjectID')

The r_coll_main table in our largest iRODS database currently has more than 30 million rows.  Unfortunately, when PostgreSQL executes this UPDATE, it performs a full table scan, which currently takes about 30 seconds on a copy of the database running on identical hardware to the production database.  The explain plan for the query looks like this:

irodsseq=# explain update R_COLL_MAIN set coll_inheritance=123456789, modify_ts=123456789 where coll_id= currval('R_ObjectID');
                QUERY PLAN                 
--------------------------------------------------------------------------
 Update on r_coll_main (cost=0.00..1518087.96 rows=1 width=1373)
  -> Seq Scan on r_coll_main (cost=0.00..1518087.96 rows=1 width=1373)
     Filter: (coll_id = currval('r_objectid'::regclass))
(3 rows)

If the query is modified to replace the value that is being matched in the WHERE clause with an explicit number, the explain change changes drastically:

irodsseq=# explain update R_COLL_MAIN set coll_inheritance=123456789, modify_ts=123456789 where coll_id= 1234567890;
                    QUERY PLAN                     
-------------------------------------------------------------------------------------------
 Update on r_coll_main (cost=0.44..8.46 rows=1 width=1373)
  -> Index Scan using idx_coll_main1 on r_coll_main (cost=0.44..8.46 rows=1 width=1373)
     Index Cond: (coll_id = 1234567890)
(3 rows)

Now, PostgreSQL has correctly identified that it can use the index on the coll_id column to narrow down the row(s) to be updated, and on my test copy of the database, the UPDATE takes a few milliseconds.

**Comment by korydraughn** [comment]
I'm not familiar with all of the details of the `EXPLAIN` command, but based on what you're saying and what I've read about `EXPLAIN`, you're pointing out that the use of `currval('R_ObjectID')` is likely the reason for the 30 seconds.

Looking at the following things from that output seem to infer that:
- `cost`
- Use of `Seq Scan` instead of `Index Scan`
- Use of `Filter` which implies a full table scan

Does that sound correct?

With that said, we can investigate solutions to the use of `currval('R_ObjectID')`.

**Comment by trel** [comment]
Right, that appears to be the case - can we somehow already know/cache/use the value that `currval('R_ObjectID')` would have been in the database?    Since it's an update, and not an insert... it seems we could have already known/found that value somehow...

**Comment by trel** [comment]
> PGDG have rejected calls to add this functionality

Very interesting.

So, if we can get rid of this function call, we currently think that will help the `UPDATE` case.

Is it a horrible idea to call the function (`currval('R_ObjectID')`) in one SQL query from the application/client, and then use the result in the next query?   As long as they're in the same transaction?  Is that ... a safe/good workaround?    Ah, you answered that as I was typing this...

> my understanding is that PostgreSQL 11 is the latest version that is officially supported by RENCI as a back-end for iRODS

This is a limitation of the unixODBC version (and by extension, the OS/version that packages unixODBC).

Please see https://github.com/irods/irods/issues/5325 for a demonstrated workaround.

**Comment by korydraughn** [comment]
Right, I felt the use of `currval()` had to be the reason. Postgres likely can't make assumptions/optimizations around that call therefore we get the worst case.

Like @trel said, perhaps fetching that value ourselves resolves the performance issue. And if Postgres 14/15 include fixes for this, we can only hope that our change to fetch the value directly results in identical/similar performance.

**Comment by SimonEckford** [comment]
for `where coll_id = currval('r_objectid')`
the Postgres optimiser is choosing to make a full table scan to find rows with that coll_id value.

for `where coll_id = 123456`
the Postgres optimiser is choosing to use the idx_coll_main index to find such rows.  This is much faster.

Interestingly if you run it as subquery ie `where coll_id = (select currval('r_objectid'))`
then the Postgres optimiser seems to use the index.

So my suggestions would be to either explicitly use the actual value, or turn it into a subquery.
(with all appropriate caveats around testing)

**Comment by DavidHarper** [comment]
My investigations (see above) show that the UPDATE executes in just a few milliseconds if the value is given explicitly.  If you can cache the value in an application-side variable and then insert it directly, this WILL make the UPDATE run approximately a thousand times faster.  My colleagues at the Sanger are running data-loading pipelines which execute this query many thousands of times in each loading run, and we have seen the back-end database host maxing out all 48 of its CPUs for hours at a time whilst dozens of concurrent clients all run this UPDATE.

**Comment by korydraughn** [comment]
Could the sub-query performance boost be due to the database doing one query and caching the results?

That would be my only guess as to why it out performs the `coll_id = currval(...)`.

**Comment by DavidHarper** [comment]
Many thanks to Simon for this discovery.  I don't think I would have guessed that putting it in a subquery would solve the problem.  Truly, who can fathom the ineffable mysteries of PostgreSQL's query analyser?

**Comment by trel** [comment]
It's addressed for 4-2-stable.    Still need two cherry-picks please.
