### ISSUE TITLE
Server thread policy about threads

### ISSUE THREAD

**Issue by dekisugi123** [irods/irods#6503]
I read one of the dev comments that the thread of iput, iget, etc (-N) command is based on the server policy, but I never found it can exceeds 4. Is there anyway for me to increase that number?

**Comment by korydraughn** [comment]
Try tweaking the arguments to `msiSetNumThreads` in core.re: https://github.com/irods/irods/blob/ed98d6d66e861f6ace4f72769e8f251856153f4f/packaging/core.re.template#L236

**Comment by trel** [comment]
Here is an existing conversation as well ... https://github.com/irods/irods/issues/5701

**Comment by dekisugi123** [comment]
I have tried changing acSetNumThreads {msiSetNumThreads("default","default","default"); }  to acSetNumThreads {msiSetNumThreads("default","10","default"); } or acSetNumThreads {msiSetNumThreads("default","16","default"); } but seems like iput still use 4 threads (observed from iput -V)

**Comment by alanking** [comment]
Taking from this comment... https://github.com/irods/irods/issues/5701#issuecomment-1028356355

> `default_number_of_transfer_threads` is defined as "The number of threads enabled when parallel transfer is invoked." in the documentation (https://docs.irods.org/4.2.11/system_overview/configuration/)
>
> If `acSetNumThreads` invokes `msiSetNumThreads` and sets `maxNumThr` to "default", the setting will be honored. Otherwise, it will, as the name suggests, set a maximum thread count of whatever is put there, thereby overriding the default, which means, of course, that `default_number_of_transfer_threads` would have no effect.

If you use "default" for all 3 parameters of `msiSetNumThreads` in your `acSetNumThreads` definition, you can set `default_number_of_transfer_threads` to 16 in order to always use 16 threads in a parallel transfer:
```
$ cat /etc/irods/core.re | grep "acSetNumThreads" | tail -n1 # show my `acSetNumThreads` impl - all "default"
acSetNumThreads {msiSetNumThreads("default","default","default"); }
$ cat /etc/irods/server_config.json | jq '.advanced_settings.default_number_of_transfer_threads' # show my parallel transfer thread setting - 4
4       
$ iput -V 1GB_file 1GB_file__default_default_default__4
From server: NumThreads=4, addr:7f97665bf1f5, port:20169, cookie=1868474950
   1GB_file__default_default     953.674 MB | 0.792 sec | 4 thr | 1203.707 MB/s
$ cat /etc/irods/server_config.json | jq '.advanced_settings.default_number_of_transfer_threads'  # updated transfer thread setting to 16
16
$ iput -V 1GB_file 1GB_file__default_default_default__16
From server: NumThreads=16, addr:7f97665bf1f5, port:20009, cookie=2138139991
   1GB_file__default_default     953.674 MB | 0.907 sec | 16 thr | 1051.937 MB/s
```

The parameter you've adjusted - the second one - is determining the *maximum* number of threads allowed. The other two parameters influence the decision-making in the server regarding how many threads are *necessary* to fulfill the configured policy. In the cases you've tried so far, it has been less than 16. You can read more about the microservice here: https://docs.irods.org/4.3.0/doxygen/reSysDataObjOpr_8cpp.html#a7a95659e9fbae307da7295adba6d1360

Hope that helps
