### ISSUE TITLE
Remove problematic resources from mkresc

### ISSUE THREAD

**Issue by dekisugi123** [irods/irods#6520]
I accidentially used iput with -R for a problematic resource (the data path no longer works). Now, when I check ils, it shows nothing but I cannot remove it :

$ ils -r
  /tempZone/home/rods

$ iadmin rmresc newResc
remote addresses: 127.0.0.1 ERROR: rcGeneralAdmin failed with error -835000 CAT_RESOURCE_NOT_EMPTY
Level 0: resource 'newResc' contains one or more dataObjects

Using iquest to check: 
$ iquest "SELECT * WHERE DATA_RESC_NAME LIKE 'newResc'"
 ERROR: iquest Error: queryAndShowStrCond failed status = -1107000 NO_COLUMN_NAME_FOUND

**Comment by alanking** [comment]
The problem is that the GenQuery shown is not valid: The asterisk being used as a wildcard character for selecting attributes is not allowed. You should try changing it to this:
```
$ iquest "%s/%s" "select COLL_NAME, DATA_NAME where DATA_RESC_NAME like 'newResc'"
```
This will produce formatted output which shows all of the data objects on `newResc` as full logical paths.

You can also use `iquest attrs` to see a full list of attributes which can be selected.

Hope that helps!

**Comment by korydraughn** [comment]
Try running `irmtrash` (no arguments) to permanently remove data objects from the trash collection.

If you know you want to permanently remove a data object without it appearing in the trash, use `irm -f` instead of `irm`.

**Comment by alanking** [comment]
Dang, @korydraughn ninja'd me.

Some philosophy behind why we don't allow removing the resource, if that's interesting...

iRODS does not allow removing a resource which hosts any replicas of any data object because the data is under iRODS management. Removing the resource would cause the replica to be inaccessible through iRODS. Actually, the replica will be *unfindable* because the resource information will be lost. We know the resource that hosts the data because it's in the catalog, but the resource no longer exists, so we do not know what server is hosting the data anymore.

**Comment by dekisugi123** [comment]
I try this : 
`$ irmtrash
remote addresses: 127.0.0.1 ERROR: rmtrashUtil: rmtrash error for /tempZone/trash/home/rods, status = -515021 status = -515021 UNIX_FILE_UNLINK_ERR, Is a directory`

So I try : 
`sudo rm -r /var/lib/irods/new_vault/trash/home`
And then I can remove the resource. So I am not sure if this is a bug or I have done something wrong.

**Comment by alanking** [comment]
`/tempZone/home/rods` usually refers to the home collection of the user `rods`, so I'm not sure how it came to be associated with a resource (collections are purely logical entities). If you can tell us what you did to get here maybe we can piece together what happened. To me, it seems like a bug that you were able to get into this situation at all, but perhaps the only thing we can do is better document something or tighten up some options in a command or three.
