### ISSUE TITLE
Davrods and Dynamic Policy Enforcement Points

### ISSUE THREAD

**Issue by ll4strw** [irods/irods#6528]
- [x] main
---
iRODS v4.3.0
OS: Rocky8
davdods v1.5.0 (librods v4.2.11)

Hello, I am not sure if I am doing anything wrong, but If I set up my `core.py` as below
```
def pep_data_obj_put_post(rule_args, callback, rei):
    callback.writeLine('serverLog', '-----> Dynamic PEP <----')
def pep_api_data_obj_put_post(rule_args, callback, rei):
    callback.writeLine('serverLog', '-----> Dynamic PEP API<----')
def acPostProcForPut(rule_args, callback, rei):
    callback.writeLine('serverLog', '-----> Static PEP <----')
```
and I upload a file via webdav (davrods), then only the _Static Policy Enforcement Point_ seems to be executed, that is  I only get ` Static PEP` in my logs. Is there a specific reason for this?

**Comment by korydraughn** [comment]
I'm guessing you're using the Python Rule Engine Plugin (PREP) given the use of `core.py`.

Is the PREP the first rule engine plugin defined in server_config.json?

**Comment by korydraughn** [comment]
Is the Python REP installed and does it appear early in the list than the Native REP?

**Comment by alanking** [comment]
DavRODS does not hit the actual put API, but performs an open/write/close. Please see this comment for details on which dynamic PEPs are engaged in the put operation: https://github.com/UtrechtUniversity/davrods/issues/18#issuecomment-564083159

The dynamic PEPs respond to actual API calls whereas the static PEPs are placed wherever the developer feels like it. In this case, the "oprType" can be set and `rsDataObjClose` understands this as having been a "put" and so the static PEP fires in a hard-coded location.

**Comment by korydraughn** [comment]
@ll4strw Does that answer your question?

**Comment by trel** [comment]
You can write a separate rule with the work you want to get done... let's call it `ll4strw_code_chunk()`...

Then, you can call that rule from multiple different PEPs that 'catch' different API activity. 

```
# this will catch iput
def pep_api_data_obj_put_post(rule_args, callback, rei):
    callback.writeLine('serverLog', '--- pep_api_data_obj_put_post ---')
    ll4strw_code_chunk()

# this will catch davrods / python / istream
def pep_api_data_obj_close_post(rule_args, callback, rei):
    callback.writeLine('serverLog', '--- pep_api_data_obj_close_post ---')
    ll4strw_code_chunk()
```

This pattern can also be used with `_pre` to keep a list of open files, and their mode... so you can only fire your code on data objects that receive a write, rather than only open/read/close...  But that quickly can get complicated.... (open/seek/read/seek/write/seek/read/close).

This is the same approach we take with our rule engine plugins (logical quotas, indexing, etc...):
  https://github.com/irods/irods_capability_indexing/blob/main/libirods_rule_engine_plugin-indexing.cpp

Policy composition will make this approach easier to hold and reason about in the future... but we're not there yet:
    https://irods.org/ugm2021/ - search for "iRODS Policy Composition" for slides and video

**Comment by trel** [comment]
Excellent.

Is there anything else we can/should do in this issue?

Maybe add this type of example to the docs somewhere handy?

**Comment by trel** [comment]
@korydraughn did you add an example like this to your recent docs PR?   If so, please link it and close this.   If not... please use this issue for a new example.

**Comment by korydraughn** [comment]
There's no example for this in the docs. Will add one.

**Comment by alanking** [comment]
Since this is scoped for 4.3.1 as a Documentation exercise, I think the task is complete. Please close if true, @korydraughn. Thanks!
