### ISSUE TITLE
quota bug in v4.3

### ISSUE THREAD

**Issue by maithili-k** [irods/irods#6603]
## Bug Report
Quota in v4.3 is not getting enforced as expected

### iRODS Version, OS and Version
irods_version - 4.3.0
CentOS Linux 7

### What did you try to do and the errors seen
aim - test quotas for different groups in iRODS

steps:
1. Create a group in iRODS and set a global quota on it ( but we are using only one storage resource)
2. create a new rodsuser and add this user to the group
3. iput object (e.g., in /Zone/home/group1)
4. iadmin cu
5. run step 3 and 4 iteratively till the quota exceeds and a new object can no longer be written
6. irm the added objects from /Zone/home/group1 as well as /Zone/trash 
7. iput object to /Zone/home/group1. However I still get an error that the quota is exceeded. Looks like the usage is not getting updated (do I need an additional step here to update it?)
8. I can readjust the quota value using the iadmin sgq command, but somehow the usage is not getting updated. I am reporting it as a bug in 'quota' because this is where I experienced it (and also see below) and need it, but this could well be related to reporting/calculating usage only and not the actual setting/enforcing of quota
9. another (unrelated to above but relevant to quota) I see is the iquota command displays ALL set quotas, irrespective of if I query as a rdsuser or rodsadmin. Also the flags -u user, etc do not work

**Comment by trel** [comment]
The quota (re-)calculation is not done automatically (could be expensive on very active systems).

I think if you add step 6.5 `iadmin cu`... it will behave as you expect?

Production systems usually but `iadmin ci` in a recurring delay rule or crontab.

---

Regarding 9), please create a separate issue for the reporting from `iquota` not being what you expect in 4.3.0.

**Comment by maithili-k** [comment]
In step 4, I already run admin cu. So after every object 'iput' I run 'iadmin cu' and it works as expected. The problem is usage is not being updated after running 'irm' the objects followed by 'iadmin cu'. I expect the usage to be less once objects are removed (irm from the collection as well as trash) but despite completely emptying the collection (+cleaning up trash), I cannot iput any new object as I am always above quota due to non-updated usage.

I will investigate iadmin ci as indeed iadmin cu will be expensive in the long run.

I will create a new issue for the iquota command

**Comment by trel** [comment]
Without emptying the trash, your files will still be taking up space....   try `irmtrash` and/or `irm -f` when you remove a file to skip the trash.

**Comment by maithili-k** [comment]
yes I also emptied the trash each time as well, but the usage is not being updated.

**Comment by trel** [comment]
Well, that is troubling / incorrect.

So you never see the calculated totals go back down again?

**Comment by maithili-k** [comment]
No it didn't. I could update the quota value but the calculated usage did not go back down.

We did a full cleanup on the groups, quotas, etc on the server today and will start testing all over again. Making absolutely sure that we did not do something wrong in the initial setup itself. Will post my findings here

**Comment by AliceSLee** [comment]
Hello, an update (from the same team): 

Testing on a new, clean instance of iRODS 4.3 (also on CentOS 7) I couldn't recreate the issue where quota sums are not reduced after removing files and re-calculating (with user setup as described: user1 in group1, user2 in group1 and group2). This worked as expected. 

The remaining curiosity in the above scenario is that, when a user is in 2 groups, any file they upload counts towards the quota of both groups, i.e. it is double-counted. This may be by design, but we are interested in other options where only one group receives the storage allocation of an uploaded file (if possible, e.g. by group hierarchy).

**Comment by korydraughn** [comment]
> Testing on a new, clean instance of iRODS 4.3 (also on CentOS 7) I couldn't recreate the issue where quota sums are not reduced after removing files and re-calculating (with user setup as described: user1 in group1, user2 in group1 and group2). This worked as expected.

Great. So you discovered what the issue was with the first attempt?

> 
Hello, an update (from the same team):

Testing on a new, clean instance of iRODS 4.3 (also on CentOS 7) I couldn't recreate the issue where quota sums are not reduced after removing files and re-calculating (with user setup as described: user1 in group1, user2 in group1 and group2). This worked as expected.

The remaining curiosity in the above scenario is that, when a user is in 2 groups, any file they upload counts towards the quota of both groups, i.e. it is double-counted. This may be by design, but we are interested in other options where only one group receives the storage allocation of an uploaded file (if possible, e.g. by group hierarchy).

Can you provide an example of what you're seeing today and what you'd like to happen with group quotas?

Perhaps we can brainstorm a solution without needing to modify the server.

**Comment by AliceSLee** [comment]
Hi Kory, I'm afraid it remains a bit of a mystery why the quota wasn't going down before, but we will continue to try to figure it out and let you know of any revelations.

The second case relates to a user who is in group1 and group2, both of which have an allocated quota. If this user does an iput to upload a single file of 5k, then 5k is taken up from the quotas of both group1 and group2. I shouldn't have mentioned it above as it doesn't relate to the bug - sorry! We were just curious at time of writing to know if this had been discussed/if there are other approaches, but will take it off the table here. 

Thanks!

**Comment by korydraughn** [comment]
No problem at all.

If you have more questions or run into problems, please open a new issue.
