### ISSUE TITLE
igroupadmin should be able to remove groups

### ISSUE THREAD

**Issue by kript** [irods/irods#6888]
- [ ] main
- [ ] 4-3-stable
- [ ] 4-2-stable
---
## Feature

In 4.2.11 at least, `igroupadmin` cannot remove a group, but it can create and manipulate them.
Please add an `rmgroup` equivalent.

```
$ igroupadmin rmgroup test_6885
unrecognized command, try 'help'
$ igroupadmin -h
Usage: igroupadmin [-hvV] [command]

This is for users of type 'groupadmin' which are allowed to perform
certain administrative functions.  It can also be used by regular
users to list groups ('lg') and by the admin for all operations.

A blank execute line invokes the interactive mode, where it
prompts and executes commands until 'quit' or 'q' is entered.
Single or double quotes can be used to enter items with blanks.
Commands are:
 lg [name] (list group info (user member list))
 mkuser Name Password (make a user and set the initial password)
 atg groupName userName[#Zone] (add to group - add a user to a group)
 rfg groupName userName[#Zone] (remove from group - remove a user from a group)
 mkgroup groupName[#Zone] (make a new group)
 help (or h) [command] (this help, or more details on a command)

iRODS Version 4.2.11                igroupadmin
```

**Comment by trel** [comment]
I believe `rmgroup` is not included on purpose, but we will definitely think through it a bit more.

Regardless, the help text will be more helpful soon.

**Comment by d-w-moore** [comment]
Conspicuously, a `groupadmin` also cannot remove a user.  Perhaps the lack of `rmgroup` and `rmuser` are related / intentional.

**Comment by trel** [comment]
Yes, as both of those those would remove something from the entire system, not just the group that the groupadmin is managing.

**Comment by alanking** [comment]
The `igroupadmin` subcommands `atg`, `rfg`, `mkuser` have now received some love in 4-2-stable as far as testing...

I believe we need to do some work on the `igroupadmin` help text before closing this issue, if I understood the thread correctly. I will leave the box unchecked for now.

**Comment by d-w-moore** [comment]
Yes, I can see about doing that here and in the irods_docs repo.

**Comment by d-w-moore** [comment]
"Here" being  the in the icommands repo.

**Comment by d-w-moore** [comment]
Tried to check `4-2-stable` and `main` milestones, but not authorized.

**Comment by alanking** [comment]
I left the checkboxes unchecked because we need to do some work on the `igroupadmin` help text before closing this issue, if I understood the thread correctly. Just make sure we don't lose that work.

**Comment by korydraughn** [comment]
@d-w-moore Don't forget to cherry-pick from main to 4-3-stable.

**Comment by alanking** [comment]
To be clear, the following PRs have been merged with commits referencing this issue:

**irods/irods:** Adds igroupadmin tests
https://github.com/irods/irods/pull/6915 (main)
https://github.com/irods/irods/pull/6889 (4-2-stable)
https://github.com/irods/irods/pull/6917 (4-3-stable)

The following open (unmerged) PRs contain commits which reference this issue:
**irods/irods:** Add another test
https://github.com/irods/irods/pull/6938 (main)
https://github.com/irods/irods/pull/6939 (4-3-stable)
(no PR for 4-2-stable, yet)

**irods/irods_client_icommands:** Update the help text
https://github.com/irods/irods_client_icommands/pull/364 (main)
https://github.com/irods/irods_client_icommands/pull/365 (4-3-stable)
https://github.com/irods/irods_client_icommands/pull/362 (4-2-stable)

So, of the three items that I have been able to identify, adding tests is about halfway done, and adding the help text is not yet done.

If it's okay with everyone, I am going to uncheck the checkboxes (at time of writing, main and 4-2-stable are checked) so that we don't miss something because I'm having trouble keeping track of the progress.

Please let me know if I missed something or if we should check them again.

**Comment by alanking** [comment]
Oh, I found the missing 4-2-stable link. Edited comment above to account for it.

**Comment by alanking** [comment]
We did it
