### ISSUE TITLE
control_plane CMakeLists.txt

### ISSUE THREAD

**Issue by ll4strw** [irods/irods#6974]
- [x] main
- [x] 4-3-stable
---
Hi,
I am wondering what is the rationale behind the choice of overwriting `LD_LIBRARY_PATH` in the following `CMakeLists.txt`. 

https://github.com/irods/irods/blob/90e42c04246d57a9182fe67d9675dd89487706eb/server/control_plane/CMakeLists.txt#L11

When compiling from source I get all sorts of problems because `avrogencpp` does not find the libraries on which it depends. Would not it be better perhaps to modify an existing `LD_LIBRARY_PATH` instead of overwriting it? The following works for me

```
COMMAND "${CMAKE_COMMAND}" -E env LD_LIBRARY_PATH="${IRODS_EXTERNALS_FULLPATH_BOOST}/lib:${IRODS_EXTERNALS_FULLPATH_CLANG_RUNTIME}/lib:${IRODS_EXTERNALS_FULLPATH_AVRO}/lib:$ENV{LD_LIBRARY_PATH}" "${IRODS_EXTERNALS_FULLPATH_AVRO}/bin/avrogencpp" -n irods -o "${CMAKE_CURRENT_BINARY_DIR}/include/irods/server_control_plane_command.hpp" -i "${CMAKE_IRODS_SOURCE_DIR}/schemas/messaging/v1/server_control_plane_command.json"
```
Shall I open a PR?

**Comment by korydraughn** [comment]
This is the first time I've heard of this being an issue.

Please provide more information about how you're compiling iRODS.
Are you using packages from packages.irods.org or are you compiling everything from source?
What OS are you compiling on/for?

**Comment by korydraughn** [comment]
When you say you're building **everything** from source, does that include the externals packages?

**Comment by korydraughn** [comment]
Can you provide the EasyBuild script you're using for the externals packages and the iRODS server?

How does EasyBuild work? For instance, when it comes to building the externals packages, are you copying the instructions from the README into an EasyBuild script and running that or are you hand crafting something special?

**Comment by korydraughn** [comment]
I understand. Is that one of the real scripts you're attempting to use?

If so, that isn't going to work because iRODS has very strict requirements on the tools and versions used. For example, iRODS does not compile using GCC. We are working on that, but it's going to be a while before that is available. See https://github.com/irods/externals/blob/main/versions.json. See the README of the externals repo for additional information.

Have you considered using the [irods_development_environment](https://github.com/irods/irods_development_environment) for compiling everything? That repo can produce Docker images which can compile everything from source for all supported OS.

Aside from that, I'm surprised that the LD_LIBRARY_PATH causes an issue. The CMakeLists.txt file expects the externals packages to be installed at a specific location. If everything is in the right place, then only those paths in the LD_LIBRARY_PATH should be necessary. Of course you suggestion isn't incorrect, but before we go and change the server, we have to understand the problem first.

**Comment by SwooshyCueb** [comment]
> Would not it be better perhaps to modify an existing `LD_LIBRARY_PATH` instead of overwriting it?

Honestly I thought we already were prepending to the existing `LD_LIBRARY_PATH`, as I specifically remember writing it to do so. I suppose it might've gotten lost in a rebase at some point. A PR would be welcome; I'll do it myself if you don't.

> Why doesn't irods compile with GCC?

As Kory said, when we originally decided to target Clang, GCC was lagging behind. These days the story is a bit different. Last I checked, it is possible to *compile* with GCC, but it requires passing `-fpermissive` and turning off `-Werror`. We have some CMake instrumentation for this. The thing is, last time I tried using a build of iRODS compiled with GCC, it was extremely unstable. Getting that fixed is on my list of things to do, but it's not super high priority at the moment.

Regardless, if you're pulling dependencies from EasyBuild instead of our externals packages, you will likely need to compile against `libstdc++`, regardless of which compiler you use. There's some CMake instrumentation for this as well, but you may have to change a few variables to get it to work.

**Comment by korydraughn** [comment]
@ll4strw Please submit a PR and we'll look it over.

**Comment by alanking** [comment]
The original issue as reported has been resolved. However, it seems there may be other things left unresolved in this issue.

@ll4strw - Shall we close this issue? We can continue to assist with build issues via discussions in this issue, or we can open new ones as problems arise.

**Comment by korydraughn** [comment]
Is your EasyBuild solution available on github? It may be useful for other people.

**Comment by trel** [comment]
very interested to try this.

the linked repo appears to be missing the `easyconfigs` directory?

**Comment by trel** [comment]
We are watching your irods_easybuild repository now (thanks) - and can have discussion there.

@alanking I think this issue is complete and can be closed?
