### ISSUE TITLE
SQL statement leak: too many concurrent statements

### ISSUE THREAD

**Issue by dworkin** [irods/irods#7050]
- [x] main
- [x] 4-3-stable
- [x] 4-2-stable
---
Missing call to cmlFreeStatement. I made a pull request for 4-2-stable, but the other branches are also affected.

**Comment by dworkin** [comment]
We ran into the 'too many concurrent statements' issue, without obvious cause. So I'm auditing the relevant code.

**Comment by dworkin** [comment]
That's all (for this audit).

**Comment by dworkin** [comment]
Well, that was embarrassing.  I had assumed that `freeGenQueryOut` worked like `cmlFreeStatement` at the lower level, and it doesn't.  All of those "statement leaks" are mere memory leaks, and I have withdrawn my related pull requests.

However, there *is* a statement leak in `checkPermissionByObjType`. It can be triggered as follows:
- generate 260 new groups with `iadmin mkgroup`
- put the `rods` user in each group with `iadmin atg`
- create a dataObj `foo` which the `rods` user does not have access to
- execute the following code in an endless loop:
    `*access=0; msiCheckAccess("foo", "read object", *access);`

The cause is that `checkPermissionByObjType` does not take into account that there could be more than one page of SQL rows.

**Comment by korydraughn** [comment]
We'll reproduce and get a fix in. Thanks for finding this.

**Comment by dworkin** [comment]
The code below is similarly afflicted:

https://github.com/irods/irods/blob/5b4b6530ab86c9cb7fc71990b50d3ffc53458570/server/re/src/reIn2p3SysRule.cpp#L494

**Comment by alanking** [comment]
I was able to reproduce the issue by writing a test as described by @dworkin in https://github.com/irods/irods/issues/7050#issuecomment-1516615931.

Here is the rule that I wrote:
```python
check_access_a_lot {
    *big_number = 51;
    *incr = 1;
    for (*i = 0; *i < *big_number; *i = *i + *incr) {
        *access = 0;
        msiCheckAccess("*logical_path", "read object", *access);
    }
}
INPUT *logical_path="/tempZone/home/rods/foo"
OUTPUT ruleExecOut
```
It turns out that you only need 51 iterations of the loop to get this result:
```bash
$ irule -r irods_rule_engine_plugin-irods_rule_language-instance -F rule.r 
remote addresses: 127.0.0.1 ERROR: rcExecMyRule error.  status = -1105000 INVALID_OBJECT_TYPE
Level 0: DEBUG: execMicroService3: error when executing microservice
line 5, col 8
        msiCheckAccess("*logical_path", "read object", *access);
        ^
```
With 50 iterations, you get errors in the logs ("too many concurrent statements") but no error comes out on the `irule` end. With 49 iterations, there are no errors at all.

The error is a failed query that happens inside this microservice and it fails because there are too many concurrently opened database statement handles.

With the change in #7066, the issue is resolved.

**Comment by alanking** [comment]
Thanks, @dworkin!
