### ISSUE TITLE
The server must reject overlapping requests to change where the delay server runs

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7137]
- [x] main
- [x] 4-3-stable
---
## Bug Report
If delay server migration is in progress, attempting to interrupt that operation must result in an error or a NOOP.

For example ...
```bash
iadmin set_delay_server node1
iadmin set_delay_server node0
error: Delay server migration already in progress. Try again later.
```

**Comment by trel** [comment]
Why is this necessary?     The design should be resilient in the face of such requests.   The latest should 'win'.

**Comment by korydraughn** [comment]
Migration is not atomic. There is an opening in which there can be two delay servers.

To keep the system stable, we have to let the migration finish.

**Comment by trel** [comment]
Hmmm, then we have a bug in the design...

**Comment by korydraughn** [comment]
It's not a bug in the design. It is because the set of operations to achieve migration are not carried out as one atomic operation. Timing is also a factor here.

**Comment by trel** [comment]
For the window of time that you are describing... I think the following addition will remove it with limited impact on performance (since this is already in the delay server logic)...

The delay server itself should fetch the current 'leader' information from the catalog, and only if it matches itself, continue to fetch the next set of delay rules to execute.

---

The checking logic from the main server: 
https://github.com/irods/irods/blob/124c9eae12062e50ad73d0436ba1eb76b63149af/server/main_server/src/rodsServer.cpp#L820-L826

which calls...
https://github.com/irods/irods/blob/124c9eae12062e50ad73d0436ba1eb76b63149af/lib/api/src/rc_get_grid_configuration_value.cpp#L7-L10

---

I propose we do the check just prior to preparing to fetch the next rows (line 798)...

https://github.com/irods/irods/blob/124c9eae12062e50ad73d0436ba1eb76b63149af/server/delay_server/src/irodsDelayServer.cpp#L794-L802

This makes it effectively a three-phase migration, rather than two-phase.
1. admin sets 'successor'
2. main server walks algorithm on each machine, promotes self to leader or starts/stops own delay server
3. delay server confirms on each loop that it is still designated as leader before doing any work

I think that removes the window of time when two delay servers could both grab the same rules.

**Comment by alanking** [comment]
@FifthPotato - Please close if complete. Thanks
