### ISSUE TITLE
Should a successful call to `rc_switch_user` close all open data objects?

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7197]
- [x] main
- [x] 4-3-stable
---
## Question
If I open one or more data objects as alice and then become bob via a call to `rc_switch_user`.

Should all data objects opened by alice be closed?

Are there other things that need to be closed or reset? Tickets, but what else?

**Comment by trel** [comment]
Could you switch back to alice and be expected to work on those previously opened data objects?

**Comment by korydraughn** [comment]
Does that sound like something useful?

Could be cool, but it's probably a security risk because those objects are accessible to the switched-to user. They could potentially have read and/or write access to data they wouldn't otherwise.

**Comment by trel** [comment]
security risk is a problem and more important than possible use case of switching back to alice on purpose.

agreed - i think closing any open handles is the safest.

**Comment by korydraughn** [comment]
Which is more appropriate?
- Closing all open data objects for the user on the call to API plugin?
- Or, making the API plugin detect open data objects and returning an error if any are found?

**Comment by trel** [comment]
hmmm.

so... it's either a side-effect of calling this API that any open handles are closed
OR
requires documentation / learning by the programmer to prepare the ground before calling

feels more 'atomic' to have the API do the work, and having the side-effect.

seems there is less chance for contention and possibility for uncoordinated writers to get mixed up / trip each other.

so... I think I'm voting for the API closes any found, itself.

anyone else?   bueller?

**Comment by korydraughn** [comment]
If the API plugin is responsible for closing things, what should it do if it fails to close a data object?

I can see this going either way, but that question I just asked pushes me in the direction of having the API plugin return an error if open data objects exist. Doing that pushes the job back on the client to properly clean up behind themselves.

Also, what if this is a parallel transfer over 1247?

**Comment by alanking** [comment]
We close all open file descriptors when tearing down an agent. If anything at all goes wrong during the closing or finalizing of the data object, it frees the descriptor, unlocks the object and marks the open replica as stale, and continues to tear down. I imagine something similar happening in this API because calling switch user is basically the same as disconnecting without having to reconnect/respawn an agent, as I understand it.

The parallel transfer over 1247 issue exists for any misbehaved client, because the other agents would not be aware that the object they are writing to has just been unlocked without the client coordinating with the "main" writer. Fortunately, the replica being written to would be marked stale and the writers are not responsible for finalizing. So the not-good-ness of the replica would be cataloged. However, that does allow the data object to be opened again in an uncoordinated fashion, which would lead to even more bad results.

Hmm...

**Comment by trel** [comment]
so, upon further discussion, we're moving forward with API plugin taking a new keyword/option to request the behavior:
 - throw error if any open objects exist (default)
 - close any open objects first

this is flexible and leaves additional cases a possibility later (close and finalize, etc...)

**Comment by alanking** [comment]
So the answer to this question was "yes"? Should we add an "enhancement" label or something to that effect for tracking purposes?

**Comment by korydraughn** [comment]
The API was adjusted to give the caller the option to choose what should happen. That is, they can instruct the API to do one of the following:
- Return an error if there is at least one open replica _(this is the default)_
- Close all open replicas and mark them stale

This is an enhancement.
