### ISSUE TITLE
Proposal: even/odd versioning

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7360]
This is one of two related proposals meant to address related problems.

At present, we increment version numbers in project repositories just before a release. **This is a good practice and we should keep doing this**, as it ensures that a release version number will always be greater than one from a development build from *after* the previous release but *before* the release in question.
However, this also presents the challenge to downstream projects that are developed side-by-side with iRODS: How to detect that the version of iRODS being used or built against is a development version. In my opinion, it should not be up to the developer to tell the buildsystem what version of iRODS it is actually building against, nor should it be up to iRODS users to tell clients that the version reported by the iRODS server should be taken with a grain of salt.

I am proposing that we change how we handle version numbers for iRODS to resemble the [even/odd pattern](https://en.wikipedia.org/wiki/Software_versioning#Odd-numbered_versions_for_development_releases) used by many other software projects: we will continue to increment the iRODS version number just before a release, but we will also increment the version number *again* post-release.

With this change to our versioning, downstream projects can use the version number to differentiate between the most recent release of iRODS and a development build.

This change also comes with some additional benefits:
- If a downstream project that inherits iRODS' version number is built against a development version of iRODS, it will be evident in the version number.
- When a user reports an issue with iRODS (or a downstream project that inherits iRODS' version number), we can tell from the version number whether they are using a development version.

One of the arguments *against* the even/odd versioning pattern is that it creates confusion for end-users about whether or not a release is a development version. In our case, this will not be applicable, as instead of releasing development versions, we will just be skipping every other version number for our releases.

**Comment by trel** [comment]
Gnome's conversation about moving away from even/odd versioning in 2019/2020
 - discussion - https://discourse.gnome.org/t/straw-man-proposal-changing-the-gnome-versioning-scheme/1964
 - decision - https://discourse.gnome.org/t/new-gnome-versioning-scheme/4235/10

---

Python's PEP 440 – Version Identification and Dependency Specification
 - https://peps.python.org/pep-0440/

**Comment by trel** [comment]
As I understand the problem...

1) We cannot use a '.90'-style version in our stable branches because we are already using all three of our allocated three-segment version scheme for the server itself...  aka 4.2.12 and 4.3.1, etc.   And changing the third segment to be '90' during development would mean that we'd be 'lowering' the version just prior to release... and that's bad for comparison/packaging.

2) We cannot use a fourth segment because we already have a convention for our plugins to add a fourth segment to indicate what it was built against... aka the third release of the storage tiering plugin built against 4.3.0 would be 4.3.0.2.

**Comment by trel** [comment]
If iRODS 5 moves to only use two segments for releases instead of three...

The freed third segment could be used either for...
a) Setting to '.90' during development (removing the need for even/odd numbering?). Is this wasteful?  Weird?
OR
b) Use by plugins (giving both the server and the plugins two segments each).  Is this helpful?  Interesting?

**Comment by trel** [comment]
Development work is now using the .90-style numbering (as part of https://github.com/irods/irods/issues/7361 and https://github.com/irods/irods/issues/7531).

I think we can close this issue as resolved/invalid as it is no longer necessary/applicable.
