### ISSUE TITLE
add documentation for writeLine()

### ISSUE THREAD

**Issue by trel** [irods/irods#7388]
- [x] main
- [x] 4-3-stable

---

## Feature

I went looking for the helptext for the system microservice `writeLine`, but could not find it.

implementation is here...

https://github.com/irods/irods/blob/4.3.0/plugins/rule_engines/irods_rule_language/src/functions.cpp#L1968

**Comment by JustinKyleJames** [comment]
I am assuming this is old?

https://github.com/irods/irods/blob/c5987967f34974a2074148edcf5437477545ebaa/server/re/src/printMS.cpp#L14-L51

**Comment by trel** [comment]
oh, does that appear in Doxygen if we link it up correctly?    which is a separate question of whether it is correct/good...

**Comment by korydraughn** [comment]
I don't think you want to link to that specific function due to its parameters. If there's no MSI for `writeLine` containing only parameters of the form `MsParam*` + `RuleExecInfo*`, then we have to make doxygen produce it.

There are examples of this in the microservice plugins. Each plugin has documentation at the bottom that is introduced when a certain macro is defined.

**Comment by alanking** [comment]
@JustinKyleJames - Close if complete. Thanks

**Comment by JustinKyleJames** [comment]
Closing
