### ISSUE TITLE
Server does not terminate agents after graceful shutdown period

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7619]
- [x] main
- [x] 4-3-stable

### iRODS Version, OS and Version

iRODS 4.3.1, Ubuntu 20.04

This occurs on tip of main too.

### What did you try to do?

Launch a long running operation and watch the server kill the agent after the shutdown grace period.
```
kory $ istream write foo
```

In a separate terminal, attempt to shutdown the server.
```
irods $ ./irodsctl -v stop
```

### Expected behavior

All iRODS processes are shutdown. The agent handling the istream operation is killed.

### Observed behavior (including steps to reproduce, if applicable)

The server shuts down, but the agent handling the istream operation still exists.

**Comment by alanking** [comment]
Confirmed that this issue exists in 4.3.0 and *not* 4.2.12.

Sidebar: The data object created by `istream` in this instance is left stuck in the intermediate state when this happens. I don't think there's anything we can do about that given that the process responsible for finalizing it is supposed to be killed.

**Comment by alanking** [comment]
Small update here... Here's a table of platforms where this issue exists. All of this was done in the irods_testing_environment:

| platform | commitish | issue exists? |
| ---- | ---- | ---- |
| Centos 7 | 4.3.1 | no |
| Centos 7 | 4.3.0 | no |
| Ubuntu 18.04 | 4.3.1 | no |
| Ubuntu 18.04 | 4.3.0 | no |
| Ubuntu 20.04 | 4.3.1 | yes |
| Ubuntu 20.04 | 4.3.0 | yes |
| Ubuntu 22.04 | 4.3.1 | yes |
| Almalinux 8 | 4.3.1 | no |
| Almalinux 8 | 4.3.0 | no |
| Debian 11 | 4.3.1 | yes |
| Debian 11 | 4.3.0 | yes |
| Debian 12 | 4.3.1 | yes |
| RockyLinux 9 | 4.3.1 | yes |

So it seems that the newer platforms demonstrate the issue while the older ones do not.

Investigation ongoing...

**Comment by alanking** [comment]
I put this in my commit message, but I'll put it here too just in case...

The way the server is being shut down was reworked in commit https://github.com/alanking/irods/commit/1a5b0399141de3448390a2d875290c60f669342e.

There is a place where a list of processes descending from the main server process is being created by using the filter() built-in command. The original implementation was written for python2 because all of our supported platforms used python2. In python2, filter() calls return the filtered iterable. Modern platforms we support use python3. In python3, filter() returns a filter object, not an iterable.

There is no benefit to delaying generating the filtered list, so this commit generates the list immediately by wrapping the call to filter() with list().

**Comment by korydraughn** [comment]
Excellent.
