### ISSUE TITLE
Cannot capture `replica_status` 

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#7910]
### iRODS Version, OS and Version
4.3.2, almalinux8

### What did you try to do?
I tried to capture the replica status information when the object is at rest matches catalog. That is, I wanted to see/capture the status "good" somehow when the object is located in irods correctly. Also, in order too see another status other than "good", I tried to reproduce the case that makes an object not "good". 

### Expected behavior
To be able to get `replica_status` in a relevant pep.

### Observed behavior (including steps to reproduce, if applicable)
 Say I am uploading a 100BM data object by a client other than iCommands, and while the content being written at some point I cut the process (ctr.+c), then I am seeing `pep_api_data_obj_close_*` is never triggered (so the `DATA_OBJ_CLOSE_AN` api is not called). The status of the object is seen as "X" (replica_status is `0`). 

If I would like to know the `replica_status`, it seems not possible to get it except in `pep_database_reg_data_obj_*`

I might be misinterpreting but the `pep_api_data_obj_lock_*` is not fired after the status of an object is not "good", in another word the replica status is not `1`. Or at least in of these (`pep_api_data_obj_close_post`, `pep_api_data_obj_write_post`) I would expect to see the `replica_status` key is available with some integer values.

Because currently the order of how PEPs are working as follows (`pep_api_data_obj_open_pre, pep_database_reg_data_obj_pre, pep_database_reg_data_obj_post, pep_api_data_obj_open_post, pep_api_data_obj_write_pre. pep_api_data_obj_write_post ... pep_api_data_obj_close_pre, pep_api_data_obj_close_post`) and as far as I understand this will never make it possible to see another value other than `2` (intermediate status, `?`) in `pep_database_reg_data_obj_*`. This is almost same as well for the put api.

**Comment by trel** [comment]
You can always get the status from the catalog via query when you're interested in it.  If you're interested in the status 'before' an upload, then that is when you would want to query and get the current status.

Yes, it will almost always be 'intermediate/?' status when it is being written and before it is closed/finalized.

**Comment by mstfdkmn** [comment]
> You can always get the status from the catalog via query when you're interested in it.

Yeah, but wouldn't querying the database after every upload be a bit much?

I was supposing there must be a way to follow up the status of replica with apis called in the same process. Because the replica_status is an attribute in the db but it is not clear when it is updated, as a user I know it is recorded as "2" when the object is first registered in the db but in the later stages I cannot follow. Two naïve thoughts:
- if pep_database_reg_data_obj_post could have been triggered just before pep_api_data_obj_close_post, I guess we would have known the changing status. ?
- if one of the api pep like pep_api_data_obj_write/close_post could have contained the replica_status info, again we would capture it.?

**Comment by korydraughn** [comment]
Agreed.

If you're concerned that executing another query will degrade performance, the only way to be sure is to measure the cost. Not only will that help you make a decision about whether an additional query is acceptable, but that will also give the Consortium a baseline to work with.

Who knows, it could spark efforts to see if query performance can be improved.

**Comment by mstfdkmn** [comment]
Thanks for all answers. I guess I got it.

@alanking Alan, I was intrigued by "This API is called from a few different APIs..." and in the link you shared, I found this part interesting: "The trigger_file_modified field is a boolean indicating whether the file_modified plugin operation should be called after the data object has been finalized". So, I have one last question:

In which condition or by which user action `pep_api_data_object_finalize_*` are invoked? Can these be used in a policy implementation?

**Comment by alanking** [comment]
> In which condition or by which user action pep_api_data_object_finalize_* are invoked? Can these be used in a policy implementation?

`pep_api_data_object_finalize_*` is invoked whenever the `data_object_finalize` API is invoked in such a way that it "crosses the API plugin boundary". Although the API is invoked internally by the server every time a data object is modified, the PEP is not triggered because it does not cross the "plugin boundary" like a client call does. It is basically just a normal function call in the same agent process which does not involve any API PEPs.

To my knowledge, none of the Consortium-maintained clients invoke the `data_object_finalize` API directly. They all use `data_object_close` or `replica_close`.

For completeness, the PEP I was suggesting hooking into above is the database operation - `pep_database_data_object_finalize_*` - not the API. Just wanted to make sure that was clear.

**Comment by alanking** [comment]
@mstfdkmn - Do you have any more questions for this topic?

**Comment by mstfdkmn** [comment]
No, thanks.

**Comment by alanking** [comment]
Okay. Closing.

**Comment by mstfdkmn** [comment]
Hi @alanking ,

Does the "status" attribute in the `pep_api_data_object_finalize_` message represent the status of the object on which it was called?

![image](https://github.com/user-attachments/assets/a1326a33-eed7-4f04-9659-3c56ec055ea0)

**Comment by alanking** [comment]
No, that is probably referring to some error code status in the `RsComm`.

You should not be implementing a PEP for `pep_api_data_object_finalize_*` because that is not reliable across clients. Rather, you should implement `pep_database_data_object_finalize_*` because the close APIs call the data_object_finalize API internally which will not trigger the API PEPs, but it will trigger the database PEPs.

I've recently added an example to the Policy Cookbook for this that may prove useful: https://github.com/irods/irods_docs/blob/d785747a2974409e4775113fb94bffbd2961faf4/docs/administrators/policy_cookbook.md#step-2a-implementing-data_object_finalize

**Comment by mstfdkmn** [comment]
Thanks. My bad was a wrong copy/paste. I meant `pep_database_data_object_finalize_*` as you may see in the screen-shot posted. But via the PREP I couldn't manage to get the `json_input` you exemplified in the Policy Cookbook.

For example the snippet below doesn't output something that I can use.
```
def pep_database_data_object_finalize_post(rule_args, callback, rei):
    callback.writeLine("serverLog", f"{dir(rule_args[3])}")
    # same for rule_args[2]
```

**Comment by alanking** [comment]
The `dir` call does not show anything apparently useful because `rule_args[3]` contains a regular string holding a JSON object. You can call `json.loads` and operate on it as a proper JSON object in Python.
