### ISSUE TITLE
change ichmod to handle the full range of the iRODS permission model

### ISSUE THREAD

**Issue by trel** [irods/irods#844]
_Originally Opened: @trel (2012-06-15 15:01:01_)

in `iRODS/server/icat/src/icatSysInserts.sql`, the current model for permissions involves 18 levels of control, significantly more than the 4 provided/suggested/explained via `ichmod`.

`ichmod` grants possibility for assigning [null/read/write/own].

the full model is linear and has:

```
insert into R_TOKN_MAIN values ('access_type',1000,'null','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1010,'execute','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1020,'read annotation','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1030,'read system metadata','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1040,'read metadata','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1050,'read object','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1060,'write annotation','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1070,'create metadata','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1080,'modify metadata','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1090,'delete metadata','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1100,'administer object','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1110,'create object','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1120,'modify object','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1130,'delete object','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1140,'create token','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1150,'delete token','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1160,'curate','','','','','1170000000','1170000000');
insert into R_TOKN_MAIN values ('access_type',1200,'own','','','','','1170000000','1170000000');
```

`ichmod` should expose the full range and explain how to use them all.

this came about with Shoffner's work with Genomics Data Grid - we wanted to create a shared directory with write access for one service account, and read access for everyone else.  the service account could create directories and files, but then could not delete them.   the interim solution is to grant the service account full 'own' permissions.  but this is not ideal because a compromise of that user could allow the granting of permissions to other users (an escalation attack).
## 

From: https://code.renci.org/gf/project/e-irods/tracker/?action=TrackerItemEdit&tracker_item_id=844

**Comment by deardooley** [comment]
I believe there is a chance the permission system may be modeled incorrectly for the scale and use cases for which it is intended to operate. Some thoughts after building and supporting end-user tools, middleware, and SaaS solutions on top of IRODS for the last 9 years.
  > ***end-users***: people who know nothing about IRODS and are just trying to get work done. They may or may not be interacting with the system directly through iCommands, but are not coding and expect things to "just work".
  > ***users***: organizations, projects, or applications who adopt IRODS for their technology needs. They are the ones doing all the integration, support, and tuning of an IRODS deployment.
  > ***idevs***: IRODS development team

* A linear permissions model isn't really helpful, and actually runs contrary to pretty much every modern data management solution end-users interact with in everyday life. This causes endless support questions for your users. That's probably not something showing up in the IRODS GitHub issues due to the level of administration between end-uses and idevs, but it's an unnecessary adoption cost your users.
* The permission model leading this issue isn't a permission model, it's a flattened, restricted role system without granular access. This makes building anything with moderate complexity on top of IRODS impossible without a "super" user account that turns around and implements granular access control. IMHO, it's better not to have a permission system when you're going to require all your users to implement a partial permission system on top of yours.
* From a user standpoint, an ongoing issue is that permissions are treated as verbs rather than individual metadata objects associated with data, metadata, and collections. In v3, this meant that permission checks were not possible because you got back an ambiguous answer. In v4, permission checks are even less clear because (based on the documentation) the PEP model won't give any information about the underlying cause. IMHO, when you don't have a finite state representation of your permission model, you are hating on your users. Don't hate on your users, they just want to be loved.
* Speaking of user love, error responses are in serious need of documentation and consistency auditing. If I were to check write access on a collection for which the underlying system account is over quota, I would get back a "data not found" error. Not only is that incorrect, it's misleading. Please show users some love by making error responses clearer and consistent, especially as IRODS turns into a sprawling distributed system. Which leads to the next point...
* Until now, IRODS has conveyed the message that user and end-user interactions are effectively stateless. That has never really been the case and, under load, leads to users feeling very hated on. For example:  
  * Microservice processing takes time. There may be many of them that need to be processed for a particular transaction. IO latency is present. Communication latency is present. Time and ordering are not guaranteed across the system. The result is, at best an obvious mess, and at worst silent data corruption that only shows up in experimental results. The chocolate factory is real and has to be avoided at all costs.
  >  [![I Love Lucy's Famous Chocolate Scene](https://cloud.githubusercontent.com/assets/785202/9151952/f1769e44-3ddb-11e5-84b9-764fdd018f1e.gif)](https://www.youtube.com/watch?v=8NPzLBSBzPI)  
  * Replication is awesome, but Physics is Physics. Propagating the data takes time and that information isn't available without digging. There needs to be an easier way to let users know that their data is in flight. That's true for concurrent read/write access as it is for accessing federated data from replica resources. Lessons learned from the world of tape storage would be helpful here, as would explaining that IRODS was not designed with, but does operate under a model of...   
  * Eventual consistency. To end-users, it looks like a broken system when they don't about it. Try explaining that to them after the fact. The conversation always winds up looking like 
    <p class="text-align:center; width:100%;">
<img src="https://cloud.githubusercontent.com/assets/785202/9151947/ccdcbf32-3ddb-11e5-9608-4988ec2dfe59.jpg" alt=Eventual consistency"  width="150"  style="width:150px; height:150px;">
 <img src="https://cloud.githubusercontent.com/assets/785202/9151940/a9b1b54e-3ddb-11e5-9d4c-d98cfd121b39.jpg" alt="So you're telling me you don't have my data" width="150" style="width:150px; height:150px;"></p>
  A little communication goes a long way. Help your users convey what's going on by providing hooks, sentinels, or additional attributes in the data objects allowing them to set expectations for their users.

**Comment by jasoncoposky** [comment]
@deardooley 

To start, props for the brilliantly illustrated github comment.  There is a lot to unpack here so I will try to briefly cover it in sections.

As this is an issue related to ichmod we can begin with the permissions model.  I would agree that it needs some work but as we have guaranteed that the 4.x series will be capable of federation with the legacy 3.x code we have not made this a priority.  If this is a topic that is made more of a priority by our membership and the broader community we will spin up a working group and issue a call for participation in order to capture the uses cases and feedback before building something new.

Regarding item number 4, I agree the error reporting needs to be improved.  This has been an ongoing effort since we began this project and continues to get better with every release.

With regard to item number 5 and consistency, a primary with issue with iRODS is that proper locking has never been implemented.  As of the 4.1 release the locking RPC calls can now be overridden with plugins.  It is our intention to release several implementations using zookeeper and other technologies to provide proper distributed locking in the near term.  How the client side reacts to the locking of data objects is another matter that will need smoothed out.

We are now in a position where iRODS is being used in ways that are well outside the initial design.  iRODS was designed with the icommands in mind where each operation was atomic in nature, the agent did not return to the client until it was finished and the agent was then released. There was little need for locking or fine grained communication with the client side.

With the advances in Jargon, the REST interface and the expectations created by interactive GUIs created by @michael-conway  and others, iRODS is now expected to be reactive and tightly coupled with the client side, having pools of long running processes in flight and ready to respond.  This is a primary motivator for our design of a new API which removes the burden from the client side, and will services these new use cases more directly.

**Comment by michael-conway** [comment]
Discussion again with Rion, we need to elevate this issue

**Comment by DukeVimes** [comment]
@trel 
I see this issue has been open for quite some time. We have the same requirement (setting the ACL of a collection to something like 'modify_metadata' -> 1040 using ichmod). Currently we use a workaround. Are there any plans regarding this issue? Or if we were to modify ichmod ourselves (just allowing for numerical values to be set), would there be chance for the changes to be integrated into the next release?

**Comment by DukeVimes** [comment]
@trel 
basically we are modifying the r_objt_access table directly and set the access_type_id to 1040 or similar. I did test some icommands, e.g. ils displays the correct token string ('modifiy metadata') and iget/iput/imeta worked as expected.

That's why I assumed the issue is only with setting those rights via ichmod, now I feel less confident whether this is a viable route. Any further advice would be much appreciated!

**Comment by trel** [comment]
Ah, okay - this is good.  A list of conformance tests that you are finding comforting would be good to have listed here, as a start for whatever gets added to the test suite for this issue.

The permissions model is linear, and most of the checks in the code are of the type `>=`, so it's good to know that they're behaving for you, so far.  Maybe there isn't as much to change in the server, as that an audit of multiple code paths needs to happen - and tests need to be written.

To confirm, yes, changing the `access_type_id ` value directly is exactly what `ichmod` would do.  If that is working for your scenarios for now, I can't think of any other immediate concerns.  You may wish to confirm that `iquest` is honoring the new permission as expected as well.

One note - clients like Metalnx and ZMT probably will require some attention/changes to honor any additional permission levels - there are a number of hard-coded matches for 'own' or 'read' in their logic.

**Comment by trel** [comment]
working on this alongside #6397 #5277 https://github.com/irods/irods/issues/5276

**Comment by trel** [comment]
We exposed/increased the Permission Model to 10 levels, not the original/described 18.
